### ISSUE TITLE
Where to get the source code of  demo  rooms like tryit(http://chotis2.dit.upm.es/)

### ISSUE THREAD

**Issue by xiliu** [ging/licode#118]
Some demo rooms in the http://chotis2.dit.upm.es/ are very nice, i want to get those source code of demo,so where i can get those demo? thanks..

**Comment by nachoaguadoc** [comment]
Hi, in case any of you is still interested in getting the source code of the demos, it can be downloaded from here https://github.com/ging/licode-demos

Best regards

**Comment by JohnnyC1951** [comment]
Could someone post a working example of config.js with representative values please? I found where to set the port in app.js (it defaulted to 80 which was used). What goes in config.service? The API did not help me.

var config = {};

config.nuve_host = '127.0.0.1';
config.service = {};
config.service.id ='54844eb4f19b0ffac799aa27';
config.service.key = '3520';

config.demo_host = 'xxx.xxx.xxx.xxx'; // Without "http", just the host.
config.https = false;

//config.plain = true;

module.exports = config;

**Comment by lodoyun** [comment]
For service.id and service.key you can use 
```
config.nuve.superserviceID
config.nuve.superserviceKey
```
form licode_config in your licode installation, the rest I think should be pretty self-explanatory.

**Comment by kanwarujjaval** [comment]
I'm getting same express 500 error!

**Comment by abertranb** [comment]
Hi I receive the same error I will provide some of my configuration:
 ~/licode I have the latest version from github (a fresh installation)
* Then I started licode 
```
~/licode/scripts/initLicode.sh
```
* Then clone the licode demos into my home directory and copy configuration, I also created self signed certificate. My config content I have to add the reference to the licode/licode_config to get value from nuve.superserviceID
```
var config = {};
var config_licode = require('../licode/licode_config');
config.nuve_host = '127.0.0.1';
config.service = {};
config.service.id =config_licode.nuve.superserviceID;
config.service.key = config_licode.nuve.superserviceKey;

config.demo_host = 'mi.public.ip'; // Without "http", just the host.
config.https = true;

//config.plain = true;

module.exports = config;
```
* Excute the application with command _sudo npm start _ and get Express error 500 and shows a log error
```
undefined
GET / 500 9ms
```
If i go to the url /admin shows form but after validate doesn't work, could be related with the comunication with erizo?

Any idea?

**Comment by abertranb** [comment]
Hello I set the 
config.nuve_host = 'http://127.0.0.1:3000/'; 

and it works!
One user can view his data but when second user access to room doesn't see the other user. 
Any idea?
