### ISSUE TITLE
Video (and probably audio) streams are not going back to life after a short network shutdown 

### ISSUE THREAD

**Issue by iwuvjhdva** [ging/licode#165]
Hi,

If I shutdown the network interface for a long time, the 'room-disconnected' event is fired as expected, though after a long timeout which is probably reasonable.

If the emulated network downtime period is relatively short, say, few seconds, then only data streams are going back to life but the video (probably audio too) streams are just freezing without any error reporting though their stream.pc.peerConnection.iceConnectionState becomes "disconnected".

The expected behaviour is maybe whether to fire 'stream-removed' and 'room-disconnected' events or to bring the streams back to life after the downtime.

Please assist.

**Comment by lodoyun** [comment]
This should be working now.
Ice fails now remove the publisher or the subscriber from the room
