### ISSUE TITLE
Licode should support trickle ICE

### ISSUE THREAD

**Issue by jnoring** [ging/licode#173]
Trickle ICE would allow candidate negotiation to complete much more quickly; this is particularly important for clients with lots of network connections, or clients that end up going through a turn server.

libnice does support trickle ICE; http://lists.freedesktop.org/archives/nice/2014-April/000836.html - so it sounds like in licode, we'd have to change how it responds to a failed state, and client-side the OFFER/ANSWER flow would have to change slightly to send individual candidates back to licode as they're discovered.

Thoughts?  I'm not sure you guys have plans to work on this; if not, we're planning on adding it.  So feedback would be awesome.  Thanks!

**Comment by zevarito** [comment]
@jnoring @lodoyun:

Did you get something working in IOS?
If not, can you provide me a brief description of the tasks that need to be done?

**Comment by jnoring** [comment]
I re-wrote licode's signaling in objective-c for iOS.  Unfortunately that is code I do not own and cannot share.  Sorry.  I can say there are a number of socket-io libraries in objective-c, and it is not hard to reverse engineer licode's signaling.  Nor is it hard to get an iOS build of webrtc you can link against your app to create peer connections, capture, encode and stream media, etc.

**Comment by zevarito** [comment]
@jnoring Thanks for this information. Are you able to point me where the signaling happen in Licode so I can figure out what needs to be converted to Objective-C ?

**Comment by windsurfdrew** [comment]
@johnwarden (or anyone) Regarding the 7/22/14 comment: Is there something that needs to be done to make licode generate and use peer reflexive TCP candidates? I'm not seeing any.

I've created a test network that restricts all UDP traffic, and am finding that the only way to establish a network connection is using a TURN server. The turn server provides a TCP relay candidate and the connection is made. But in my case, as in your comment, I would prefer not to use the relay - a direct TCP connection to the server should be possible. I know this thread is a little stale, but I'm not seeing anything more recent on the topic. Any ideas?
