### ISSUE TITLE
Does erizofc support audio/video streams now ?

### ISSUE THREAD

**Issue by azfx** [ging/licode#230]
As per the blog - http://lynckia.com/licode/erizofc.html , only datastreams were supported then ( dec/2012 ). Does licode now support audio/video media streams using erizofc ? Thanks.

**Comment by lodoyun** [comment]
At this point no. We are not planning on allowing erizofc to receive/send media (video/audio). We will, however, improve externalOuput and externalInput (currently only for recording and playing files) so erizofc can serve as a way to redirect media outside of the WebRTC (ICE/STUN/SRTP) world
