### ISSUE TITLE
Deadlock remove subscriber in OneToManyProcessor

### ISSUE THREAD

**Issue by francoisTemasys** [ging/licode#231]
This happen at least on the branch ice_trickle on commit 4a7fbaddf8d0d86132ef952be650adced57b4f28.

Here is my test workflow:
-create one publisher PA
-create a second publisher PB (I don't think this one is really useful)
-create a subscriber SA for the publisher PA. But I don't send the candidates.
-SA ice connection fail
-remove subscriber SA to PA using removeSubscriber = function(from, to)
The function ```publishers[to].muxer.removeSubscriber(from);``` never end.

I have debugged that the problem comes from here:https://github.com/ging/licode/blob/trickle_ice/erizo/src/erizo/OneToManyProcessor.cpp#L94
I added one more line:
```
void OneToManyProcessor::removeSubscriber(const std::string& peerId) {
    ELOG_DEBUG("Remove subscriber");
    boost::mutex::scoped_lock lock(myMonitor_);
    if (this->subscribers.find(peerId) != subscribers.end()) {
      this->subscribers.erase(peerId);
    }
    ELOG_DEBUG("Subscriber removed");
  }
```
The line "Subscriber removed``` never appear.

**Comment by francoisTemasys** [comment]
I just tested with last commit (8ad60191c4b5f59315adea1b882c3eb93f7a638f) and same result

**Comment by jnoring** [comment]
I guess the bigger question is if you debug it in gdb, what other thread is
holding myMonitor_ ?

**Comment by francoisTemasys** [comment]
Ok so the problem is not on myMonitor_ but when releasing the webRtcConnection object.
In the destructor:
```
if (connEventListener_ != NULL){
      connEventListener_->notifyEvent(globalState_, "");
      connEventListener_ = NULL;
    }
    globalState_ = CONN_FINISHED;
```
  1. redundancy of CONN_FINISHED (but it's a minor problem)
  2. ```connEventListener_->notifyEvent(globalState_, "");``` is the line giving problems. Commenting out solved the deadlock. That would require more inspection.

**Comment by lodoyun** [comment]
I'm having trouble reproducing this...
- What browser are you using?
- You don't send the candidates from the client, but do you add the candidates received from erizo?
- Does closing the browser of SA cause any issue?

**Comment by francoisTemasys** [comment]
I'm using Chrome 39.0.2171.99. 

Sorry I wasn't clear, I don't send the erizo candidates for the subscriber but I accept the candidates from Chrome. Then on the callback 'fail' I do ```removeSubscriber(``` that will do:
```
that.removeSubscriber = function(from, to)
  {

    if (subscribers[to][from])
    {
      logger.info('Removing subscriber ', from, 'to muxer ', to);
      publishers[to].muxer.removeSubscriber(from);
      logger.info('Closing subscriber ',from);
      subscribers[to][from].close();
      logger.info('Deleting subscriber ',from);
      delete subscribers[to][from];
    }
  };
```
And I don't understand your last question, "closing the browser of SA"?

**Comment by francoisTemasys** [comment]
I'll close this issue has it's most probably related to #240
