### ISSUE TITLE
RtpSource & RtpSink

### ISSUE THREAD

**Issue by vipulrastogi** [ging/licode#237]
Can I use above files to directly send/receive RTP/RTCP data ? if so, can somebody share any example on this.
thanks,

**Comment by lodoyun** [comment]
I'm afraid at this point they are largely unsupported, although we plan to go back to them at some point. 
In the [erizo_tree](https://github.com/ging/licode/tree/erizo_tree) branch it is used to send and receive RTP in a very hard_coded way.
