### ISSUE TITLE
Google Chrome 40.0.2214.91 can't create peer connection to Licode

### ISSUE THREAD

**Issue by ivopavlik** [ging/licode#238]
Hello,

after upgrading to Google Chrome to 40.0.2214.91 I can't create peer connection to Licode. With previous version (fortunately remained on one my host) I can connect and see streams.
I tried clear installation on clear host. Console output is below.

IP

eyJ0b2tlbklkIjoiNTRjNjJhNmIxMTU3YjNhMGI2YmY5MTNkIiwiaG9zdCI6IjE5Mi4xNjguMC40MDo4MDgwIiwic2VjdXJlIjpmYWxzZSwic2lnbmF0dXJlIjoiTmpSak5qSTNOalpqTTJVME16RTJOV0UxT0RZMU9UWmhaREF5TURRMk5HUTFPV1JtTWpZMU1nPT0ifQ==
erizo.js:156 DEBUG:  Requested access to local media
erizo.js:156 DEBUG:  Object {video: Object, audio: true, fake: undefined, screen: "", extensionId: undefined}
erizo.js:156 INFO:  User has granted access to local media.
erizo.js:156 DEBUG:  Event: access-accepted
erizo.js:140 Object {tokenId: "54c62a6b1157b3a0b6bf913d", host: "192.168.0.40:8080", secure: false, signature: "NjRjNjI3NjZjM2U0MzE2NWE1ODY1OTZhZDAyMDQ2NGQ1OWRmMjY1Mg=="}
erizo.js:156 DEBUG:  Creating URL from stream [object MediaStream]
erizo.js:166 The 'overflowchanged' event is deprecated and may be removed. Please do not use it.
erizo.js:156 INFO:  Connected to room 54c61f4b1157b3a0b6bf9134
erizo.js:156 DEBUG:  Event: room-connected
erizo.js:156 DEBUG:  Stable
erizo.js:156 DEBUG:  Stable
erizo.js:156 INFO:  Subscribing to: 794612491270527200
erizo.js:156 DEBUG:  Changed v=0
o=- 579759670911975074 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE audio video
a=msid-semantic: WMS wKTPXEc7uhoMaMVRcifObv1yL4maSyiFMBpf
m=audio 9 RTP/SAVPF 111 103 104 9 0 8 106 105 13 126
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:lRN05ftiCmf5uvZF
a=ice-pwd:VidmphYrtm0oUMuWykdLS5Bm
a=ice-options:google-ice
a=fingerprint:sha-256 FE:44:A5:18:67:7E:D1:09:72:50:51:4A:35:A5:39:8A:05:50:80:A9:D4:70:95:A7:98:9F:55:6C:31:68:36:4B
a=setup:actpass
a=mid:audio
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=sendrecv
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=fmtp:111 minptime=10
a=rtpmap:103 ISAC/16000
a=rtpmap:104 ISAC/32000
a=rtpmap:9 G722/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:106 CN/32000
a=rtpmap:105 CN/16000
a=rtpmap:13 CN/8000
a=rtpmap:126 telephone-event/8000
a=maxptime:60
a=ssrc:4098435929 cname:Dy98hIb0Rs3qaslz
a=ssrc:4098435929 msid:wKTPXEc7uhoMaMVRcifObv1yL4maSyiFMBpf e67b202f-59a8-41a7-b01b-8c2c09baa075
a=ssrc:4098435929 mslabel:wKTPXEc7uhoMaMVRcifObv1yL4maSyiFMBpf
a=ssrc:4098435929 label:e67b202f-59a8-41a7-b01b-8c2c09baa075
m=video 9 RTP/SAVPF 100 116 117 96
b=AS:300
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:lRN05ftiCmf5uvZF
a=ice-pwd:VidmphYrtm0oUMuWykdLS5Bm
a=ice-options:google-ice
a=fingerprint:sha-256 FE:44:A5:18:67:7E:D1:09:72:50:51:4A:35:A5:39:8A:05:50:80:A9:D4:70:95:A7:98:9F:55:6C:31:68:36:4B
a=setup:actpass
a=mid:video
a=extmap:2 urn:ietf:params:rtp-hdrext:toffset
a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=sendrecv
a=rtcp-mux
a=rtpmap:120 VP8/90000
a=rtcp-fb:120 ccm fir
a=rtcp-fb:120 nack
a=rtcp-fb:120 nack pli
a=rtcp-fb:120 goog-remb
a=rtpmap:116 red/90000
a=rtpmap:117 ulpfec/90000
a=rtpmap:96 rtx/90000
a=fmtp:96 apt=120
a=ssrc-group:FID 980495180 1306190662
a=ssrc:980495180 cname:Dy98hIb0Rs3qaslz
a=ssrc:980495180 msid:wKTPXEc7uhoMaMVRcifObv1yL4maSyiFMBpf 08d65009-0205-468c-ad81-9bd777bd8251
a=ssrc:980495180 mslabel:wKTPXEc7uhoMaMVRcifObv1yL4maSyiFMBpf
a=ssrc:980495180 label:08d65009-0205-468c-ad81-9bd777bd8251
a=ssrc:1306190662 cname:Dy98hIb0Rs3qaslz
a=ssrc:1306190662 msid:wKTPXEc7uhoMaMVRcifObv1yL4maSyiFMBpf 08d65009-0205-468c-ad81-9bd777bd8251
a=ssrc:1306190662 mslabel:wKTPXEc7uhoMaMVRcifObv1yL4maSyiFMBpf
a=ssrc:1306190662 label:08d65009-0205-468c-ad81-9bd777bd8251

**Comment by lodoyun** [comment]
Should be fixed in 1af80f5425f153bcafcbd59b360e21dedd17a3a1
We still had part of the quick fix for firefox interoperability and it didn't work with chrome.
Thanks!
