### ISSUE TITLE
erizoAPI eventCallback_ not released?

### ISSUE THREAD

**Issue by francoisTemasys** [ging/licode#240]
I'm not really familiar with v8 so most of it are assumptions.

Could the eventCallback_ and the statsCallback_ of the webrtcConnection.cc creates some unexpected behavior if throwing new event when object has not been released but closed.

Why not doing the following in the function close:
```
Handle<Value> WebRtcConnection::close(const Arguments& args) {
  HandleScope scope;

  WebRtcConnection* obj = ObjectWrap::Unwrap<WebRtcConnection>(args.This());
//ADD THIS
  obj->hasCallback_ = false;
  obj->hasEventCallback_ = false;//Need to be created
/////
  uv_close((uv_handle_t*)&obj->async_, NULL);
  uv_close((uv_handle_t*)&obj->asyncStats_, NULL);


  if(!uv_is_closing((uv_handle_t*)&obj->async_)) {
    uv_close((uv_handle_t*)&obj->async_, NULL);
  }
  if(!uv_is_closing((uv_handle_t*)&obj->asyncStats_)) {
 	uv_close((uv_handle_t*)&obj->asyncStats_, NULL);
  }

  return scope.Close(Null());
}
```

From http://izs.me/v8-docs/classv8_1_1Persistent.html

**Comment by jnoring** [comment]
I believe this change has already been made in the trickle_ice branch

**Comment by jnoring** [comment]
Yep, see https://github.com/ging/licode/commit/60988c92c67127b50e16925f001afe2e65729266

**Comment by IVBakker** [comment]
Yes:
-hasCallback is for the StatsCallback, but there is no bool for the EventCallback. What if we call init without callback and we decide to work only with getState.
-Why isn't hasCallback turned off for avoiding possible unexpected behavior?

It actually doesn't really solve the problem I was facing on the other issue. But it's still something.

**Comment by lodoyun** [comment]
I've added a check so the underlying erizo::webrtcconnection object has to be there when calling the callback
