### ISSUE TITLE
Google Chrome Version 40.0.2214.93 m - Compatibility issue

### ISSUE THREAD

**Issue by miroof** [ging/licode#243]
Hello,

After updating to Google Chrome Version 40.0.2214.93 m it was no more possible to create peer connections. I updated erizo client script with your last fix but now I have another issue : the streams are all blanks (black screen for video and no sound).

It worked perfectly with Google Chrome V39. And it's no more usable on V40.

Am I the only one to have this issue ?

Regards,
Jeremy

**Comment by francoisTemasys** [comment]
#238 ?

**Comment by miroof** [comment]
Hi,

This fix resolves the peer connection issue but now I have a black screen instead of the remote video. Whereas this black screen issue never occured with the previous versions of Google Chrome.

**Comment by miroof** [comment]
Resolved after a new clean install.

Thx.
