### ISSUE TITLE
How To Uninstall?

### ISSUE THREAD

**Issue by andresrivas1506** [ging/licode#244]
Hi, I followed the installation steps in Centos 6.5 but for some reason, SH Scripts (`./licode/scripts/installCentOsDeps.sh`,  `./licode/scripts/installErizo.sh` and `./licode/scripts/installNuve.sh`) failed. Now I like to clean my system. is there any way?

**Comment by francoisTemasys** [comment]
Nothing has been installed on your system directories. The dependencies libraries are install in licode/build and are used locally. To start from a fresh install just delete the git project and re-do.

You might probably need to stop/restart mongodb, but I'm not sure of that.

**Comment by lodoyun** [comment]
These are the packages installed via yum:
make gcc openssl-devel cmake pkgconfig nodejs boost-devel boost-regex boost-thread boost-system log4cxx-devel rabbitmq-server mongodb mongodb-server curl boost-test tar xz libffi-devel npm yasm java-1.7.0-openjdk

You can remove them if you don't use them. Also as @francoisTemasys said, the compiled libraries are installed in the licode directory tree so just remove to clean everything.

**Comment by andresrivas1506** [comment]
Thanks!
