### ISSUE TITLE
erizoAgent should be merged with erizoController

### ISSUE THREAD

**Issue by IVBakker** [ging/licode#247]
I don't understand why erizoAgent has been divided from erizoController. The points that I don't understand are the following.
-there is a clear interdependancy between erizoAgent and erizoController. One can't work without the other
-putting erizoAgent aside is bringing additional "dangerous" dependancy (connectivity issue with amqper)
-erizoAgent isn't the one following that erizoJS is responding
-it's not going to bring deadlock or crash issue. erizoAgent is just "launching" processes

**Comment by lodoyun** [comment]
It is part of the new layer of distribution we added to the architecture a while ago, the role of each component is [briefly explained here](http://lynckia.com/licode/async.html)
As you pointed out, erizoAgent starts a number of erizoJSs on demand [following what is specified in licode_config.js](https://github.com/ging/licode/blob/master/scripts/licode_default.js#L82)

Basically, you start an erizoAgent in any server to want to use for erizoJS hosting. Those erizoJS can be part of the same "logical" erizoController. You can, for instance, have rooms in one erizoController that are distributed across several servers. If you don't divide erizoAgent from erizoController you cannot do that.
Of course, in the one-server scenario it does not look very useful.

**Comment by IVBakker** [comment]
I understand.
I was thinking that it would more natural that erizoJS+Agent are part of the same "logical" than erizoController because there is already a scalling authority made with Nuve.
But it's a matter of point of view I guess
