### ISSUE TITLE
Firefox 35.0.1 Connection drops after some minutes "Ice failed"

### ISSUE THREAD

**Issue by peili** [ging/licode#251]
Firefox 35.0.1 Connection drops after some minutes "Ice failed"

**Comment by IVBakker** [comment]
On branch? What does the erizoJS logs say?

**Comment by peili** [comment]
master branch
2015-02-05 17:09:15.577  - INFO: ErizoController - Socket disconnect  j7dyV3zjFDaO8vlSU0sz
2015-02-05 17:09:15.577  - INFO: RoomController - Removing subscriptions of  j7dyV3zjFDaO8vlSU0sz
2015-02-05 17:09:15.577  - INFO: RoomController - Removing subscriber  j7dyV3zjFDaO8vlSU0sz to muxer  119451550533995040

Seems to be a client problem on Firefox that the WebSocket disconnects. about:webrtc in Firefox tells that the PeerConnection is sill open to Erizo even when there is no data stream anymore:
RTP statistics
outbound_rtp_audio_-1
Local: 17:14:16 GMT+0100 (CET) outboundrtp SSRC: 2838467253 Sent: 24148 packets (1434.6 Kb)

**Comment by IVBakker** [comment]
Already more information. Is it the last commit from master (with ice trickle)?

Now we need a little bit more:
1) Change the file log4cxx.properties in erizoAgent to have NiceConnection=DEBUG and maybe WebRtcConnection=DEBUG
2) The logs we need to see is the one from erizoJS not erizoController (that's the one you are posting). It should be in erizoAgent, look for the last .log files. Then search for something wrong.
