### ISSUE TITLE
Exceptions when disconnecting from p2p room

### ISSUE THREAD

**Issue by vibhorsd** [ging/licode#252]
Getting following exceptions when ending a call where `{p2p: true}` is passed in `createRoom` API.

    function endCall() {
        if (localStream) {
            console.log('closing local stream');
            try {
                localStream.close();
            } catch (err) {
                console.log('close local stream error = ', err);
            }
            localStream = null;
        }

        if (room) {
            for (var idx in subscribedStreams) {
                console.log('unsubscribing from remote stream');
                try {
                    room.unsubscribe(subscribedStreams[idx]);
                } catch (err) {
                    console.log('room.unsubscribe error: ', err);
                }
            }
            console.log('disconnecting from room');
            try {
                room.disconnect();
            } catch (err) {
                console.log('room.disconnect error: ', err);
            }
        }
    }

"closing local stream" client.js:229
"close local stream error = " TypeError: b.pc.close is not a function
Stack trace:
Erizo.Room/a.unpublish@http://myserver.com/javascripts/lib/erizo.js:151:343
Erizo.Stream/a.close@http://myserver.com/javascripts/lib/erizo.js:134:261
endCall@http://myserver.com/javascripts/client.js:231:13
@http://myserver.com/javascripts/main.js:42:9
m.event.dispatch@http://myserver.com/javascripts/lib/jquery.js:3:8384
m.event.add/r.handle@http://myserver.com/javascripts/lib/jquery.js:3:5122
 client.js:233
"unsubscribing from remote stream" client.js:240
"disconnecting from room" client.js:247
"DEBUG: " "Event: room-disconnected" erizo.js:156
"DEBUG: " "Event: stream-removed" erizo.js:156
"DEBUG: " "Event: stream-removed" erizo.js:156
"room.disconnect error: " TypeError: c.pc.close is not a function
Stack trace:
Erizo.Room/<@http://myserver.com/javascripts/lib/erizo.js:138:500
Erizo.EventDispatcher/a.dispatchEvent@http://myserver.com/javascripts/lib/erizo.js:93:548
Erizo.Room/a.disconnect@http://myserver.com/javascripts/lib/erizo.js:146:484
endCall@http://myserver.com/javascripts/client.js:249:13
@http://myserver.com/javascripts/main.js:42:9
m.event.dispatch@http://myserver.com/javascripts/lib/jquery.js:3:8384
m.event.add/r.handle@http://myserver.com/javascripts/lib/jquery.js:3:5122
 client.js:251

**Comment by nachoaguadoc** [comment]
Hi,

It has been fixed in 9777260a09519b0c94481776ac2cb9e11e2869aa, thanks!

**Comment by nachoaguadoc** [comment]
Sorry, the correct commit is this one ad9d53587cf9e1d187e2bed6e066f4b89ebb62cd
