### ISSUE TITLE
No video is broadcasted when using "mandatory" for video in getUserMedia constraint parameter

### ISSUE THREAD

**Issue by ivopavlik** [ging/licode#254]
When I use WebRTC style media constraints for getUserMedia method e.g.:
`{audio: true, video: {mandatory: {minWidth: 1280, minHeight: 720, maxWidth: 1280, maxHeight: 720}}}`

I don't get video track of remote stream on remote side and a black screen is presented in video element.

When I use the same "mandatory" constraints with the screen and no audio, like:
`{audio: false, screen: true, video: {mandatory: {minWidth: 1280, minHeight: 720, maxWidth: 1280, maxHeight: 720}}}`

2nd peer is with incomplete session description:
`{sdp: "v=0\r\no=- 3880956701818766161 2 IN IP4 127.0.0.1\r\ns=-\r\nt=0 0\r\na=msid-semantic: WMS\r\n", type: "offer"}`

, no candidates are reported (Candidates to be added:  0 []) and no connection is established.

Before release 1.1.0 it was possible to use "WebRTC-style" constraint definition. It is needed at least for framerate definition.

Many thanks.

**Comment by blackjid** [comment]
any luck with this?

**Comment by zevarito** [comment]
@ivopavlik Any update?

**Comment by lodoyun** [comment]
You cannot pass constraints using the Webrtc syntax in Licode when creating a local stream, 
see http://lynckia.com/licode/client-api.html for the supported options.
It can be argued that erizo client should support the same syntax/functionality and I tend to agree. Is that what you are requesting?
