### ISSUE TITLE
Recording Issue

### ISSUE THREAD

**Issue by pawanvivekananda** [ging/licode#258]
The recorded file can't play video when played back

**Comment by jnoring** [comment]
Going to need a bit more information than that.

**Comment by pawanvivekananda** [comment]
I am trying to recording vp8 with pcmu
After recording when i try to playback the recorded file, it fails to play video but audio plays seamlessly  In the master branch

**Comment by pawanvivekananda** [comment]
I tried reverting back the revision to check where it has broken ...  i found its broken in 

78b7b6ab97cbd05e04df1253d73a747ce94d959e

**Comment by lodoyun** [comment]
I introduced a fix for this yesterday in aa7e88c9dadd0e0437edf2faa7a533c19b30f321

Please try it and reopen the issue if you find any more problems. Keep in mind you won't be able to seek within the file unless you re-encode the file
