### ISSUE TITLE
chrome 41 issues

### ISSUE THREAD

**Issue by blackjid** [ging/licode#263]
Hi, any idea why the latest commit is not working in chrome 41 stable??

**Comment by lodoyun** [comment]
It's working fine for me in Mac OS and Windows 7 with Chrome 41.0.2272.76 64 bits
Any more details on what is happening?

**Comment by blackjid** [comment]
I think it is working....
The problem had to do with this issue https://github.com/ging/licode/issues/254

I was passing a videoConstrain with mandatory and optionals constrains.... and I wasn't able to get any video on the remote peer....

I tried using  `videoConstrain: true` and it works fine....

any idea what have change in this regard??
thnks

**Comment by lodoyun** [comment]
please continue the discussion in issue #254 as it looks like it is the same issue
