### ISSUE TITLE
错误：ISO C++ 不允许声明无类型的‘SRTP_PROTECTION_PROFILE’

### ISSUE THREAD

**Issue by 99154562** [ging/licode#265]
Scanning dependencies of target erizo
[  3%] Building CXX object erizo/CMakeFiles/erizo.dir/media/ExternalInput.cpp.o
[  6%] Building CXX object erizo/CMakeFiles/erizo.dir/media/mixers/VideoMixer.cpp.o
[  9%] Building CXX object erizo/CMakeFiles/erizo.dir/media/mixers/VideoUtils.cpp.o
[ 12%] Building CXX object erizo/CMakeFiles/erizo.dir/media/OneToManyTranscoder.cpp.o
[ 15%] Building CXX object erizo/CMakeFiles/erizo.dir/OneToManyProcessor.cpp.o
[ 18%] Building CXX object erizo/CMakeFiles/erizo.dir/StringUtil.cpp.o
[ 21%] Building CXX object erizo/CMakeFiles/erizo.dir/WebRtcConnection.cpp.o
In file included from /sh/licode/licode-1.1.0/erizo/src/erizo/DtlsTransport.h:8,
                 from /sh/licode/licode-1.1.0/erizo/src/erizo/WebRtcConnection.cpp:8:
/sh/licode/licode-1.1.0/erizo/src/erizo/dtls/DtlsSocket.h:110: 错误：ISO C++ 不允许声明无类型的‘SRTP_PROTECTION_PROFILE’
/sh/licode/licode-1.1.0/erizo/src/erizo/dtls/DtlsSocket.h:110: 错误：expected ‘;’ before ‘*’ token
make[2]: *** [erizo/CMakeFiles/erizo.dir/WebRtcConnection.cpp.o] 错误 1
make[1]: *** [erizo/CMakeFiles/erizo.dir/all] 错误 2
make: *** [all] 错误 2

**Comment by lodoyun** [comment]
In what OS are you trying to compile?

**Comment by 99154562** [comment]
redhat linux   , but i recomplie openssl ,resolved.  
thank you
