### ISSUE TITLE
Does something changed with how MKV files are recorded?

### ISSUE THREAD

**Issue by zevarito** [ging/licode#266]
We used to have a script that watches for mkv file additions to a folder and then trigger a transcoding process. This used to work fine until we had to update Licode, now *seems* like Licode open/closes the file to write small chunks of data causing the event -added- to be triggered before the recording is complete.

Could you explain to me how it works?

Thanks!

**Comment by DmitriyKarpov** [comment]
Hi! Are you transcoding files during recording process or after recording stops? In my project I launch transcoding after recording stops, but I want to transcode files on the fly during recording process. But I've not found any way to do it, maybe you can give me some advices to search?

**Comment by zevarito** [comment]
@dennismartensson we transcode the file after recording stops.

I've noticed that before Licode latests updates we used to watch for MKV file addition in a folder and then transcode.

Now seems that file is created as soon as live recording starts, which might be helpful for you if you want to transcode at the same time you are broadcasting, I think you should check ffmpeg (if you are using it) to see how to transcode a live stream and if it is possible.

If you do it, please share you research here ;)

**Comment by lodoyun** [comment]
Since when did you experience this change? The new master branch (trickle_ice)?
We did make some changes to recording but, specifically, the way we write to files should not have changed at all.
Licode should create the file as soon as the recording starts, write on it and close it after the recording stops or the stream is no longer available.
I don't know if I would recommend transcoding on the fly, the results will probably be better if you wait for the file to end.

**Comment by zevarito** [comment]
Actually the way it works is how you described so no issues there.

Thanks.

On Tue, Mar 17, 2015 at 11:37 AM, Pedro Rodriguez <notifications@github.com>
wrote:

> Since when did you experience this change? The new master branch
> (trickle_ice)?
> We did make some changes to recording but, specifically, the way we write
> to files should not have changed at all.
> Licode should create the file as soon as the recording starts, write on it
> and close it after the recording stops or the stream is no longer available.
> I don't know if I would recommend transcoding on the fly, the results will
> probably be better if you wait for the file to end.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ging/licode/issues/266#issuecomment-82387334>.
>



-- 
Alvaro
