### ISSUE TITLE
Licode is not working in virtual machine of Openstack

### ISSUE THREAD

**Issue by mosfet1kg** [ging/licode#268]
I know Licode has accepted new technique regarding ICE.

Why I write this mention is that Licode is not working on my virtual machine.

Last verion of Licode just uses machine IP written in licode_config.js as config.erizoController.publicIP

However, Current version don't use it in the same manner.

I can find the private Ip like <code>a=candidate:1 1 udp 2013266431 192.168.6.10 53568 typ host generation 0 </code> from the sdp.

So, Licode in VM only supports conferencing for the devices in same NAT environment.

**Comment by lodoyun** [comment]
Hi, you must also set up `config.erizoAgent.publicIP`
That's the IP that will be changed in the candidates.

**Comment by mosfet1kg** [comment]
I already did. <code>config.erizoAgent.publicIP</code> also has the public IP allocated to its VM.

**Comment by lodoyun** [comment]
Update and try again, just fixed a bug regarding this 2dd39d936f21344bf1016c7dfc2e69cdc2e2d883
Sorry I didn't mention it before

**Comment by mosfet1kg** [comment]
I'm impressed with the commit...Thanks
