### ISSUE TITLE
ICE Connection Failed on Chrome for Windows but not on Chrome for Mac

### ISSUE THREAD

**Issue by lainor** [ging/licode#272]
I'm getting:

INFO:  ICE Connection Failed
DEBUG:  Event: stream-failed
End of candidates

On Chrome 41.0.2272.89 m for Windows.
The same setup works like a charm on Chrome 41.0.2272.89 for Mac OS X Yosemite.

Any clue?

**Comment by lainor** [comment]
With Windows Firewall off it seems to work.
The issue appeared after I updated to the latest version of Erizo that supports Trickle.
Before, it was working also with Windows Firewall on.

Could it be a Trickle related problem?

**Comment by lodoyun** [comment]
Hi, 
tag v1.1.0 is pre trickle_ice so it makes sense that it behaves the same than before updating.
What version of Windows are you running? I'll try to reproduce it.

**Comment by lainor** [comment]
Windows 8.1 x64

**Comment by zevarito** [comment]
Dunno if it will help you since I was running with the same issue in Linux, but I had to update external-ip config setting in our turnserver.conf to the same as rely-ip, strange, I know, but before that it wasn't working.

Also if you are using SSL check that the process that runs your turnsever has access to key/cert files. Check logs.

Good luck!

**Comment by lodoyun** [comment]
I've done a couple of quick tests (with and without TURN) behind a NAT and everything seems to be working correctly.
Have you checked the configuration is the same in both scenarios? Is there any more information you can give us? NATs? TURN/STUN?

**Comment by lainor** [comment]
The problem appears when using Windows' firewall behind NAT.
The configuration is the same in both cases (pre-trickle and trickle)
We are using google's stun and self hosted turn server.
I'm using the same connection for both Mac and Windows tests.

**Comment by Mido22** [comment]
same issue here, chrome version 45, on Windows 7 64 bit, but in Firefox, it runs without any issue, but what I do not understand is, why is a TURN server even required in my case because licode server was run on a local VM

**Comment by lodoyun** [comment]
Old Issue, I'm closing this. Feel free to reopen it if the problem persists.
