### ISSUE TITLE
Erizo Client doesn't support optional video params for getUserMedia

### ISSUE THREAD

**Issue by zevarito** [ging/licode#273]
According to this [0], is not possible to setup optional parameters for video constraints of getUserMedia, which makes impossible to select rear/front cameras with Chrome, there is another way to achieve this or a patch is needed ?

Also, would be interesting to add pass-through parameters directly into getUserMedia ?

I'll play with my own fork to find a way to achieve this, please let me know any suggestions that you might have.

Thanks!

[0] https://github.com/ging/licode/blob/ad9d53587cf9e1d187e2bed6e066f4b89ebb62cd/erizo_controller/erizoClient/src/Stream.js#L83

**Comment by mrbatista** [comment]
Chrome not support select rear/front camera on-the-fly. See [this](http://webrtc.github.io/samples/src/content/getusermedia/source/) for get available audio and video sources and then set video/audio constraints in getUserMedia.

**Comment by zevarito** [comment]
@mrbatista Right, I am still a step behind, just looking for pass optional and mandatory arguments to getUserMedia through ErizoStream.

This feature was removed in this commit 40662786364ef78dd9e76ce5bb0ac44a1c6a7539. See LOC.
Currently working on a patch for Erizo that also is compatible with videoSize.

LOC: https://github.com/ging/licode/commit/40662786364ef78dd9e76ce5bb0ac44a1c6a7539#diff-ac12d5f3fb930e488d8b6c38cf708e3dL85

**Comment by zevarito** [comment]
Here is a patch just in case. https://github.com/rhinobird/licode/commit/8805c8c8654a378c92389d0bc6b828266446641b
