### ISSUE TITLE
How to scale Licode?

### ISSUE THREAD

**Issue by zevarito** [ging/licode#281]
Are you guys using more than one instance of Licode?
How are you doing load balance?

**Comment by ivopavlik** [comment]
Licode is quite pretty scalable, if you have more rooms and more broadcasters. You can find some details in this blog: http://lynckia.com/licode/async.html
Install Licode to more servers. Based on your topology, you can install and run separately only some components (and their dependencies) on each server (Nuve, ErizoController, ErizoAgent). You can decide which component will be running on which server in initLicode.sh.
Important thing is to define on which one will be installed RabbitMQ server (Nuve should I think). All other nodes (servers) should connect to that server (using config.rabbit.host parameter in licode_config.js).
You can scale number of rooms for each ErizoController instance by config.erizoController.warning_n_rooms and config.erizoController.limit_n_rooms in licode_config.js.
Likewise, you can scale number of broadcasters' processes for each ErizoAgent by parameters config.erizoAgent.maxProcesses and config.erizoAgent.prerunProcesses.

As I mentioned in beginning, that it is pretty scalable when you have more more rooms and/or more broadcasters. In my case, we have one big room with many receivers and only one broadcaster. Does have anybody idea how to scale resources and network traffic to more servers to provide sufficient bandwidth to many receivers connections? EizoAgent creates ErizoJS processes for each broadcaster (by documentation), which can be scaled to more servers. But how to scale more receivers or multiplex broadcaster's stream to more servers?

Any recommendation is appreciated :)

**Comment by zevarito** [comment]
Thank you very much for your answer, it was really helpful.

You said you have one broadcaster many receivers, I wonder what limit of
receivers did you hit?

Thanks again.

On Wednesday, April 8, 2015, Ivan <notifications@github.com> wrote:

> Licode is quite pretty scalable, if you have more rooms and more
> broadcasters. You can find some details in this blog:
> http://lynckia.com/licode/async.html
> Install Licode to more servers. Based on your topology, you can install
> and run separately only some components (and their dependencies) on each
> server (Nuve, ErizoController, ErizoAgent). You can decide which component
> will be running on which server in initLicode.sh.
> Important thing is to define on which one will be installed RabbitMQ
> server (Nuve should I think). All other nodes (servers) should connect to
> that server (using config.rabbit.host parameter in licode_config.js).
> You can scale number of rooms for each ErizoController instance by
> config.erizoController.warning_n_rooms and
> config.erizoController.limit_n_rooms in licode_config.js.
> Likewise, you can scale number of broadcasters' processes for each
> ErizoAgent by parameters config.erizoAgent.maxProcesses and
> config.erizoAgent.prerunProcesses.
>
> As I mentioned in beginning, that it is pretty scalable when you have more
> more rooms and/or more broadcasters. In my case, we have one big room with
> many receivers and only one broadcaster. Does have anybody idea how to
> scale resources and network traffic to more servers to provide sufficient
> bandwidth to many receivers connections? EizoAgent creates ErizoJS
> processes for each broadcaster (by documentation), which can be scaled to
> more servers. But how to scale more receivers or multiplex broadcaster's
> stream to more servers?
>
> Any recommendation is appreciated :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ging/licode/issues/281#issuecomment-90878173>.
>


-- 
Sent from Gmail Mobile

**Comment by zevarito** [comment]
@ivopavlik while it is pretty clear how to scale Licode, it is not so clear for me when it should scale to improve performance, since I've confirmed my Licode server runs ok but streaming performance being degraded a lot.

I've tested this scenario:

* EC2 m3.large
* 15 people consuming 3 broadcasts each

Server CPU, Memory, Disk, Bandwidth was not saturated but video quality was pretty bad most of the time, and occasionally really great.

**Comment by lodoyun** [comment]
Ok, that is a different problem.
As it is now(and provided the server is not saturated), each publisher of Licode will try to adapt its video stream to the worst of its subscribers.
That means if you have 10 subscribers with great connections the video will be great (and by great I mean with a Bitrate close to what you configured). However, if one of the subscribers has a bad connection (low BW, lossy, etc.) the publisher will adapt its stream and all 10 subscribers will see a bad quality (low BW) video.
This is good for a many-to-many videoconference where quality is usually not as important as being able to participate. It is not so great for more streaming-oriented applications. We are working on a solution where you will set a lower quality limit and subscribers that are not able to cope with it will be notified and will stop being taken into account in the publisher video quality.

**Comment by zevarito** [comment]
@lodoyun thanks, that clarifies a lot. Do you have estimations on where the solution might see the light? There is branch where I can contribute too? Any help you need, please let me know.

Thanks!

**Comment by zevarito** [comment]
@lodoyun I found this thread... https://groups.google.com/forum/#!searchin/lynckia/sdp$20chrome/lynckia/vZdirnQ3kdQ/XOlLUtrqsm8J

Do you think is worth to try? Also, where exactly should apply the patch?

I've tried to reply thread but google is not giving me the option to do it.

thanks.

**Comment by kaustavdm** [comment]
If you want to scale licode in production, it is better to load balance using nginx.

So, you can install rabbitmq on separate servers and the rest of the components on multiple servers and distribute load through nginx.

**Comment by joshuairl** [comment]
@kaustavdm Any examples of this done anywhere?  Know anyone who has documented a tutorial of this process?

**Comment by kaustavdm** [comment]
@joshuairl Not documented yet, but it goes like this:

- Box1: RabbitMQ instance
- Box2: MongoDB instance
- Box3: Licode instance (Erizo + Nuve)
- Box4: Licode instance (Erizo + Nuve)
- Box5: Licode instance (Erizo + Nuve)
- Box6: Load balancer (Nginx). Reverse proxy to Box3, Box4 and Box5. Use ip-hash to ensure compatibility

Configs in Box3, Box4 and Box5 point to Box1 and Box2 for the DB instances.

**Comment by cracker0dks** [comment]
Hey, I'm also intrested in scaling licode. Why do you need RabbitMQ and whats his task? How does Nginx know on which server wich licode room is running ?

**Comment by joshuairl** [comment]
You define the upstream ips of the boxes running licode in the Nginx config.

**Comment by joshuairl** [comment]
I assume rabbitmq handles the propagation of events and room info?

**Comment by kaustavdm** [comment]
@joshuairl RabbitMQ handles the propagation of media elements. It creates the media pipeline. MongoDB handles the room info.

**Comment by joshuairl** [comment]
Awesome! Thanks.  You rock.

**Comment by joshuairl** [comment]
If we want to do this setup, we probably don’t want to use the ./installUbuntuDeps.sh file right?
Last time I ran this I think it installed rabbitmq and everything on the box? No?

**Comment by joshuairl** [comment]
Nevermind, just trying it after removing mongoldb and rabbitmq-server from installUbuntuDeps.  We shall learn by doing :)
Thanks

**Comment by kaustavdm** [comment]
I ended up customizing the install script. But, it was only for a short trial run, so I did not get serious enough with it. Glad that you found it helpful.

**Comment by lodoyun** [comment]
I see some issues with that deployment.
Nuve is designed to do the load balancing for the Erizos, you don't actually need one per Erizo, just configuring the same rabbitmq host for all of them will work together. Nuve will assign rooms to each of the Erizos and will redirect clients there.

To be honest @kaustavdm, I'm not sure I understand how your deployment is working. As it is now, the correspondence between Erizos and Rooms is not stored in Mongo, it's in memory, so, if ngynx is redirecting requests to different Nuves, there is no guarantee users in the same room will end up in the same Erizo.

Besides, since [this update](http://lynckia.com/licode/async.html), you don't event have to have a full erizoController to distribute the Erizo load, although it is a perfectly valid approach.

**Comment by cracker0dks** [comment]
Is there a best practice you can tell for view rooms (3-4) with max. 60 Brodcast Clients in it. At the moment it is running all on the same server and it worked pretty well for 1 Room. Can I build it up like:

* Server 1: RabbitMQ, MongoDb, Webserver, Nuve
* Server 2-N: erizoControllers (for Rooms) with ErizoClients

Configurated by the Cloud Handler -> http://lynckia.com/licode/ch-policies.html

Do you think this will work? Any better plans?

Thanks :)

**Comment by joshuairl** [comment]
@lodoyun So basically the idea is... install one `main licode box` with `rabbitmq`, `mongodb`, etc. and run `licode/scripts/initLicode.sh` to run it all.

Then, create a new box that just runs only `./licode/erizo_controller/initErizo_agent.sh` with a `licode_config.json` file that is configured to point `rabbitmq` at your `main licode box`.

Then, all incoming requests come to the `main licode box` which distributes things to the N-amount of spawned erizo agent servers?

Am I following you correctly?

**Comment by lodoyun** [comment]
Basically yes.
You can also run several erizoControllers associated with one Nuve/Rabbimq/Mongodb install
