### ISSUE TITLE
Load assets over SSL

### ISSUE THREAD

**Issue by zevarito** [ging/licode#282]
Currently this assets are fetched causing the Browser to warn about content insecure.
I've checked those are not served under https, which is the best fix/workaround for this?

Thanks!

http://chotis2.dit.upm.es:3000/assets/loader.gif
http://chotis2.dit.upm.es:3000/assets/star.svg
http://chotis2.dit.upm.es:3000/assets/sound48.png

**Comment by zevarito** [comment]
I am now getting net::ERR_NAME_NOT_RESOLVED for those assets.

Has something changed?

**Comment by andresrivas1506** [comment]
I solved this by putting these files on my server and editing erizo.js, now these loaded locally
