### ISSUE TITLE
anybody give me the article about Licode: TURN configuration discussion of coTurn?

### ISSUE THREAD

**Issue by qdog988** [ging/licode#291]
I found an article of how to set turn server with Licode on groups.google.com,but I cant open it.

anybody can give me the article?

the URL is
https://groups.google.com/forum/#!topic/lynckia/rT8_N1lcV8M

thanks

**Comment by lodoyun** [comment]
What do you mean you cannot see it?
It is public, try a different browser?
Here are the basics:
http://lynckia.com/licode/turn.html
