### ISSUE TITLE
get{Active}Rooms ?

### ISSUE THREAD

**Issue by andresrivas1506** [ging/licode#292]
Hi, there is any way to get non-empty rooms?
The [Server API](http://lynckia.com/licode/server-api.html#rooms) shows how to get all the rooms, but I need only active (not empty)

there is a method?

```javascript
app.get('/getRooms/', function(req, res){
 
    N.API.getRooms(function(rooms) {
        res.send(rooms);
    }, function (e) {
        console.log('Error: ', e);
    });
});
```

Greetings

**Comment by lodoyun** [comment]
Not at this point. You will have to get users for each room and check those that are not empty.
