### ISSUE TITLE
PublicIP licode_config.js INFO:  ICE Connection Failed

### ISSUE THREAD

**Issue by farrukhmustafa** [ging/licode#293]
Hello Experts,
  I have amazon aws instance running 12.04 Ubuntu LTS with latest vanilla Licode code without any code changes. As amazon gives elastic IP or even if you use standard public IP, it does not work. 

I only change one entry in licode_config.js --> config.erizoController.publicIP = '52.X.X.XX'; //default value: '' public IP, . erizoController starts fine but when I enter a room such as http://host:port/room?id=...., I get below error. 

DEBUG:  Event: room-connected
videoconference.js:26 vopy a pub
erizo.js:159 INFO:  Stream published
erizo.js:159 DEBUG:  Stable!
erizo.js:151 Sending message Object {type: "offer", sdp: "v=0
↵o=- 7998226799333784791 2 IN IP4 127.0.0.1
↵s…7015 label:9ae200c0-3ae7-4e5f-b797-5fc592b1ed19
↵"}
erizo.js:113 Set remote and local description v=0
erizo.js:113 Set remote and local description v=0
o=- 0 0 IN IP4 127.0.0.1
s=LicodeMCU
t=0 0
a=group:BUNDLE audio video
a=msid-semantic: WMS 5xhVnqSWQ8
m=audio 1 RTP/SAVPF 0 126
c=IN IP4 0.0.0.0
a=rtcp:1 IN IP4 0.0.0.0
a=candidate:1 1 udp 2013266431 172.31.46.17 48431 typ host generation 0
a=ice-ufrag:DaRa
a=ice-pwd:7dFcFc5fyEdDK4vZ7SfHa/
a=fingerprint:sha-256 D2:95:41:EA:37:09:DC:08:22:8B:53:25:6B:D6:62:F4:29:C0:39:02:32:2D:F2:1F:13:31:EE:3B:B5:B0:BE:09
a=sendrecv
a=mid:audio
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=rtcp-mux
a=rtpmap:0 PCMU/8000
a=rtpmap:126 telephone-event/8000
a=maxptime:60
a=ssrc:44444 cname:o/i14u9pJrxRKAsu
a=ssrc:44444 msid:5xhVnqSWQ8 a0
a=ssrc:44444 mslabel:5xhVnqSWQ8
a=ssrc:44444 label:5xhVnqSWQ8a0
m=video 1 RTP/SAVPF 100 116 117
c=IN IP4 0.0.0.0
a=rtcp:1 IN IP4 0.0.0.0
a=candidate:1 1 udp 2013266431 172.31.46.17 48431 typ host generation 0
a=ice-ufrag:DaRa
a=ice-pwd:7dFcFc5fyEdDK4vZ7SfHa/
a=extmap:2 urn:ietf:params:rtp-hdrext:toffset
a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=fingerprint:sha-256 D2:95:41:EA:37:09:DC:08:22:8B:53:25:6B:D6:62:F4:29:C0:39:02:32:2D:F2:1F:13:31:EE:3B:B5:B0:BE:09
a=sendrecv
a=mid:video
a=rtcp-mux
a=rtpmap:100 VP8/90000
a=rtcp-fb:100 ccm fir
a=rtcp-fb:100 nack
a=rtcp-fb:100 nack pli
a=rtcp-fb:100 goog-remb
a=rtpmap:116 red/90000
a=rtpmap:117 ulpfec/90000
a=ssrc:55543 cname:o/i14u9pJrxRKAsu
a=ssrc:55543 msid:5xhVnqSWQ8 v0
a=ssrc:55543 mslabel:5xhVnqSWQ8
a=ssrc:55543 label:5xhVnqSWQ8v0
a=ssrc:55555 cname:o/i14u9pJrxRKAsu
a=ssrc:55555 msid:5xhVnqSWQ8 v0
a=ssrc:55555 mslabel:5xhVnqSWQ8
a=ssrc:55555 label:5xhVnqSWQ8v0

erizo.js:111 Local Candidates stored:  1 [Object]
erizo.js:111 Local Candidates stored:  2 [Object, Object]
erizo.js:111 Local Candidates stored:  3 [Object, Object, Object]
erizo.js:111 Local Candidates stored:  4 [Object, Object, Object, Object]
erizo.js:114 Candidates to be added:  0 []
erizo.js:114 Local candidates to send: 4
erizo.js:151 Sending message Object {type: "candidate", candidate: Object}
erizo.js:151 Sending message Object {type: "candidate", candidate: Object}
erizo.js:151 Sending message Object {type: "candidate", candidate: Object}
erizo.js:151 Sending message Object {type: "candidate", candidate: Object}
erizo.js:151 Sending message Object {type: "candidate", candidate: Object}
erizo.js:151 Sending message Object {type: "candidate", candidate: Object}
erizo.js:151 Sending message Object {type: "candidate", candidate: Object}
erizo.js:151 Sending message Object {type: "candidate", candidate: Object}
erizo.js:111 End of candidates.
erizo.js:159 INFO:  ICE Connection Failed
erizo.js:159 DEBUG:  Event: stream-failed

I have tried debugging it from many weeks but in-vain. I need your help to tell me how can I configure licode with public IP. My guess is, it is still using private IP somewhere and not using public IP completely. 
Please help.

**Comment by zevarito** [comment]
Did you setup Turn/Stun servers correctly?

http://lynckia.com/licode/turn.html

On Mon, May 4, 2015 at 4:23 AM, farrukhmustafa <notifications@github.com>
wrote:

> Hello Experts,
> I have amazon aws instance running 12.04 Ubuntu LTS with latest vanilla
> Licode code without any code changes. As amazon gives elastic IP or even if
> you use standard public IP, it does not work.
>
> I only change one entry in licode_config.js -->
> config.erizoController.publicIP = '52.X.X.XX'; //default value: '' public
> IP, . erizoController starts fine but when I enter a room such as
> http://host:port/room?id=...., I get below error.
>
> DEBUG: Event: room-connected
> videoconference.js:26 vopy a pub
> erizo.js:159 INFO: Stream published
> erizo.js:159 DEBUG: Stable!
> erizo.js:151 Sending message Object {type: "offer", sdp: "v=0
> ↵o=- 7998226799333784791 2 IN IP4 127.0.0.1
> ↵s…7015 label:9ae200c0-3ae7-4e5f-b797-5fc592b1ed19
> ↵"}
> erizo.js:113 Set remote and local description v=0
> erizo.js:113 Set remote and local description v=0
> o=- 0 0 IN IP4 127.0.0.1
> s=LicodeMCU
> t=0 0
> a=group:BUNDLE audio video
> a=msid-semantic: WMS 5xhVnqSWQ8
> m=audio 1 RTP/SAVPF 0 126
> c=IN IP4 0.0.0.0
> a=rtcp:1 IN IP4 0.0.0.0
> a=candidate:1 1 udp 2013266431 172.31.46.17 48431 typ host generation 0
> a=ice-ufrag:DaRa
> a=ice-pwd:7dFcFc5fyEdDK4vZ7SfHa/
> a=fingerprint:sha-256
> D2:95:41:EA:37:09:DC:08:22:8B:53:25:6B:D6:62:F4:29:C0:39:02:32:2D:F2:1F:13:31:EE:3B:B5:B0:BE:09
> a=sendrecv
> a=mid:audio
> a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
> a=rtcp-mux
> a=rtpmap:0 PCMU/8000
> a=rtpmap:126 telephone-event/8000
> a=maxptime:60
> a=ssrc:44444 cname:o/i14u9pJrxRKAsu
> a=ssrc:44444 msid:5xhVnqSWQ8 a0
> a=ssrc:44444 mslabel:5xhVnqSWQ8
> a=ssrc:44444 label:5xhVnqSWQ8a0
> m=video 1 RTP/SAVPF 100 116 117
> c=IN IP4 0.0.0.0
> a=rtcp:1 IN IP4 0.0.0.0
> a=candidate:1 1 udp 2013266431 172.31.46.17 48431 typ host generation 0
> a=ice-ufrag:DaRa
> a=ice-pwd:7dFcFc5fyEdDK4vZ7SfHa/
> a=extmap:2 urn:ietf:params:rtp-hdrext:toffset
> a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
> a=fingerprint:sha-256
> D2:95:41:EA:37:09:DC:08:22:8B:53:25:6B:D6:62:F4:29:C0:39:02:32:2D:F2:1F:13:31:EE:3B:B5:B0:BE:09
> a=sendrecv
> a=mid:video
> a=rtcp-mux
> a=rtpmap:100 VP8/90000
> a=rtcp-fb:100 ccm fir
> a=rtcp-fb:100 nack
> a=rtcp-fb:100 nack pli
> a=rtcp-fb:100 goog-remb
> a=rtpmap:116 red/90000
> a=rtpmap:117 ulpfec/90000
> a=ssrc:55543 cname:o/i14u9pJrxRKAsu
> a=ssrc:55543 msid:5xhVnqSWQ8 v0
> a=ssrc:55543 mslabel:5xhVnqSWQ8
> a=ssrc:55543 label:5xhVnqSWQ8v0
> a=ssrc:55555 cname:o/i14u9pJrxRKAsu
> a=ssrc:55555 msid:5xhVnqSWQ8 v0
> a=ssrc:55555 mslabel:5xhVnqSWQ8
> a=ssrc:55555 label:5xhVnqSWQ8v0
>
> erizo.js:111 Local Candidates stored: 1 [Object]
> erizo.js:111 Local Candidates stored: 2 [Object, Object]
> erizo.js:111 Local Candidates stored: 3 [Object, Object, Object]
> erizo.js:111 Local Candidates stored: 4 [Object, Object, Object, Object]
> erizo.js:114 Candidates to be added: 0 []
> erizo.js:114 Local candidates to send: 4
> erizo.js:151 Sending message Object {type: "candidate", candidate: Object}
> erizo.js:151 Sending message Object {type: "candidate", candidate: Object}
> erizo.js:151 Sending message Object {type: "candidate", candidate: Object}
> erizo.js:151 Sending message Object {type: "candidate", candidate: Object}
> erizo.js:151 Sending message Object {type: "candidate", candidate: Object}
> erizo.js:151 Sending message Object {type: "candidate", candidate: Object}
> erizo.js:151 Sending message Object {type: "candidate", candidate: Object}
> erizo.js:151 Sending message Object {type: "candidate", candidate: Object}
> erizo.js:111 End of candidates.
> erizo.js:159 INFO: ICE Connection Failed
> erizo.js:159 DEBUG: Event: stream-failed
>
> I have tried debugging it from many weeks but in-vain. I need your help to
> tell me how can I configure licode with public IP. My guess is, it is still
> using private IP somewhere and not using public IP completely.
> Please help.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ging/licode/issues/293>.
>



-- 
Alvaro

**Comment by farrukhmustafa** [comment]
I will set it up today but two simple questions.. 

STUN part
Do I need to setup up both Turn and Stun servers? I see in licode_config.js, that google stun server is already mentioned. Do I need to do anything else? I am new to it so i apologize.

/*********************************************************
 ERIZO CONTROLLER CONFIGURATION
**********************************************************/
config.erizoController = {};
//Use undefined to run clients without Stun 
config.erizoController.stunServerUrl = 'stun:stun.l.google.com:19302'; // default value: 'stun:stun.l.google.com:19302'

TURN Part,
I will use the provided rfc5766-turn-server and config it but is there any other config needed and why it doesn't work with just erizo.controller.publicIP?

Regards

**Comment by zevarito** [comment]
Leave stunt as it is, setup turn server (configure turn local/external ip
before launch) use turn settings in licode config.

On Monday, May 4, 2015, farrukhmustafa <notifications@github.com> wrote:

> I will set it up today but two simple questions..
>
> STUN part
> Do I need to setup up both Turn and Stun servers? I see in
> licode_config.js, that google stun server is already mentioned. Do I need
> to do anything else? I am new to it so i apologize.
>
> /*********************************************************
> ERIZO CONTROLLER CONFIGURATION
> **********************************************************/
> config.erizoController = {};
> //Use undefined to run clients without Stun
> config.erizoController.stunServerUrl = 'stun:stun.l.google.com:19302'; //
> default value: 'stun:stun.l.google.com:19302'
>
> TURN Part,
> I will use the provided rfc5766-turn-server and config it but is there any
> other config needed and why it doesn't work with just
> erizo.controller.publicIP?
>
> Regards
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ging/licode/issues/293#issuecomment-98776972>.
>


-- 
Sent from Gmail Mobile

**Comment by farrukhmustafa** [comment]
I was able to resolve to with your help. Thank you for that. I first installed "rfc5766-turn-server" on a separate CentOS host but was unable to make it work with licode server. Then I installed turn server on licode server and somehow it started working.

Below are the required steps to install TURN server:

1) Install turn server as mentioned in below URL 

http://blog.knoldus.com/2013/10/24/configure-turn-server-for-webrtc-on-amazon-ec2/

Once it is installed, and ports are open, don't do step 4 and 6 on his blog. Follow below directions

2) create a cert/key using openssl command. I copied it in /usr/local/etc but you can use choose any folder where turn server has PATH mentioned.

openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout mysitename.key -out mysitename.crt

3) Copy paste below to a "turnserver.conf" and place it under "/usr/local/etc/
# RFC5766-TURN-SERVER configuration file
#
tls-listening-port=443
#Internal Amazon Private IP 
listening-ip=172.31.X.X
#Internal Amazon Private IP, same as above  
relay-ip=172.31.X.X
#External / Elastic IP from Amazon
external-ip=52.24.X.X
lt-cred-mech
#User:Password
user=User1:Password1
#Enable FingerPrinting
fingerprint
realm=ec2-52-X-X-X.us-west-2.compute.amazonaws.com
cert=/usr/local/etc/noricllccom.crt
pkey=/usr/local/etc/noricllccom.key

4) Start the server using --> nohup turnserver -v &

5) Start ./initLicode.sh and ./initBasicExample.sh again from ../licode/scripts/

Hope it helps....

**Comment by farrukhmustafa** [comment]
@zevarito .. While installing on Amazon CentOs, turn server runs perfectly but Licode server was unable to connect to it. Do you know any reason or do you think it should be installed on licode server?

**Comment by zevarito** [comment]
Hmm no reason comes to my mind. If Turn server is properly running, check
logs. And Licode config is pointing there with user and pass it should work.
Although in my case I have turn running on the same box that Licode, so I
cannot talk from experience.

On Tue, May 5, 2015 at 1:19 AM, farrukhmustafa <notifications@github.com>
wrote:

> @zevarito <https://github.com/zevarito> .. While installing on Amazon
> CentOs, turn server runs perfectly but Licode server was unable to connect
> to it. Do you know any reason or do you think it should be installed on
> licode server?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ging/licode/issues/293#issuecomment-98943668>.
>



-- 
Alvaro

**Comment by leilei6996** [comment]
do need set stun server in Licode config? only set trun server in licode config?
