### ISSUE TITLE
Feature: IOS Integration

### ISSUE THREAD

**Issue by zevarito** [ging/licode#296]
There is some work in progress on this area?

If not, are Licode team up to suggest a developing strategy of this?

I would love to do it, but need some guidance and support from your team first.

Thanks!

**Comment by lodoyun** [comment]
We don't have an "official" solution.
Licode now is compatible with [openwebrtc](http://www.openwebrtc.io) and any solution based on libjingle/google's webrtc should work with Licode.
If you don't use a javascript based solution (like cordova), you will need to implement licode's signalling and control (erizo.js). We will gladly ask any questions about that if you start working on it.

**Comment by zevarito** [comment]
I found that while it works with openwebrtc the performance seems to be very poor.
I could not find a solution to make it work with Cordova, does it require adapat PhoneRTC plugin or there is an out-of-the-box solution?

@lodoyun I think I will give a try to rewrite signaling on objc, which do you think will be the best communication channel to ask questions to you guys?

**Comment by zevarito** [comment]
I've started a native Erizo client for IOS.

You can check the project here: https://github.com/zevarito/ErizoClientIOS

From the README this are the current supported features:

* Connect to Rooms with encoded tokens.
* Capture local Audio & Video media.
* Publish local Media.
* Server side stream recording.

I'll try to complete the Roadmap in the following two weeks.

Developers are welcome to contribute!

**Comment by ArtisanCodesmith** [comment]
My pull request #394 makes Licode compatible with [Cordova](cordova.apache.com) and it's [iosrtc plugin](https://github.com/eface2face/cordova-plugin-iosrtc) and it works like a charm - performance is great as I not have an iOS hybrid Licode application! 

If you need any help let me know! :)

**Comment by remymateus** [comment]
@ArtisanCodesmith I need help implementing licode in a cordova app. ;)
