### ISSUE TITLE
Originals MKV files with undefined video and audio codecs

### ISSUE THREAD

**Issue by zevarito** [ging/licode#300]
Looking at the recorded MKV files, when I try to open them with VLC I get this error and reproduction suddenly stops.

Converting them with FFMPEG to a MP4 container allow the video to be watched in full length but it shows some quality issues that I cannot confirm with the original one (I could not play it end to end).

There is a way to get a better MKV output?

**Comment by jnoring** [comment]
You could try ffplay from the command line to do playback--that'll probably let you watch the original file.

**Comment by zevarito** [comment]
@jnoring that's correct it does the trick.

I found that the video starts at 640px wide then reduces the size to a half and then reduces the size again. Is that compensation bandwidth by the broadcaster?

**Comment by jnoring** [comment]
@zevarito that likely sounds like a bandwidth or CPU issue on sender or receiver.  WebRTC will automatically degrade bandwidth/resolution in response to limited resources.  Generally I'll look at the CPU on clients, and/or run an mtr at the same time to see what network conditions are like.

**Comment by zevarito** [comment]
Right, I believe that it was degraded bandwidth on broadcaster device, also
using 3G, not Wifi.
A point to notice is that we have removed REMB from SDP.

On Wed, May 27, 2015 at 3:51 PM, jnoring <notifications@github.com> wrote:

> @zevarito <https://github.com/zevarito> that likely sounds like a
> bandwidth or CPU issue on sender or receiver. WebRTC will automatically
> degrade bandwidth/resolution in response to limited resources. Generally
> I'll look at the CPU on clients, and/or run an mtr at the same time to see
> what network conditions are like.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ging/licode/issues/300#issuecomment-106033952>.
>



-- 
Alvaro

**Comment by jnoring** [comment]
I'm almost positive you will not be able to sustain VGA over a 3g connection, so it isn't surprising to me it drops the size at all.  Also, you're probably being limited by 3g *upload* speed, not download, but possibly both.  

I assume you're using opus for the audio codec?

**Comment by zevarito** [comment]
It does make sense, but I wonder if is better to request camera access with
less than VGA resolution in 3G scenarios since Chrome supports camera
viewport size definition.

Will this make a difference or should I let it fallback by his own?

That's right I am using opus for the Audio codec, is that better or worse?

On Thu, May 28, 2015 at 2:32 PM, jnoring <notifications@github.com> wrote:

> I'm almost positive you will not be able to sustain VGA over a 3g
> connection, so it isn't surprising to me it drops the size at all. Also,
> you're probably being limited by 3g *upload* speed, not download, but
> possibly both.
>
> I assume you're using opus for the audio codec?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ging/licode/issues/300#issuecomment-106511240>.
>



-- 
Alvaro

**Comment by jnoring** [comment]
I'd just let Chrome manage it.  It's going to send the best video it can.  You could possibly start with the resolution a bit lower if you know it's going to end up there anyway.

Opus is the best choice for audio by far.
