### ISSUE TITLE
How do I only record Audio

### ISSUE THREAD

**Issue by ajithreddy** [ging/licode#301]
I was just trying out the basic example of Licode. Even when I passed only audio stream, the recording is being done in a .mkv container. What do I do to only record the audio in opus format.

**Comment by cadrogui** [comment]
Hi, according to the documentation you must configure the server first.

http://lynckia.com/licode/client-api.html#recordStreamStart

````
Start Recording
Start the recording of a stream in the server in the path specified in licode_config.js

The recording will stored in a .mkv file using VP8 codec for video and PCMU or OPUS for audio, depending on the server configuration. This file can be played directly or streamed into a Licode room.

Licode will keep recording until stopRecording is called or the stream is removed from the room.
````

regards

**Comment by ajithreddy** [comment]
Thanks for the response. Can u guide me how to do this server configuration to record only audio

**Comment by cadrogui** [comment]
Hi, im new user like you, soon as figure out, i post a line.

regards.

**Comment by lodoyun** [comment]
The recording will be in a mkv but it will be an audio-only file, you can safely convert it to mp3 or any other format with ffmpeg.

**Comment by ajithreddy** [comment]
Is it not possible to record in opus format than converting it to mp3 or opus later

**Comment by ajithreddy** [comment]
Hi, 
I was making audio only calls and enabled recording. It recorded it in .mkv format but when I play the file it said 'undf' format cannot be identified. I guess it is not able to record opus audio in .mkv container. 
What is the solution for this as I want to leverage the low bitrates of Opus
