### ISSUE TITLE
Generating video other than mkv format?

### ISSUE THREAD

**Issue by thirdknife** [ging/licode#302]
Hi,

Is there a possibility that recorded video can be in standard web format like mpeg4?

**Comment by jnoring** [comment]
I don't think muxing into an mp4 is possible because I don't think mp4 containers will accept opus/vp8.  But admittedly I have not tried recently.

What are you trying to accomplish?

**Comment by thirdknife** [comment]
@jnoring I want to play the recorded videos in browser.

**Comment by lodoyun** [comment]
We are recording VP8 + OPUS/PCM, the only container that supported this at the time was mkv.
You can post-process the recording with ffmpeg or avconv to get a mp4/webm file.

**Comment by zevarito** [comment]
Just for the record, we have been using ffmpeg with several configurations
to encode original MKV into webm and mp4, but we have found better results
with Amazon Elastic Transcoder. However once a while we get some audio lost
that we haven't digging into it yet.

On Mon, Jun 15, 2015 at 5:33 AM, Pedro Rodriguez <notifications@github.com>
wrote:

> We are recording VP8 + OPUS/PCM, the only container that supported this at
> the time was mkv.
> You can post-process the recording with ffmpeg or avconv to get a mp4/webm
> file.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ging/licode/issues/302#issuecomment-111978212>.
>



-- 
Alvaro

**Comment by lodoyun** [comment]
This is not going to change for now. When a container suitable for the codecs browsers are using becomes available we will study it. For now, post-processing or playing video via Licode are the best options.
