### ISSUE TITLE
Basic Example not working: Cross-Origin

### ISSUE THREAD

**Issue by cracker0dks** [ging/licode#303]
Hey, 
I have installed licode on Ubuntu 14 a few minutes ago. If i try to test the basciExample, I see my webcam picture but in the console (firefox) I get the error: Cross-Origin-access denied on http://134.103.216.248:8080/socket.io/1/?t=1433449940512
and the voiceChat is not working!

why I get this error ? and how I can solve it ?

This is the crome console:
<sub>eyJ0b2tlbklkIjoiNTU3MGI4ODQzNjEyZTdhODA2ZTQ5ZjU0IiwiaG9zdCI6IjEzNC4xMDMuMjE2LjI0ODo4MDgwIiwic2VjdXJlIjpmYWxzZSwic2lnbmF0dXJlIjoiTWpZME5UbG1OalF3WlRRNFpHWmhOVFl4T0RreU1EZGhOemRrTjJReU9UTXhaV00yT1RrME9RPT0ifQ==
erizo.js:160 DEBUG:  Requested access to local media
erizo.js:160 DEBUG:  Object
erizo.js:160 INFO:  User has granted access to local media.
erizo.js:160 DEBUG:  Event: access-accepted
erizo.js:142 Object
erizo.js:160 DEBUG:  Creating URL from stream [object MediaStream]
http://134.103.216.248:8080/socket.io/1/?t=1433450626119 Failed to load resource: net::ERR_CONNECTION_REFUSED</sub>

EDIT: I think its the same problem: https://groups.google.com/forum/#!searchin/lynckia/socket.io/lynckia/DlVhXVZ4u1E/SIoq_Q3D_QEJ
its because Socket.io update from 0.9.6 to 1.0.5. anyone with a solution ?

EDIT2: So going back to Socket.io 0.9.16 didnt solve the problem for me

**Comment by cadrogui** [comment]
Hi, maybe this will help you:

http://stackoverflow.com/questions/11181546/how-to-enable-cross-origin-resource-sharing-cors-in-the-express-js-framework-o

try adding this to the example, cause i see and is not set this header:

````
res.header("Access-Control-Allow-Headers", "X-Requested-With");
````

regards.

**Comment by cracker0dks** [comment]
It was an socket.io version problem. I reinstalled the system new and dont install any new versions of socket.io. this works for me!
