### ISSUE TITLE
FIX - The package karma-requirejs does not satisfy its siblings on npm install bug

### ISSUE THREAD

**Issue by cadrogui** [ging/licode#305]
afte install i noticed that all packages are not installed, so i try to install all dependencies mentioned in the package.json via

````
npm install
````

cause of this i get this debug and the nom installation fails.

````
npm ERR! peerinvalid The package karma-requirejs does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer karma@0.10.10 wants karma-requirejs@~0.2.0

npm ERR! System Linux 3.2.0-85-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "mongojs"
npm ERR! cwd /home/music/licode
npm ERR! node -v v0.10.37
npm ERR! npm -v 1.4.28
npm ERR! code EPEERINVALID
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/music/licode/npm-debug.log
npm ERR! not ok code 0
````

to fix this, in the package.son i change the version of "karma-requirejs": "~0.2.0"

regards.

**Comment by j4y** [comment]
I also ran into this issue and added a pull request for it:

https://github.com/ging/licode/pull/307

**Comment by lodoyun** [comment]
This is actually not needed to run Licode. It is used for our internal automated test system, thanks for the report!
