### ISSUE TITLE
Running on Ubuntu 14 ?

### ISSUE THREAD

**Issue by cracker0dks** [ging/licode#306]
Does anyone got this running on ubuntu 14? I get an error while running:
> ./licode/scripts/installNuve.sh

Ubunut 12 is not supported anymore.

Thanks :)

**Comment by lodoyun** [comment]
It should work on Ubuntu 14.04 LTS.
Can you copy the error here?

**Comment by cracker0dks** [comment]
Hey, it was my fault. I had not enough space left on my hd.... now it runs! thanks for your nice work!
