### ISSUE TITLE
ScreenShare example dont work

### ISSUE THREAD

**Issue by cracker0dks** [ging/licode#313]
Both ScreenShare examples on: https://chotis2.dit.upm.es/ are not working because of: can not read "mandatory" of undefined! (without a line number)

I found out, that you have to replace: 
>line 8104: if(config.video.mandatory!= undefined){

with:

> line 8104: if(config.video!= undefined){

in erizo.js than everthing is working fine again. 

Have fun ;)

NOTE: this is chrome only problem!

**Comment by nachoaguadoc** [comment]
Hi,

There was a bug when screensharing in Chrome that caused config.video to be undefined. It's been fixed in a9b64b301d80579110d0f2006812cf1f9a017fd6

Thank you!
