### ISSUE TITLE
Having issues in latest deployment

### ISSUE THREAD

**Issue by ahmedkhak** [ging/licode#315]
I installed latest version of licode on my Ubuntu server. when i execute that command "./licode/scripts/initLicode.sh" it shows that message multiple times

"2015-06-25 09:01:22.600  - INFO: ErizoAgent - Launched new ErizoJS  0c22cc49-ea0                                                                                        e-ecbf-1cca-7e1dd7bc39ba
Running process"

and at the end it shows 

child_process.js:958
    throw errnoException(process._errno, 'spawn');
          ^
Error: spawn EMFILE
    at errnoException (child_process.js:1011:11)
    at ChildProcess.spawn (child_process.js:958:11)
    at exports.spawn (child_process.js:746:9)
    at launchErizoJS (/root/licode/erizo_controller/erizoAgent/erizoAgent.js:100                                                                                        :24)
    at fillErizos (/root/licode/erizo_controller/erizoAgent/erizoAgent.js:132:13                                                                                        )
    at ChildProcess.<anonymous> (/root/licode/erizo_controller/erizoAgent/erizoA                                                                                        gent.js:112:9)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Process.ChildProcess._handle.onexit (child_process.js:833:5)

After that i run "./licode/scripts/initBasicExample.sh", that shows no errors, but when i access page in console it shows information which is 

DEBUG:  Creating URL from stream [object MediaStream]
erizo.js:161 INFO:  Connected to room 558bdb9a27d5a926081d8f88
erizo.js:161 DEBUG:  Event: room-connected
erizo.js:161 ERROR:  Error when publishing the stream:  No ErizoAgents available

**Comment by lodoyun** [comment]
That looks like erizo was not successfully compiled.
Run scripts/installErizo.sh and paste the output

**Comment by ahmedkhak** [comment]
I executed that command "./licode/scripts/installErizo.sh", and result is 

Installing erizo...
-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE)
-- Found glib-2.0: /usr/include/glib-2.0, /usr/lib/x86_64-linux-gnu/libglib-2.0.so;/usr/lib/x86_64-linux-gnu/libgobject-2.0.so;/usr/lib/x86_64-linux-gnu/libgthread-2.0.so
-- Boost version: 1.54.0
-- Found the following Boost libraries:
--   thread
--   regex
--   system
-- Configuring done
-- Generating done
-- Build files have been written to: /root/licode/erizo/build
Done
[100%] Built target erizo
Installing erizoAPI...
building with node-gyp
gyp info it worked if it ends with ok
gyp info using node-gyp@0.10.10
gyp info using node@0.10.39 | linux | x64
gyp info spawn python
gyp info spawn args [ '/usr/share/node-gyp/gyp/gyp',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/root/licode/erizoAPI/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/share/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/include/nodejs/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/usr/include/nodejs',
gyp info spawn args   '-Dmodule_root_dir=/root/licode/erizoAPI',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp: /usr/include/nodejs/common.gypi not found (cwd: /root/licode/erizoAPI) while reading includes of binding.gyp while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:431:16)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 3.13.0-24-generic
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /root/licode/erizoAPI
gyp ERR! node -v v0.10.39
gyp ERR! node-gyp -v v0.10.10
gyp ERR! not ok
Installing erizoController...
[erizo_controller] Installing node_modules for erizo_controller

> ws@0.4.32 install /root/licode/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory `/root/licode/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node: Finished
  COPY Release/bufferutil.node
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  SOLINK_MODULE(target) Release/obj.target/validation.node: Finished
  COPY Release/validation.node
make: Leaving directory `/root/licode/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws/build'
node-getopt@0.2.3 ../node_modules/node-getopt

amqp@0.2.4 ../node_modules/amqp
└── lodash@1.3.1

log4js@0.6.26 ../node_modules/log4js
├── async@0.2.10
├── underscore@1.8.2
├── semver@4.3.6
└── readable-stream@1.0.33 (isarray@0.0.1, inherits@2.0.1, string_decoder@0.10.31, core-util-is@1.0.1)

socket.io@0.9.16 ../node_modules/socket.io
├── base64id@0.1.0
├── policyfile@0.0.4
├── redis@0.7.3
└── socket.io-client@0.9.16 (xmlhttprequest@1.4.2, uglify-js@1.2.5, active-x-obfuscator@0.0.1, ws@0.4.32)
[erizo_controller] Done, node_modules installed
[erizo_controller] Done, erizo.js compiled

**Comment by lodoyun** [comment]
erizoAPI is not compiling properly.
Are you running ubuntu 14.04?
What node.js installation are you using? the one installed with installUbuntuDeps should give you no trouble. That one should not be looking for gyp: /usr/include/nodejs/common.gypi not found (cwd: /root/licode/erizoAPI) while reading includes of binding.gyp while trying to load binding.gyp

**Comment by joshuairl** [comment]
I originally screwed this part up by trying to install node-gyp with apt-get prior to running the installUbuntuDeps.  I was trying to just install the minimum deps to just run Erizo and Nuve on one box and the rest on other boxes.

**Comment by thedgm** [comment]
I have different error upon installing:

```
[root@flashphone ~]# ./licode/scripts/installErizo.sh
Installing erizo...
-- Found glib-2.0: /usr/include/glib-2.0, /usr/lib64/libglib-2.0.so;/usr/lib64/libgobject-2.0.so;/usr/lib64/libgthread-2.0.so
-- Boost version: 1.53.0
-- Found the following Boost libraries:
--   thread
--   regex
--   system
-- Configuring done
-- Generating done
-- Build files have been written to: /root/licode/erizo/build
Done
Linking CXX shared library liberizo.so
/usr/bin/ld: /usr/local/lib/libavutil.a(error.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libavutil.a: could not read symbols: Bad value
collect2: error: ld returned 1 exit status
make[2]: *** [erizo/liberizo.so] Error 1
make[1]: *** [erizo/CMakeFiles/erizo.dir/all] Error 2
make: *** [all] Error 2

```

**Comment by anilshah** [comment]
Hi, I am facing the same problem. I tried to install licode on fresh ubuntu 14.04.
But while running the test page I see that the video is being published and it's throwing error ERROR:  Error when publishing the stream:  No ErizoAgents available.

Thanks
Anil
