### ISSUE TITLE
N.API.getUsers from room is Unauthorized

### ISSUE THREAD

**Issue by cracker0dks** [ging/licode#316]
Hey, I get the error:

> 401 Unauthorized

when I try to call:

> N.API.getUsers(rooms[i]["_id"], function(users) { ... });

This happen ONLY if I have more then 4 Room. 4 or less i got no Problem. The config file says somthing about max rooms: config.erizoController.limit_n_rooms = 20; // default value: 20

Why I get this error ? 
Thanks :)

**Comment by cracker0dks** [comment]
is there a limitation for request per seconds on the N.API ?

**Comment by lodoyun** [comment]
No, there is no "hardcoded" limitation.
However, there is a protection mechanism in Nuve requests. Among other things request headers include a Timestamp and a Cnonce. If you are issuing many requests and there are variations in network conditions, nuve may receive requests in a different order, resulting in an Auth Fail.
You can see this in the nuve logs, looking like this:
> INFO: NuveAuthenticator - Last timestamp:  1435739803087  and new:  1435739800422
> INFO: NuveAuthenticator - Last cnonce:  16863  and new:  71738
> INFO: NuveAuthenticator - [Auth] Invalid timestamp or cnonce

Overall, I would not be polling Nuve that often, or, at least, wait for one request to be responded before starting another.
