### ISSUE TITLE
Lost superserviceID and superserviceKey

### ISSUE THREAD

**Issue by cracker0dks** [ging/licode#326]
I override config.nuve.superserviceID and config.nuve.superserviceKey in the licode_config by accident . How can I get them back without install the hole thing again?

I cant find it... its not in the mongoDb and i cant find it in the files. 
Pls help. 
ty

**Comment by zevarito** [comment]
By reinstalling Nuve you should get those back.

On Saturday, July 18, 2015, cracker0dks <notifications@github.com> wrote:

> I override config.nuve.superserviceID and config.nuve.superserviceKey in
> the licode_config by accident . How can I get them back without install the
> hole thing again?
>
> I cant find it... its not in the mongoDb and i cant find it in the files.
> Pls help.
> ty
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ging/licode/issues/326>.
>


-- 
Sent from Gmail Mobile

**Comment by cracker0dks** [comment]
ok that worked. I thought i could get it without. 
Thanks :)
