### ISSUE TITLE
recording file can be saved as mp4 or webm?

### ISSUE THREAD

**Issue by leehong** [ging/licode#328]
the recording file default format mkv, play the mkv in chrome can`t  fast forward.

**Comment by ahmedkhak** [comment]
I converted recorded file to "webm", when "stop-recording" is called. You need to execute 

ffmpeg -i from_mkv_filename.mkv to_webm_filename.webm

command in "exec" function in "stopRecorder" event

**Comment by lodoyun** [comment]
To have fast-forward you should re-encode the file. A good way to do it is following @ahmedkhak 's advice

**Comment by leehong** [comment]
@ahmedkhak @lodoyun Thank you guys...
