### ISSUE TITLE
Running licode as a service?

### ISSUE THREAD

**Issue by joshuairl** [ging/licode#329]
The installation instructions do not mention a service or init.d being put in place.
Didn't know if that was part of the install or if I was missing something.

I don't see a way to start / stop it?

**Comment by cracker0dks** [comment]
All Licode parts are node servers that are started by the init script as demon. You can start and stop them by hand (in screen if you want)

**Comment by joshuairl** [comment]
If I run initLicode… but then ctrl+c… it stays running?
It does appear to stay running.

**Comment by cracker0dks** [comment]
Yep because the init script starts the node server with: "node xyz &" the "&" means as deamon take a look at this: http://stackoverflow.com/questions/4797050/how-to-run-process-as-background-and-never-die

**Comment by joshuairl** [comment]
It runs unless you logout of the shell session... then it stops...

**Comment by cracker0dks** [comment]
if you run your server with something like: "node myapp &" it will run after logout from shell. without "&" not! You can also can take a look at linux "screen" app which can help you to run apps when you are not in your session.

**Comment by lodoyun** [comment]
Also, you can use [forever](https://github.com/foreverjs/forever) or a similar alternative to make sure the different nodes keep running.
You will have to modify the start scripts or create your own (recommended) with the different parts of licode you want to start

**Comment by dzhusipov** [comment]
I'm using GNU Screen for running it at backgound. 
Example: screen -AmdSL basicserver node basicServer.js
