### ISSUE TITLE
What would cause the id of the video element to be undefined?

### ISSUE THREAD

**Issue by joshuairl** [ging/licode#333]
![image](https://cloud.githubusercontent.com/assets/171077/8942353/eaf06c22-3542-11e5-93f1-2fd8459d791d.png)

in Erizo.js the `that.id` is undefined for some reason.

Not sure why...? it says `that.elementID` is `user-video` which is correct and the video shows up fine but the view that's created has undefined all over.

**Comment by vibhorsd** [comment]
I used to get this too. The way I solved it is pass an id when creating the stream.

            var stream = Erizo.Stream({
                streamID: uuid.v1()
            });

**Comment by nachoaguadoc** [comment]
Hi @joshuairl,

Is that ID undefined only in your local video or in the others too?

**Comment by joshuairl** [comment]
It was only in local... I ended up modding the erizojs client to fix anything that was acting whacky for me... so didn't get this resolved.

**Comment by nachoaguadoc** [comment]
This is the normal behaviour because when you publish a stream you don't know your own ID. In which case do you need it to have the actual ID?

**Comment by nachoaguadoc** [comment]
Closed due to inactivity.
