### ISSUE TITLE
Deep Licode Architecture and understanding

### ISSUE THREAD

**Issue by cracker0dks** [ging/licode#335]
Hey,
since there is no complete model and description of the licode architecture, I tried to understand it by the simple model on the licode docu and reading in the licode google group. Here is my approach:

![licode architecture 1](https://cloud.githubusercontent.com/assets/1816621/8993885/26fdff9c-3708-11e5-9f57-3554754079dd.png)

Short Informations I found all around the components:
* **Nuve** Manage Erizo Controllers (can create more than one Erizo Controller if needed for scale) 
* **MongoDB**: Stores room and users in rooms
* **Erizo Controler**: Manage rooms and the users in it
* **MCU - Erizo Agent**: The C++ MCU that broadcast video/audio
* **RabbitMQ**: handles the propagation of media elements. It creates the media pipeline. 

Is this correct and can you please add Information if you know ?
You can edit the model if you want at: https://docs.google.com/drawings/d/1KIRmaJHh2GUH3rDQWXrnwhwhtI5FAdnBOFAptlvIo2s/edit

You can also add this or something like this to the doc on the licode page for better understanding?

**Comment by zevarito** [comment]
Great initiative!

2015-07-30 17:15 GMT-03:00 cracker0dks <notifications@github.com>:

> Hey,
> since there is no complete model and description of the licode
> architecture, I tried to understand it by the simple model on the licode
> docu and reading in the licode google group. Here is my approach:
>
> [image: licode architecture 1]
> <https://cloud.githubusercontent.com/assets/1816621/8993885/26fdff9c-3708-11e5-9f57-3554754079dd.png>
>
> Short Informations I found all around the components:
>
>    - *Nuve* Manage Erizo Controllers (can create more than one Erizo
>    Controller if needed for scale)
>    - *MongoDB*: Stores room and users in rooms
>    - *Erizo Controler*: Manage rooms and the users in it
>    - *MCU - Erizo Agent*: The C++ MCU that broadcast video/audio
>    - *RabbitMQ*: handles the propagation of media elements. It creates
>    the media pipeline.
>
> Is this correct and can you please and Information if you know ?
> You can edit the model if you want at:
> https://docs.google.com/drawings/d/1KIRmaJHh2GUH3rDQWXrnwhwhtI5FAdnBOFAptlvIo2s/edit
>
> You can also add this or something like this to the doc on the licode page
> for better understanding?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ging/licode/issues/335>.
>



-- 
Alvaro

**Comment by lodoyun** [comment]
Actually, it's more like this:
![licode architecture_fixed](https://cloud.githubusercontent.com/assets/932923/9057958/d88673b4-3a9d-11e5-884c-54dcc0f36e0c.png)

* **Nuve** Manages Services (Custom APPs), Rooms and Users, generates tokens for delegated auth so custom apps can provide access to users. It balances the Rooms among the available ErizoControllers.
* **MongoDB** Only used by Nuve to store information about rooms and tokens. No user information is managed by Licode.
* **Erizo Controler** Manages Control, signalling and data streams for the rooms assigned to it by Nuve. New started ErizoControllers are automatically discovered by Nuve as long as they are connected to the same RabbitMQ instance.
* **MCU - Erizo Agent+ErizoJS (ErizoAPI+ErizoC++):** Distributed MCU. A better explanation on how this works is available (here)[http://lynckia.com/licode/async.html] ErizoJS is NOT erizo.js from the client side, sorry about the naming confusion. 
* **RabbitMQ:** Message broker, enables the distribution of the architecture. Handles all the messages among the components of Licode.  It does not handle media and/or communicate with the Clients.

**Comment by cracker0dks** [comment]
Wow! Thank you very much for the awesome explanation!

**Comment by guogenfang** [comment]
Great,very helpful
