### ISSUE TITLE
Room distributed across multiple erizoAgents?

### ISSUE THREAD

**Issue by vipulrastogi** [ging/licode#338]
Is there any architecture of describing how room is shared across multiple erizoAgents ? I am wondering how media is shared across multiple ErizoJS in this case ?

**Comment by lodoyun** [comment]
There's a general architecture explanation in this issue https://github.com/ging/licode/issues/335 and in [this blog post] (http://lynckia.com/licode/async.html)
By default, publishers will be assigned to an ErizoJS provided by an Agent selected with round-robin.
This behaviour can be modified by (editing the policy) [https://github.com/ging/licode/blob/master/erizo_controller/erizoController/ch_policies/default_policy.js]

At this point ErizoJSs don't forward media to each other.

**Comment by arsenicraghav** [comment]
'default_policy.js' always return the same agent, so there's no round robin also ? or we need to make it round robin ?

exports.getErizoAgent = function () {
  'use strict';
  return 'ErizoAgent';
};
