### ISSUE TITLE
How to handle bandwidthAlert event

### ISSUE THREAD

**Issue by zevarito** [ging/licode#345]
Hi,

What suppose a client to do when receive a message of type `bandwidthAlert`?

Thanks!

**Comment by lodoyun** [comment]
It is only fired if you set up a lower bandwidth limit when publishing a stream with minVideoBW.

If you do that, Licode will keep track of the bandwidth reported by the clients if REMB RTCP messages are available. If the reported bandwidth of a subscriber does not meet the minimum requirements, a bandwidthAlert event is fired to that client. Besides if the bandwidth problem persists, Licode will end up stopping the video and stop forwarding RTCP packets from that subscriber to avoid degrading video quality to the others.

The event should be used by applications to warn clients, subscribe to a different stream, etc.

**Comment by zevarito** [comment]
@lodoyun Thanks for the explanation.
