### ISSUE TITLE
What is the logic behind using separate erizoJS process for each publisher

### ISSUE THREAD

**Issue by ajithreddy** [ging/licode#349]
Referring to : http://lynckia.com/licode/async.html
It seems that the article says that licode will launch a new process for each publisher. Isn't this an overkill. So for 50 publishers, I will have 50 processes which is a kind of overkill. I am not sure if I am missing something here. Please enlighten me about this.

**Comment by ivopavlik** [comment]
I'd like to point here my question from groups: https://groups.google.com/forum/#!topic/lynckia/xtDTuINqX3Q
I also have issue with "No Agents Available" when connection to RabbitMQ is timed-out when I had Nuve server on one node and more ErizoControllers and ErizoAgents on other nodes.

Thanks.

**Comment by lodoyun** [comment]
Well, basically it is explained in the post you link. We started by separating erizoController from the WebRTC stack of Licode. We implemented the Agent, which provides new broadcasters (erizoJS) on demand. By doing that, we can now host conferencing rooms across multiple servers. As a result of that, erizoJS started to be a process on its own.
Furthermore, recently, we implemented our *scaling policies* that allow you to customise how erizoControllers and Agents are selected from the pool of resources you may have. 

If you are only using one server, the advantage of having several processes is that a critical problem in one broadcast won't affect the others.

If you feel too many processes is a problem, its entirely configurable, you can set up the limit of processes per agent instance (here)[ https://github.com/ging/licode/blob/master/scripts/licode_default.js#L104], once the limit is reached, the same process will host more than one broadcaster.
