### ISSUE TITLE
Toggling video/audio on/off during call

### ISSUE THREAD

**Issue by alexpayne** [ging/licode#356]
localStream.updateConfiguration({video: false});

Doesn't seem to switch off the video whilst in a call. Is there a way to toggle the video/audio on and off during a call. If the client no longer wants to share the cam and mic basically?

Thanks.

**Comment by nachoaguadoc** [comment]
Hi!

You can turn off the video or audio locally in the client with ```localStream.stream.getAudioTracks()[0].enabled = false;``` and  ```localStream.stream.getVideoTracks()[0].enabled = false;```. This way the other members of the call won't be able to watch or listen to your stream. I hope it helps.

Best regards

**Comment by alexpayne** [comment]
Thanks.

What about stopping the cam and mic altogether? Removing the feeds from the
stream. Then switching back on?

**Comment by nachoaguadoc** [comment]
I think I don't get what you are trying to achieve. Why isn't valid for you to assign those two values to true or false and toggling them when needed?

**Comment by alexpayne** [comment]
Hi Ignacio,

Sorry, just tested the code out and it does what I wanted - many many
thanks!!
I thought that it might only hide it locally and that the remote people
would still be able to see and hear the person, but they can't. Which is
great.

Many thanks.

**Comment by nachoaguadoc** [comment]
Perfect! Glad to help, I close this issue then.

Best regards
