### ISSUE TITLE
installErizo.sh error

### ISSUE THREAD

**Issue by zoopnin** [ging/licode#357]
./licode/scripts/installErizo.sh
Installing erizo...
-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE) 
-- checking for module 'glib-2.0'
--   package 'glib-2.0' not found
CMake Error at /home/apps/licode/erizo/cmake/FindGlib.cmake:36 (message):
  pkg-config is needed
Call Stack (most recent call first):
  erizo/CMakeLists.txt:25 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/apps/licode/erizo/build/CMakeFiles/CMakeOutput.log".

**Comment by zoopnin** [comment]
what's the problem?

**Comment by nachoaguadoc** [comment]
Hi,

What Operating System are you using? Have you installed properly the dependencies with the script provided?

**Comment by zoopnin** [comment]
@nachoaguadoc 
I am using centos6.5.I have installed dependencies ,everything is fine.Just when I installed the installErizo.sh the errors happen.do you have any ideas.thanks very much.

**Comment by nachoaguadoc** [comment]
It seems that during the installation of the dependencies has been a problem. Have you tried reinstalling them? There should be an Error log during the process.

If the machine where you're installing them doesn't have enough free space the installation fails, have you checked that?
