### ISSUE TITLE
How to start the licode.

### ISSUE THREAD

**Issue by zoopnin** [ging/licode#360]
I step the document to build the licode success,but I don't know how to start the licode.The licode be installed on server ,but  i develop on local ,so how to call ?

**Comment by nachoaguadoc** [comment]
Have you followed the steps indicated in http://lynckia.com/licode/install.html? 

Once installed you just have to run the scripts ./initLicode.sh and ./initBasicExample.sh in your server and it should work fine.

**Comment by zoopnin** [comment]
@nachoaguadoc   I installed the licode a remote server .but I have to code on local,so how to test the local coding right or not ?

**Comment by nachoaguadoc** [comment]
@zoopnin There is a Client API to communicate with the server side of Licode. You can find it here http://lynckia.com/licode/client-api.html
