### ISSUE TITLE
When migrate to node v4

### ISSUE THREAD

**Issue by eorza** [ging/licode#363]
I tried to update my node version to v4, but it seems the node c++ API changed a lot since 0.12.0, so I can't compile the erizoAPI.

Is there any plan to update the node to the newest version?

**Comment by varunFX** [comment]
+1

**Comment by lodoyun** [comment]
We migrated erizoAPI to [Nan](https://github.com/nodejs/nan) so it should be possible to compile it in nod e above 0.10
Can't give you a timeline for migrating Licode to new versions of node, although we will at some point.

**Comment by casualuser** [comment]
Greetings!

So nowadays node 0.10 looks like completely outdated and became unmaintained on Oct '16
We're looking for WebRTC open platform for build own large commercial video content system.

And for a moment after quite long investigation of tech questions and details looks like Licode remains as the only suitable solution. Now we're experimenting with demos and looking for possible code integration into our system.

We just can't starting build big system with dependance on outdated node version.. 

So the question looks like - is there _any_ plans to upgrade Licode codebase to support current node.js LTS version and how easy that can be? Please shed some more light on this moment.
