### ISSUE TITLE
Let's fix those bug,Let the centos can run fine

### ISSUE THREAD

**Issue by zoopnin** [ging/licode#368]
I want to install licode on centos .so I call this srcipt. -->  scripts/installCentOsDepsUnattended.sh
I find the shell script some links miss.
as follow:

install_vpx(){
  [ -d $LIB_DIR ] || mkdir -p $LIB_DIR
  cd $LIB_DIR
  curl -O https://webm.googlecode.com/files/libvpx-v1.0.0.tar.bz2
  tar -xf libvpx-v1.0.0.tar.bz2
  cd libvpx-v1.0.0
  ./configure --prefix=$PREFIX_DIR --enable-vp8 --enable-shared --enable-pic
  make -s V=0
  make install
  cd $CURRENT_DIR

}

**Comment by lodoyun** [comment]
What link is missing?
We don't "officially" support CentOS, that script does work in some distributions. If you point me to the specific problem we'll try to fix it

**Comment by nachoaguadoc** [comment]
Closed due to inactivity.
