### ISSUE TITLE
Error on last codebase (ErizoAgent)

### ISSUE THREAD

**Issue by cracker0dks** [ging/licode#369]
I installed the last codebase on a clean system (Ubuntu14.04) a few minutes ago. 
When I run: ./licode/scripts/initLicode.sh
it will spawn this endless logs in 1sec interval: 
    
    2015-11-23 10:22:54.764  - INFO: ErizoAgent - Launched new ErizoJS  becb38ea-c3e0-b998-6ceb-     1e699f78e3bc
    Running process

Until: 

    child_process.js:958
    throw errnoException(process._errno, 'spawn');
          ^
    Error: spawn EMFILE

It can not spawn any more... after that error I get a lot of (Every 5 Sec): 

    2015-11-23 10:25:02.591  - WARN: ECCH - No agents available

So something is wrong here. What can I do?

**Comment by lodoyun** [comment]
Looks like you have too many files/sockets open. You can check this limit by running ```ulimit -a```  usually is 1024 by default.
In a production environment (or for stress testing) you will probably have to change that limit.

**Comment by cracker0dks** [comment]
yeah, but this was after a clean install of the os and licode. But I tested again with the last commit and everything works fine now. Thanks :)
