### ISSUE TITLE
High CPU Usage on voice only

### ISSUE THREAD

**Issue by cracker0dks** [ging/licode#371]
Hey, 
Im using voice only at the moment on all clients:

    var config = {
        audio: true,
        video: false,
        data: true,
        screen: false,
        videoSize: [640, 480, 640, 480]
    };

    localStream = Erizo.Stream(config);

But I got massive CPU usage on the Server. 
![snip](https://cloud.githubusercontent.com/assets/1816621/11447224/deb34c80-9542-11e5-87cf-9ea9ed5f3f4d.PNG)
(This is on 1 cpu 2.5GhZ)

I diddnt find any parameter to turn the room into a voice only room. 

How can I reduce the cpu usage when all my clients only have Voice Chat on?

**Comment by jnoring** [comment]
Why are you specifying a videoSize in your config?  And what sort of bandwidth are you sending to the server?

Also, keep in mind licode is n^2 as you add more clients to a room.  If you have 12 clients in the same room, there are 144 streams licode is processing, in other words.  For 4 clients, it's 16 streams.

**Comment by cracker0dks** [comment]
Thanks for your reply. Because "videoSize" was in the standard config, thats why :)  But "video" is set to false. I don't see any n^2 in my graph do you ? What do you mean by "sort of bandwith"? I noticed, that when I activate screenshare, I got no increase of CPU usage!

**Comment by lodoyun** [comment]
Hi, there should be no problem with using "videoSize" if video is false, it should be ignored by Licode.
As @jnoring  said connections (and CPU use) grow quadratically in a centralised topology. 

You can tackle this in many ways:

- Switching codecs. If you are using PCMU (default in Licode) you can switch to OPUS by changing SDPInfo.cpp to include that codec. OPUS will be more intelligent in the use of bandwidth, the less bandwidth, the less CPU needed.
- Muting streams. Usually you don't need 12 or more people talking at the same time, design your application to minimise the amount of people talking at the same time. Muting a stream will stop sending traffic to Licode even if the stream is still alive.
- Distributing rooms. If you absolutely need all the streams working at the same time and changing to OPUS is not enough, you will need more computing power. By deploying more erizoAgents you can add more participants distributed in several servers while being in the same Licode room.

**Comment by cracker0dks** [comment]
Thanks for your reply. 
I will try Opus and test if its better. Why is PCMU default if you think OPUS is better at handling bandwith ? It is because of quallity? licence ?

I mute the user by overwriting the mic input with 0. But this still sends 0. Is their a smarter way to mute/unmute ?

I allready distributed to 2 Servers 16 CPUs each and got no problems at all. The thing about my question was, that I talked to my Network Management Proffesor about the CPU usage and he told me that on the most MCU he knows the CPU usage is 100% at about 100 Users (voice only). This might be hardware MCUs but 100% at 10 Users at this MCU (as shown in the graph) makes me wonder :)

btw. can u explain why I get no CPU increase if I enable screenshare ?

**Comment by lodoyun** [comment]
The OPUS thing is mostly legacy, it did solve some problems in the beginning with recording and with streaming media outside of Licode. We will probably set it as default in the near future.

You can disable the audio track locally in the publisher:
```
localStream.getAudioTracks()[0].enabled = false; // muted
localStream.getAudioTracks()[0].enabled = true; // unmuted
```

Performance really depends on the MCU, how it works and how users are arranged. Regarding screensharing... I assume you are only publishing 1 screen (not one from each user), in that case the CPU progression will be linear and it will reach a point where it is hardly noticeable compared to audio (that grows quadratically).
