### ISSUE TITLE
Dockerfile not working

### ISSUE THREAD

**Issue by cracker0dks** [ging/licode#372]
Hey, 
i cant get the dockerfile running! after this command (I changed the ip of course):

     sudo docker run -d --name licode -p 3001:3001 -p 8080:8080 -p 3000:3000 -p 30000-31000:30000-31000/udp -e "PUBLIC_IP=XXX.XXX.XXX.XXX" lynckia/licode

I get the Error (after downloading and stuff): 

    Error response from daemon: Cannot start container licode: failed to create endpoint licode on network bridge: iptables failed: iptables --wait -t nat -A POSTROUTING -p udp -s 172.17.0.2 -d 172.17.0.2 --dport 30499 -j MASQUERADE:  (fork/exec /sbin/iptables: cannot allocate memory)
    Error: failed to start containers: [licode]

Tested on 2 different server (One Digitalocean - pre installed Docker server) same error both!

Is this my fault ?

PS: I get the same error if I build my docker container from git scource

**Comment by mosfet1kg** [comment]
I don't know why did his problem happen.
But anyway I have a question with regard to this command.
Docker uses proxy process entitled as "docker-proxy" which requires some small amount of memory, which can be measured by using "top" or "htop" monitoring tool in linux.
For example, if you invoke port mapping from 3000 to 30100, docker generates 100 docker-proxy processes.
So I think the use of wide IP range for port mapping is not proper way. 

I have studied to implement live video streaming platform taking advantage of docker and licode. 
The aformentioned problem makes related implementation difficult.

**Comment by cracker0dks** [comment]
have you tried to use: --net=host (When you only run one docker container) or bridge the network to your docker container (if you have more than one ?)

**Comment by mosfet1kg** [comment]
Oh my.... Is it really working? In my case, rabbitmq is not working on --net=host environment.

**Comment by cracker0dks** [comment]
Don't know... I have not tested. This just came to my mind as I saw your prob^^

**Comment by lodoyun** [comment]
What docker version are you using? 
Doing a quick search I've found [this](https://github.com/docker/docker/issues/12848)
And it points to a memory leak in older versions of docker (<1.7). Also, check the available memory in the host.

**Comment by cracker0dks** [comment]
Yeah it was the old docker version. I was running Docker 1.6.
Now upgraded to 1.9.1 and its running without problems! 
Thanks!
