### ISSUE TITLE
Licode video recording not working with Chrome 47

### ISSUE THREAD

**Issue by j4y** [ging/licode#373]
Chrome 47 was just released to the stable channel today for Windows/Linux/Mac:

http://googlechromereleases.blogspot.se/2015/12/stable-channel-update.html

We noticed that video recording stopped working.  Perhaps something in ChromeStableStack.js needs to be updated?

**Comment by jnoring** [comment]
Hmm--that's odd.  I would think something in ExternalOutput.cpp would actually need to be updated.  Is video recording even creating a file at all?  are there any errors or output?

**Comment by lainor** [comment]
Hi, just tested with Chrome 47 on Mac, recording seems to work fine here.

*Fabrizio Sestito*
Co-founder & CTO
*xpli.ca <http://xpli.ca/>*

Tel: +49 (0) 176 958 77049
Twitter: @FabrizioSestito <https://twitter.com/FabrizioSestito>

**Comment by j4y** [comment]
One thing I have noticed is that the candidates come back slightly different in v46:
```
erizo.js:6099 INFO:  Storing candidate:  1 Object {sdpMLineIndex: 0, sdpMid: "video", candidate: "a=candidate:3903771101 1 udp 2122260223 192.168.44.83 54999 typ host generation 0"}
erizo.js:6099 INFO:  Storing candidate:  2 Object {sdpMLineIndex: 0, sdpMid: "video", candidate: "a=candidate:3903771101 2 udp 2122260222 192.168.44.83 50976 typ host generation 0"}
erizo.js:4158 Candidates to be added:  0 []
erizo.js:4163 Local candidates to send: 2
```

than in 47:
```
erizo.js:6094 INFO:  Storing candidate:  1 Object {sdpMLineIndex: 0, sdpMid: "video", candidate: "a=candidate:3903771101 1 udp 2122260223 192.168.44.83 61716 typ host generation 0"}
erizo.js:6094 INFO:  Storing candidate:  2 Object {sdpMLineIndex: 0, sdpMid: "video", candidate: "a=candidate:3903771101 2 udp 2122260222 192.168.44.83 62203 typ host generation 0"}
erizo.js:6094 INFO:  Storing candidate:  3 Object {sdpMLineIndex: 0, sdpMid: "video", candidate: "a=candidate:1776736105 2 udp 1686052606 74.104.143…rflx raddr 192.168.44.83 rport 62203 generation 0"}
erizo.js:6094 INFO:  Storing candidate:  4 Object {sdpMLineIndex: 0, sdpMid: "video", candidate: "a=candidate:1776736105 1 udp 1686052607 74.104.143…rflx raddr 192.168.44.83 rport 61716 generation 0"}
erizo.js:6094 INFO:  Storing candidate:  5 Object {sdpMLineIndex: 0, sdpMid: "video", candidate: "a=candidate:2787978541 1 tcp 1518280447 192.168.44.83 0 typ host tcptype active generation 0"}
erizo.js:6094 INFO:  Storing candidate:  6 Object {sdpMLineIndex: 0, sdpMid: "video", candidate: "a=candidate:2787978541 2 tcp 1518280446 192.168.44.83 0 typ host tcptype active generation 0"}
erizo.js:4030 End of candidates.
```

**Comment by lainor** [comment]
What's happening exactly? Is the recording button showing up or is the recording black?

**Comment by jnoring** [comment]
Does basic example work (as in, can you see other people in the room if they join?)  Does licode create a recording that doesn't play, no recording at all, explode with an error.....other?

**Comment by j4y** [comment]
This is a bug in Chrome 47.  It's not possible to stream without audio.

**Comment by j4y** [comment]
This issue #375 is related
