### ISSUE TITLE
Limit bandwidth server-side to protect server?

### ISSUE THREAD

**Issue by oliverhausler** [ging/licode#378]
You specify here http://lynckia.com/licode/client-api.html that the client can set a max bandwidth for a stream: `var config = {maxVideoBW: 300, maxAudioBW: 300};`

In WebRtcConnection.cpp `WebRtcConnection::setRemoteSdp` I can see this code:

    if (remoteSdp_.videoBandwidth !=0){
      ELOG_DEBUG("Setting remote bandwidth %u", remoteSdp_.videoBandwidth);
      this->rtcpProcessor_->setVideoBW(remoteSdp_.videoBandwidth*1000);
    }

Does that mean bandwidth can only be controlled by the client? Is there a server-side protection to protect the server from a malicious client raising its bandwidth arbitrarily?

**Comment by lodoyun** [comment]
In the [configuration](https://github.com/ging/licode/blob/master/scripts/licode_default.js#L47-L48) you can set both the default and maximum bandwidth that can be set via the client.

The max value set in the configuration limits what can be set via the clients.

**Comment by oliverhausler** [comment]
Thank you @lodoyun, I closed this.
