### ISSUE TITLE
Can't publish screen stream with Chrome 47

### ISSUE THREAD

**Issue by loganathan-r** [ging/licode#379]
Using windows 8 with Chrome 47, not able to publish local screen sharing stream. I have tested with Licode demo Screen sharing rooms https://chotis2.dit.upm.es/room?id=52949272f4094e6e6c00001e located in https://chotis2.dit.upm.es/

This may be similar to open issue [GitHub](https://github.com/ging/licode/issues/375)

**Comment by j4y** [comment]
see Pull Request #381

**Comment by lodoyun** [comment]
After pull request #381 it works in our test, please reopen if the issue persists.

Thanks @j4y

**Comment by loganathan-r** [comment]
It works after the fix. Thanks @j4y
