### ISSUE TITLE
Sometimes I may disconnect with each other while testing the Basic Example

### ISSUE THREAD

**Issue by aaa132452** [ging/licode#385]
I installed Licode on a physical machine with ubuntu 12.04 x86,4G RAM, Intel(R) Pentium(R) CPU G630 @ 2.70GHz.There were 2 men taking parting in this test and using firefox 42.0.Could you please provide some possible problems and solutions?When someone disconnect with the romm,the console will print "Removing xxx " and same as exit normally.

**Comment by lodoyun** [comment]
Are you still having this problem?
Without knowing anything else, I would blame the network connection, especially if ICE checks succeeded and the communication was established before the failure.

**Comment by nachoaguadoc** [comment]
Closed due to inactivity.
