### ISSUE TITLE
Server does not add publisher if video only stream published from FireFox 42 and above

### ISSUE THREAD

**Issue by loganathan-r** [ging/licode#387]
I'm not able to publish video only stream from FireFox 42 & above. 
The `'signaling_message_erizo'` event returned `'timeout'` message like below
`Object { mess: "timeout", peerId: 524482292123138900, ErrorCode: 6 }`

when looking at console log and erizo log, FireFox 42 does not add Bundle attribute on SDP, so it set Bundle as false `Is bundle? 0`, see erizo log below

`DEBUG WebRtcConnection (77) Is bundle? 0`
`DEBUG WebRtcConnection (80) Video 1 videossrc 396508465 Audio 0 audio ssrc 0 Bundle 0`
`DEBUG WebRtcConnection (82) Setting SSRC to localSdp 55543`
`DEBUG DtlsTransport (81) Initializing DtlsTransport`
`DEBUG NiceConnection (91) Creating Agent`
`DEBUG NiceConnection (116) Setting STUN server 54.172.164.4:443`
`DEBUG NiceConnection (130) Adding Stream... Number of components 1`
`DEBUG WebRtcConnection (140) Setting remote bandwidth 300`
`DEBUG NiceConnection (263) Gathering candidates 0x1859eb0`

I presume Licode does not handle stream without Bundle tag. Till versions FireFox 41, SDP contains Bundle attributes, hence it works

**Comment by nachoaguadoc** [comment]
Hi, we pushed a fix for this in f341fd10f03973424b294c0b223fa28b7fd6bec4. It should work fine now, thank you.
