### ISSUE TITLE
Chrome 47 video freeze when startRecording is called

### ISSUE THREAD

**Issue by theDude30** [ging/licode#388]
Hi,
It looks like that a/v works well on chrome 47 but when calling "room.startRecording" it will freeze the audio video component and i cannot close chrome browser normally(i had to terminate the process).
This tested on the test application as well.

Any suggestions?

**Comment by razaceme31** [comment]
Hi,
I am having the same issue a/v recording is not possible and components freeze, however browser can be controlled normally.
I am wondering if it is a licode bug or a chrome update has caused it.?
Any help please.

**Comment by lodoyun** [comment]
I haven't been able to reproduce this.
Any more details? What OS? Are you trying to record video, audio or both?

**Comment by theDude30** [comment]
happens when i try to record video stream by using the following:
 room.startRecording(stream,roomName, function(id) {
        recording = true;
        recordingId = id;
      });

tested on:
client: chrome47 mac and windows.
server: ubuntu

**Comment by lodoyun** [comment]
I've been able to reproduce this with older versions of Licode (pre-August). The issue has to do with the old/hacky FIR Packets sent to get KeyFrames when recording, this has changed since.

Try updating Licode and reopen if it still does not work
