### ISSUE TITLE
What is the factor that kill nuve.js automatically?

### ISSUE THREAD

**Issue by prospdragon** [ging/licode#391]
I've running licode basic_example on aws.
It works well.
But after 2~3 hours, I access it on my browser then it does not works.
Before access it, I have check daemons.

ps aux | grep node
root      3857  0.0  2.9 1075016 117840 ?      Sl   11:43   0:09 node nuve.js
root      3869  0.1  4.7 935708 191760 ?       Sl   11:43   0:17 node erizoController.js
root      3876  0.0  1.3 794924 55036 ?        Sl   11:43   0:02 node erizoAgent.js
root      3881  2.3  1.0 1774852 40716 ?       Sl   11:43   6:25 node ./../erizoJS/erizoJS.js 4858dc76-6159-2422-75bd-669e7104e327 172.31.53.212 172.31.53.212
... .. ...

after I access on my browser, I have checked daemons;
root      3876  0.0  1.3 794924 55036 ?        Sl   11:43   0:02 node erizoAgent.js
root      3881  2.3  1.0 1709596 41748 ?       Sl   11:43   6:25 node ./../erizoJS/erizoJS.js 4858dc76-6159-2422-75bd-669e7104e327 172.31.53.212 172.31.53.212
... ... ...

As you see, "node nuve.js" and "node erizoController.js" is killed.
I'd like to know why.

**Comment by Saadkhalid-mm** [comment]
Same happens with me. There is no reason I could identify. I have been trying to monitor the log to capture the issue, but I haven't been able to do that for now.

**Comment by Saadkhalid-mm** [comment]
@lodoyun @zevarito Any idea guys? We can't really trace the issue. My implementation is on AWS. Using Ubuntu. I have a turn server implemented as well.

**Comment by prettynatty** [comment]
I found that controller dies when client passes to it `undefined` as a callback

**Comment by Saadkhalid-mm** [comment]
@prettynatty can you please elaborate a little further? I'm a little new to this solution so I'm facing some difficulty in understanding what you are referring to when you say 'client passes to it undefined as a callback'. Any specific part of code you can refer to? Or any specific event you can point towards?

**Comment by prospdragon** [comment]
maybe we can avoid this issue by using 'forever' module.
but i think it's not best way

**Comment by Saadkhalid-mm** [comment]
It isn't a solution of the problem. Rather it's a patch work. Users would still face disruptions and downtimes. We really need to diagnose the actual issue.

**Comment by lodoyun** [comment]
Are you using the last version from the master branch? 
We did correct a couple of bugs that may cause this a while ago.
Otherwise, can you attach nuve and erizoController logs?

**Comment by prospdragon** [comment]
I'm using the last version.
I have installed on Ubuntu 14.04 of AWS.
I'll attach logs soon.
