### ISSUE TITLE
Windows build file for ErizoClient is incomplete

### ISSUE THREAD

**Issue by Mido22** [ging/licode#392]
when building erizo client in Linux environment( using file `erizo_controller/erizoClient/tools/
compile.sh`), it works fine, but in windows env, the `erizo.js` built with `compile.bat` does not work properly.

Upon comparison between the two compile scripts, the issue was obvious, `compile.bat` does not include the `webrtc-stacks` files, once I added them, it started functioning properly. 

P.S:  on a related note, any plans of replacing webrtc-stacks with `adapter.js` in the future?
( P.P.S would be happy to work on that if you are short on resources)

**Comment by Globik** [comment]
And where is here a compile.bat? I don't see it.

**Comment by varunFX** [comment]
I was talking about [this file](https://github.com/ging/licode/blob/master/erizo_controller/erizoClient/tools/compile.bat), but seens like it got fixed in [this recent commit](https://github.com/ging/licode/commit/b6c9f5f484247af0c00592a983ff153b1f24aa24)

**Comment by Mido22** [comment]
I was talking about [this file](https://github.com/ging/licode/blob/master/erizo_controller/erizoClient/tools/compile.bat), but seens like it got fixed in [this recent commit](https://github.com/ging/licode/commit/b6c9f5f484247af0c00592a983ff153b1f24aa24).
