### ISSUE TITLE
Docker install and image not working

### ISSUE THREAD

**Issue by cracker0dks** [ging/licode#397]
If I want to start the given Docker image or install my own Dockerimage I get the following error if i start ./licode/scripts/initLicode.sh:

    2016-01-14 23:50:25.416  - ERROR: RPC - Connection error... { [Error: connect ECONNREFUSED]
    code: 'ECONNREFUSED',
    errno: 'ECONNREFUSED',
    syscall: 'connect' }
    Error: connect ECONNREFUSED
    at errnoException (net.js:905:11)
    at Object.afterConnect [as oncomplete] (net.js:896:19)  killing process.

Maybe its happening because of this error while installing ./licode/scripts/installNuve.sh:

    SOLINK_MODULE(target) Release/obj.target/kerberos.node
    /usr/bin/ld: cannot find -lkrb5
    /usr/bin/ld: cannot find -lgssapi_krb5
    collect2: error: ld returned 1 exit status
    make: *** [Release/obj.target/kerberos.node] Error 1
    make: Leaving directory     `/home/licode/node_modules/mongojs/node_modules/mongodb/node_modules/kerberos/build'
    gyp ERR! build error
    gyp ERR! stack Error: `make` failed with exit code: 2
    gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-     gyp/lib/build.js:267:23)
    gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
    gyp ERR! System Linux 3.16.0-30-generic
    gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js"     "rebuild"
    gyp ERR! cwd      /home/licode/node_modules/mongojs/node_modules/mongodb/node_modules/kerberos
    gyp ERR! node -v v0.10.37
    gyp ERR! node-gyp -v v1.0.1
    gyp ERR! not ok
    node-getopt@0.2.3 ../../node_modules/node-getopt

I tested this on 3 different systems with the latest docker (1.9.1): 
If I install without docker on a clean system it works!

Can anybody help? Anybody got the same problem?
This is the example code only!

Thanks :)

**Comment by mosfet1kg** [comment]
I also checked that this docker file is not working.
I think that you had better make a new docker image which shoud have a bash
script excuting mongod and rabbitmq.
2016. 1. 15. 오전 8:58에 "cracker0dks" <notifications@github.com>님이 작성:

**Comment by cracker0dks** [comment]
Ok that means:
1 Docker mongoDb and rabbitmq 
1 Docker licode stuff 
Is that working for you ?

**Comment by mosfet1kg** [comment]
I wrote three new bash scripts and modified initLicode.sh.
When we launch new container, we can run a bash script by taking advantage of entrypoint command.
<code>docker run -ti -d -e CLUSTERED=true -e ISMASTER=true -e HOSTIP=143.248.142.191 -e MINPORT=30000 -e MAXPORT=30100 -e MAXVIDEOBW=3000 --hostname rabbit1 -p 3000:3000 -p 3001:3001 -p 8080:8080 -p 30000-30100:30000-30100/udp --entrypoint="/opt/licode/initMCU.sh" {image name}</code>

1./opt/initMCU.sh
<code>#!/bin/bash

cd /opt/licode/
./startRabbit.sh
./startMongod.sh

cd /home/licode/scripts/
./initLicode.sh
</code>

**Comment by cracker0dks** [comment]
Thanks for you scripts. 
I tried it but I think startRabbit.sh is missing.
Can you please post. 
It is possible that you provide your final working image ?

**Comment by mosfet1kg** [comment]
I didn't omit startRabbit.sh.  Please check one more time.
final image.. hmm
I have never use public docker registry.
When I know how to use its function, I will share my image.

**Comment by cracker0dks** [comment]
Ok got it running :) very nice! (didnt saw startRabbit.sh -> my fault)

Thanks :)

PS: you wrote /opt/scripts but in your initMCU.sh you go to /opt/licode/sctipts I removed the licode from the initMCU file in my case.

And for all the people who want to build their own docker, you have to change the superserviceID & superserviceKey to your own at licode_config.js (this values will be echoed on your licode installation)

**Comment by mosfet1kg** [comment]
You right... I made a few mistake
Anyway, i am happy because my scripts can be used for your work. ^_^

**Comment by cracker0dks** [comment]
Yeah makes me happy too :D 
Changed the scripts at some points and pushed the working Image to docker hub: https://hub.docker.com/r/rofl256/licode_basic/

hope this helps someone else :)

**Comment by mosfet1kg** [comment]
hmm.. I omitted a step for clustering between containers where licode works in. Rabbitmq has an weird property.  Everytime we deploy a licode container , the rabbitmq port for clustering is assigned randomly. 
Therefore, we should modify the rabbitmq configuration file  to avoid the aforementioned problem.

vi /etc/rabbitmq/rabbitmq-env.conf

export SERVER_ERL_ARGS="$SERVER_ERL_ARGS -kernel inet_dist_listen_min 65000 -kernel inet_dist_listen_max 65000"


--------
After these step, we can launch distributed MCU.

at host2   
$ echo {{your hostIP}} rabbit1 >> /etc/hosts

at host1
$ echo {{another hostIP}} rabbit2 >> /etc/hosts

at host1
docker run -ti -d -e CLUSTERED=true -e ISMASTER=true -e HOSTIP={{your hostIP}} -e MINPORT=30000 -e MAXPORT=30100 --hostname rabbit1 -e MAXVIDEOBW=1000000 -p 3000:3000 -p 3001:3001 -p 8080:8080 -p 30000-30100:30000-30100/udp -p 65000:65000 -p 4369:4369 {{licodeImg}}

at host2
docker run -ti -d -e CLUSTERED=true -e ISMASTER='' -e HOSTIP={{another your host IP}} -e MINPORT=30000 -e MAXPORT=30100 --hostname rabbit2 -e CLUSTER_WITH=rabbit1 -e MAXVIDEOBW=1000000 -p 3000:3000 -p 3001:3001 -p 8080:8080 -p 30000-30100:30000-30100/udp -p 65000:65000 -p 4369:4369 {{licodeImg}}

**Comment by cracker0dks** [comment]
Good to know. The rabbitmq-env.conf is only on this place if you turn cluster on? Its missing on my current installation.

**Comment by mosfet1kg** [comment]
@cracker0dks Nope..  When rabbitmq turns on and a rabbitmq-env.conf exists, rabbitmq only refer to this config file.

**Comment by cracker0dks** [comment]
Dont know How to implement this in the automatic script... if you want to, you can send me the script to change the line in: /etc/rabbitmq/rabbitmq-env.conf. Then I will update my docker script.

**Comment by mosfet1kg** [comment]
@cracker0dks 
 I'm sorry to make you confused. 

Alas It's getting difficult to describe the steps for clustering among containers. 
In my opinion, it is impossible to make automatic rabbitmq clustering without another component like DNS, because rabbitmq depends on hostname for clustering. 
That's why we need some command "$ echo {{another hostIP}} rabbit2 >> /etc/hosts"

So I think it's impossible automatic script without DNS.
If you want to make cluster among containers, please launch container without "entrypoint" argument and then execute "initMCU.sh" after a command like "$ echo {{another hostIP}} rabbit2 >> /etc/hosts".

Besides, I recommend for you to study "iptables". I will explain why it needs later.

**Comment by cracker0dks** [comment]
I dont need to cluster RabbitMQ at the moment. I just thought it would be nice to have it included. How many clients are on your system that you have to scale RabbitMq ?

**Comment by mosfet1kg** [comment]
@cracker0dks 
Sorry for late...

I usually deploy Licode containers into several physical server.
In my opinion, Licode has very very nice horizontal scalability however it shows not good performance in aspect of vertical scalability.
One licode container can handle video sessions very well below 10MB/sec network throughput in my environment(1GB ethernet, 16cores macpro).

However a lot of packet loss caused when network throughput reaches 10MB/sec.
At that time, CPU usage is only 300% so only one container cannot use system resource efficiently.

So as to solve this problem, we can deploy multiple licode containers into a physical server.
Each container can handle 10MB/sec If the containers are clustered, therefore a physical server throughput can increase as a rule of thumb.

**Comment by cracker0dks** [comment]
ok thanks, but you scale licode (erizo)? Or do you deploy rabbitMQ with each container?

**Comment by mosfet1kg** [comment]
https://www.terena.org/activities/tf-webrtc/meeting1/slides/Lynckia.pdf

Licode uses rabbitmq as message channel.  Simply speaking, we can modify licode host in licode_config.json or use rabbitmqctl for clustering. 

The former method is easier than the latter.
