### ISSUE TITLE
Strange erizo error

### ISSUE THREAD

**Issue by karth295** [ging/licode#401]
My licode server has been periodically crashing, and I've been trying to get to the bottom of it. I found this strange error message in the logs:

2016-01-10 18:24:29,664  - ERROR: WebRtcConnection - Update Transport State with Transport NULL, this should not happen!

[erizo-ac9dbb57-def0-23f4-0cb4-7edc02c54443.log.txt](https://github.com/ging/licode/files/93911/erizo-ac9dbb57-def0-23f4-0cb4-7edc02c54443.log.txt)

**Comment by lodoyun** [comment]
There were a couple of potential race conditions in the WebRTCConnection startup flow that could cause this.

Should be fixed as of 8caf8b1dd6fe346c3966f4c9196b9639dff948b6
