### ISSUE TITLE
nuveAuthenticator error cause by express deprecated

### ISSUE THREAD

**Issue by ridzeal** [ging/licode#402]
Error Log Message: 
nuve-0 (err): Sun, 17 Jan 2016 09:45:34 GMT express deprecated res.send(status, body): Use res.status(status).send(body) instead at auth/nuveAuthenticator.js:113:13

Propose fix:
Modify res.send(401, {'WWW-Authenticate': challengeReq});
To res.status(401).send({'WWW-Authenticate': challengeReq});

Fixed file attached
[nuveAuthenticator.js.zip](https://github.com/ging/licode/files/94581/nuveAuthenticator.js.zip)

**Comment by nachoaguadoc** [comment]
Hi,
Thank you very much, it's been fixed in 7ffc75408f3c7b92618c1762b3f9aaaa0473d714

BR
