### ISSUE TITLE
local video does not appear in basic example 

### ISSUE THREAD

**Issue by shaktsin** [ging/licode#403]
I'm trying to install licode in a cluster(amazon ubuntu boxes). The topology of cluster is as follow - 
box 1 - Nuve + mongodb + rabbitmq + basic examples 
box 2- ErizoController1
box3 -  ErizoController2

But the problem is, whenever I run basic examples test app, I'm not able to see local video. 
From logs, it seems that controllers are well integrated with the rabbitmq. 

here is the url for the reference - http://54.179.137.53:3001/connection_test.html

**Comment by nachoaguadoc** [comment]
Hi @shaktsin ,

I'm trying to access the url but I can't even load it, I keep getting the connection refused. Is the service down?

**Comment by shaktsin** [comment]
Please try again. Server was down at that time.

**Comment by nachoaguadoc** [comment]
Are you working on Chrome? Since last version of the web browser, you have to access via https, it won't work any other way. If that's the case, you have to activate the option in the licode_config.js file.

**Comment by mosfet1kg** [comment]
I think the url is not working.   if you want to test the url as insecure origin on mac os, try following command.
<code>sudo ./Google\ Chrome.app/Contents/MacOS/Google\ Chrome --unsafely-treat-insecure-origin-as-secure=http://.179.137.53:3001 --user-data-dir=/Users/ {user account} /Documents/profile</code>

**Comment by shaktsin** [comment]
Hi mosfet1kg , 

I fear that the url in your command was not correct. Although, service is up. I tried to open service in chrome with flag unsafely-treat-insecure-origin-as-secure on, but the result is same. 

@nachoaguadoc 

Yes I am working on Chrome. Can you please provide me some pointers to activate https option in licode_config.js?

**Comment by mosfet1kg** [comment]
I tried to test the url by using the cmd I said. But it is not working... Is it properly installed without errors?

**Comment by shaktsin** [comment]
Give it a try! 
sudo ./Google\ Chrome.app/Contents/MacOS/Google\ Chrome --unsafely-treat-insecure-origin-as-secure=http://54.179.137.53:3001 --user-data-dir=/Users/ {user account} /Documents/profile

I hope it is properly installed, as I don't see any error anywhere in the logs.

**Comment by mosfet1kg** [comment]
Compare the logs with following url

https://143.248.142.191:3001/

**Comment by shaktsin** [comment]
Thanks @nachoaguadoc and @mosfet1kg ! 
Issue was with https. I opened service with https, and got it working.
