### ISSUE TITLE
make Erize error

### ISSUE THREAD

**Issue by sciaz** [ging/licode#405]
I'm trying to install on Ubuntu 14.04 LTS 64bit.when i try  ./installErizo.sh,it came out like that:

Installing erizo...
-- Found glib-2.0: /usr/include/glib-2.0, /usr/lib/x86_64-linux-gnu/libglib-2.0.so;/usr/lib/x86_64-linux-gnu/libgobject-2.0.so;/usr/lib/x86_64-linux-gnu/libgthread-2.0.so
-- Boost version: 1.54.0
-- Found the following Boost libraries:
--   thread
--   regex
--   system
-- Configuring done
-- Generating done
-- Build files have been written to: /licode/erizo/build
Done
make[2]: *** No rule to make target `/usr/lib/libboost_thread-mt.so', needed by `erizo/liberizo.so'.  Stop.
make[1]: *** [erizo/CMakeFiles/erizo.dir/all] Error 2
make: *** [all] Error 2
Installing erizoAPI...
building with node-gyp
gyp info it worked if it ends with ok
gyp info using node-gyp@3.2.1
gyp info using node@0.10.37 | linux | x64
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/usr/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/licode/erizoAPI/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/root/.node-gyp/0.10.37/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/root/.node-gyp/0.10.37',
gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/licode/erizoAPI',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory `/licode/erizoAPI/build'
  CXX(target) Release/obj.target/addon/addon.o
  CXX(target) Release/obj.target/addon/WebRtcConnection.o
  CXX(target) Release/obj.target/addon/OneToManyProcessor.o
  CXX(target) Release/obj.target/addon/ExternalInput.o
  CXX(target) Release/obj.target/addon/ExternalOutput.o
  CXX(target) Release/obj.target/addon/OneToManyTranscoder.o
  SOLINK_MODULE(target) Release/obj.target/addon.node
/usr/bin/ld: cannot find -lerizo
collect2: error: ld returned 1 exit status
make: *** [Release/obj.target/addon.node] Error 1
make: Leaving directory `/licode/erizoAPI/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 3.19.0-25-generic
gyp ERR! command "node" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /licode/erizoAPI
gyp ERR! node -v v0.10.37
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok 
Installing erizoController...

I have tried the way in https://github.com/ging/licode/issues/34,it still doesn't work..

**Comment by prospdragon** [comment]
I've get same errors.

**Comment by cracker0dks** [comment]
installed with last commit and no error on ubuntu 14 today

**Comment by menelike** [comment]
I think this was fixed with https://github.com/ging/licode/commit/decf81fbc9f3c7ab50cce95c9d9fda9fb0bd4319

**Comment by ytjjyy** [comment]
@sciaz 

I've get same errors ,can you help me?

**Comment by sciaz** [comment]
@cracker0dks 's way can work~ @ytjjyy 
.also @menelike 's is ok.
and be sure your network is good.
sorry for pool En...
