### ISSUE TITLE
erizo.js and socket.io.js cannot work well together

### ISSUE THREAD

**Issue by deajosha** [ging/licode#407]
i compile the licode code and run the basiceExample very good by https.
then i copy the erizo.js from the ubuntu to the windows, and refer erizo.js in a node applications by https protol.

 i write the below code:
   <script src="javascripts/modules/erizo.js"></script>
   <script src="/socket.io/socket.io.js"></script> in a html page.

when it execute the Erizo.Room() function, it occur the problem below:
" Uncaught TypeError: Cannot set property 'eventListeners' of undefined"  in erizo.js: 93 

i check the problem for a long time, someone can help me?

**Comment by deajosha** [comment]
i compile the licode code and run the basiceExample very good by https.
then i copy the erizo.js from the ubuntu to the windows, and refer erizo.js in a node applications by https protol.

i refer the erizo.js and "/socket.io/socket.io.js"  in a html page.

when it execute the Erizo.Room() function, it occur the problem below:
" Uncaught TypeError: Cannot set property 'eventListeners' of undefined" in erizo.js: 93

i check the problem for a long time, someone can help me?

**Comment by mosfet1kg** [comment]
You should import socket.io.js ahead of bringing erizo.js.

```
<script src="/socket.io/socket.io.js"></script>
<script>
        var ioSafe = io,
           socket = ioSafe();
</script>
...
<script type="text/javascript" src="/erizo.js"></script>
```

Please refer to the following link
https://groups.google.com/forum/#!searchin/lynckia/ioSafe()/lynckia/I1ZPtzllNZo/kvghucUSCgAJ

**Comment by deajosha** [comment]
thanks i will try it.
