### ISSUE TITLE
nginx reverse proxy licode failed

### ISSUE THREAD

**Issue by deajosha** [ging/licode#417]
I change the licode_config.js as follows:
```
config.erizoController.port=8080;
config.erizoController.ssl=true;
config.erizoController.listen_ssl=true;
config.erizoContorller.listen_port=8080;
```

and I wirte an example via https, and can show the stream.

Now, I have writen an streamShow webserver via https, and move it to nginx for reverse proxy.
 when user click a button, then post a request like '/stream/show' to streamShow webserver, and then nginx forward the request to the example webserver by nginx reverse proxy, but it occure error in browser like below:
`GET https://xxx:8080/socket.io/1/?t=1457081831709 net::ERR_INSECURE_RESPONSE,  errizo.js:28.`
I think it should be the ssl problem for licode socket.io,  but i cannot solve the problem. if I donot call the licode stream module within example webserver, there is no error.

**Comment by menelike** [comment]
imho if you enable ssl in nginx you should not use ssl in `erizoController`. I think the ssl capabilities of erizo are only built for development reasons.

**Comment by deajosha** [comment]
licode must run via https, or will not show the stream.
