### ISSUE TITLE
Is it possible to have multiple servers

### ISSUE THREAD

**Issue by etamponi** [ging/licode#425]
Hi!

I am building a webconference application and I was wondering if licode can be configured to have multiple servers scattered around the world, as otherwise a centralized server would generate a sensible delay... I haven't found documentation on this regard. Is it possible right now?

Thanks in advance!

**Comment by cracker0dks** [comment]
yeah! Should be possible.
First distribute licode on multible server with one main server.
At the end you can change the user assignment from nuve (round-robin) to a location based one. (editing the policy) 

Thats it!

**Comment by etamponi** [comment]
Sounds easy, thanks :)

I am not sure on how to indicate the main server and where I can edit the policy, can you give me some additional hints?

I mean, once I deploy linode on multiple server, how do I tell them they are part of the same nuve "cluster"?

**Comment by cracker0dks** [comment]
Ok thats easy.

Install one standalone Licode Server (thats your main server).
Install a second (or more) server and set the hostIP in the licode_config.js to you main Server (you dont have to start RabbitMq and Nuve on the distributed Servers).

Now you have to take a look at the policy. Take a look at this [blogpost](http://lynckia.com/licode/ch-policies.html)

**Comment by etamponi** [comment]
It seems very easy!

Thanks a lot :) I'll try in the next days!

**Comment by cracker0dks** [comment]
the hard part is the new policy. Never done this... maybe someone else knows more about that part :)

**Comment by etamponi** [comment]
@cracker0dks I don't find any hostIP option in my config... Can you point out what option should I set exactly?

**Comment by cracker0dks** [comment]
after serverinstallation on your ditributed server you got a file "licode_config.js" in your .../licode folder. In that file you have to change:
`config.rabbit.host=mainServerIp`
I wrote that wrong sry. 
Than restart erizoController and erizoAngent on you distributed server.

**Comment by etamponi** [comment]
Thank you!

There is another thing that I didn't understand but it is not related to this question... I'll ask it here but if you want I can open another issue: in the client, how do you specify the signalling host? I only see a reference to the host to get the token, but subsequent calls to the Erizo object don't have references to the signalling host!

**Comment by cracker0dks** [comment]
I hope I got your question correct. If you take a look at the non minified erizo.js (you can build it non minified) you will find the connection from the client to the erizoController. For deep understanding you can have a look at my question: https://github.com/ging/licode/issues/335

**Comment by etamponi** [comment]
Ohhh so the erizo.js file is built using the config options that I have to set beforehand? Seems reasonable! And thanks for the link :)

**Comment by cracker0dks** [comment]
no its minifed by the installation (no config included) but you cant build it unminified. if you can read minified js you dont need to build it :D

**Comment by kekkokk** [comment]
the host ip is passed to the client thanks to the encrypted token. 
so, when a user request a token for a specified room, the request is passed to nuve which will route your request to the erizo_controller based on the policy you specify in default_policy. It takes the controller ip and encode it in the token sent to client.
next, the client makes a request at the ip specified in the token (which is the controller ip). the controller assign an agent based on its default_policy and pass the ip of the agent assigned to you in the sdp(i think?!).
more or less this will be the flow

**Comment by etamponi** [comment]
Thank you :)

I hope to have a chance to try this all in the next weeks :)

Emanuele

On Fri, Mar 18, 2016 at 10:12 AM, Francesco Durighetto <
notifications@github.com> wrote:

> the host ip is passed to the client thanks to the encrypted token.
> so, when a user request a token for a specified room, the request is
> passed to nuve which will route your request to the erizo_controller based
> on the policy you specify in default_policy. It takes the controller ip and
> encode it in the token sent to client.
> next, the client makes a request at the ip specified in the token (which
> is the controller ip). the controller assign an agent based on its
> default_policy and pass the ip of the agent assigned to you in the sdp(i
> think?!).
> more or less this will be the flow
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ging/licode/issues/425#issuecomment-198267821>
>



-- 
Emanuele Tamponi

PhD in Electronic and Computer Engineering

Postdoc at IASC Group, DIEE.
University of Cagliari, Italy.

Software Engineer at Fog Creek Software.
55th Broadway, New York City, US.
