### ISSUE TITLE
Firefox not working on none lan server (Basic example)

### ISSUE THREAD

**Issue by cracker0dks** [ging/licode#426]
I cant figur out why firefox is not working on the last commit (Basic example).
It works on chrome and on firefox if the server is in the same network (lan).

Online only chrome is working and firefox not. (but firefox console log is the same as on lan)

tested on 3 different servers and 2 different pcs with last firefox and licode version.

Can anyone confirme this?
How can I debug this if the console log is the same?

Thanks :)

**Comment by prospdragon** [comment]
I get same issue.
In my case, It worked on Firefox 44, but not working on 45.(of course, it works on chrome.)
In console of firefox, it shows "ICE failed, see about:webrtc for more details"

Is this issue occur only for me, or anyone ?

**Comment by cracker0dks** [comment]
Ok thanks! should be for everyone. Tested this on different pcs with latest firefox and on Firefox nightly.

**Comment by prospdragon** [comment]
I fixed this problem.
In my case, it was problem of turn server.
I did re-config of turn server, and licode works well in firefox too.

**Comment by cracker0dks** [comment]
wow. What do you mean by re-config ? change the IP ?

**Comment by prospdragon** [comment]
Changed the config of turn server.

**Comment by cracker0dks** [comment]
mmm I use the default turn server (google) maybe I have to switch or just wait? What Turn server do you use?

**Comment by prospdragon** [comment]
I'm using rfc5766-turn-server.

**Comment by cracker0dks** [comment]
I tested with and without TURN Server but both not working for me. about:webrtc logs for not working external server on firefox:
![image](https://cloud.githubusercontent.com/assets/1816621/14214102/75364c6a-f83b-11e5-9c09-6483d87a8c07.png)

Log for local Server:
![image](https://cloud.githubusercontent.com/assets/1816621/14214168/ca83201c-f83b-11e5-8120-d23e8cc7a3ce.png)

I got one entry more but no fails... but still no connection. This is the basicExample.

**Comment by cracker0dks** [comment]
Ok I figuered out how I can connect to online server with firefox:
1. Connect to a room
2. Wait until: `DEBUG:  Gathered all candidates for this pc` pops up in the console (about 7sec)
3. Connect to the same room again
This works for me 90% of the time. Is this maybe a Firefoxbug ?

**Comment by cracker0dks** [comment]
![image](https://cloud.githubusercontent.com/assets/1816621/14605833/c0f103d8-057a-11e6-9d03-14bb015ef623.png)

Who is using Firefox with that bug? :D

Its still buggy with the last Commit.

Here is the Server log for firefox: 

```
2016-04-18 13:30:14.156  - INFO: RoomController - Adding publisher peer_id  283343756105750800 options { state: 'erizo',
  data: true,
  audio: true,
  video: true,
  minVideoBW: 0 }
2016-04-18 13:30:14.156  - INFO: ECCH - Contacting Agent  ErizoAgent  for a new ErizoJS
2016-04-18 13:30:14.157  - INFO: ErizoAgent - Get erizo JS ba07336c-0330-a560-4d5a-fdaf5d4980e3
2016-04-18 13:30:14.159  - DEBUG: RoomController - ErizoJS id: ba07336c-0330-a560-4d5a-fdaf5d4980e3 assigned for publisher 283343756105750800
2016-04-18 13:30:24.364  - WARN: RoomController - ErizoJS 29a4f9a7-dbab-8dcf-e7dc-c8ff32e9b644 is empty and does not respond, removing
```

**Comment by cracker0dks** [comment]
Ok with the new FF46 its working on win again (at least win10)
Ubuntu FF still buggy

**Comment by mccob** [comment]
Over month, I see WebRTC calls failures increasing with Firefox...

**Comment by cracker0dks** [comment]
FF 46.0.1 on windows is buggy again... what is mozilla doing :(

**Comment by mccob** [comment]
No problem here with FF 46.0.1 on windows

**Comment by cracker0dks** [comment]
have you tested on none lan ?

**Comment by mccob** [comment]
yes over Internet

**Comment by cracker0dks** [comment]
ok thanks! That give me hope. with or without TURN server?

**Comment by mccob** [comment]
with TURN

**Comment by cracker0dks** [comment]
ok, have to try this! thanks :)

**Comment by cracker0dks** [comment]
TURN not solved this..

Long story short: It is a firefox port problem!

Long story: My firewall only allowed ports:80, 443, 8080 and  30000-30100/UDP I also set MINPORT=30000 and MAXPORT=30100 at the licode_config, but Firefox will not work with this settings (no problem for chrome). 

This was not a problem a few firefox versions back -> might be a Firefox bug?! 

Here is a work around:
Firefox tries to connect to port 1025 - 65535/UDP for WebRTC. And it seems that Firefox starts at 1025 and stops if it can't connect?!. So if you start at open port 1025 and go to port 1125 everything is working with Firefox.

The best way (for no limits) is to open port: 1025-65535/UDP -> for firefox

@prospdragon & @mccob thanks for your help :+1:
