### ISSUE TITLE
licode support h264 ?

### ISSUE THREAD

**Issue by notedit** [ging/licode#429]
as i know  Chrome M50 has supported h264,   when will licode support that?

**Comment by mccob** [comment]
licode doesn't support h264 ? I think licode already support h264

see http://lynckia.com/licode/client-api.html

**Comment by notedit** [comment]
i do not see any  h264 code in this repo

**Comment by mccob** [comment]
I see multiple response when I search h264 in this repo

**Comment by jnoring** [comment]
It does not currently support h.264.  That'd be a great feature to add though, since I think there are inklings that MSFT and Apple will add webrtc support, but my guess is it'll be h.264

**Comment by lodoyun** [comment]
We currently don't support h.264 in the browser. 
There's nothing preventing us from supporting both h.264 and VP9 and will do in the near future

**Comment by mccob** [comment]
wow very good news ! thank you !

**Comment by miniruwan** [comment]
Now that Safari 11 is released and Safari 11 only supports H264, is there any timeline on implementing H264 in licode?
Similar discussion here : https://github.com/lynckia/licode/issues/915

**Comment by mkhahani** [comment]
I am also curious to know when support for Safari would be added, and if it is far then I have to think of an iOS app.
IMO a project road map would be very helpful.

**Comment by jcague** [comment]
We'll add support to Safari in the next weeks, it's definitively in our roadmap. These are the tasks to 
- h264 is not fully support in Licode. We still need to make slideshow compatible (work in progress), propagate fmtp lines (and possibly other info) from publisher to subscriber's SDP
- we want to make video/audio codecs configurable per room.
- Adapterjs does not currently support all safari features. This [Pull Request](https://github.com/webrtc/adapter/pull/676) has recently improve things a lot, but we need to investigate other cases too.

**Comment by menelike** [comment]
I've been waiting for this feature for 2 years now, your post made my day, what a relief.

**Comment by mkhahani** [comment]
Great!
Does Simulcast is compatible with h264?

**Comment by jcague** [comment]
there isn't a simulcast option for h264 in Google's webrtc library yet. There's an open PR, but it seems like it's stuck at some point: https://chromium-review.googlesource.com/c/external/webrtc/+/514351

**Comment by mkhahani** [comment]
Too bad :(

**Comment by jcague** [comment]
I've found really hard issues that prevent Safari to work in all cases. it seems like it is still buggy and we can't provide a solution that would be production ready yet. Anyway, we'll update adapterjs, which improves support to Safari, and we'll be able to do some demo with it ;)
