### ISSUE TITLE
Is erizo tree working?

### ISSUE THREAD

**Issue by mosfet1kg** [ging/licode#430]
I am interested in the platform that can accommodate a lot of clients.

 Because of bandwidth limitation, It is difficult for me to make e-learning system where many students subscribe a teacher's stream.

As far as I know, there is a prototype function titled "shouldAddSurrogate" regarding erizo tree at https://github.com/ging/licode/blob/master/erizo_controller/erizoController/roomController.js.

So I'm curious about whether its function works or not.

**Comment by lodoyun** [comment]
It works, or should work, but its a prototype at best.
We're still figuring out how to offer that functionality in Licode from the ErizoClient/Nuve perspective. Right now it's not a priority but we'll revisit it at some point

**Comment by mosfet1kg** [comment]
@lodoyun 

I found erizo tree for stream relay between erizos is working from commit cf8c8aa992c3d974d7975338142fdc9236f643b4.

Thank you for your work.
