### ISSUE TITLE
Chrome audio not working when screensharing is enabled

### ISSUE THREAD

**Issue by cracker0dks** [ging/licode#431]
You can test it on licode example page: https://chotis2.dit.upm.es/room?id=56bb47f4c61d88361edb4dcb
The other example: video and screenshare is working on chrome.

The problem is this configuration: `room.subscribe(stream, {audio:true, video: true});`
If you turn video to false, audio is working again, but screensharing is disabled.

Does anyone knows a workaround?

**Comment by cracker0dks** [comment]
found out, that this only a problem on old src code (example must be old code aswell). with the last commit this is not a problem anymore.

**Comment by angrybrd** [comment]
I am still facing this issue in Chrome. Here is my setting to share the audio with screen sharing -

In the extension script -

chrome.desktopCapture.chooseDesktopMedia(
                ["screen", "tab", "audio"], sender.tab,
                function(streamId) {
                    sendResponse({ streamId: streamId});
                });

----------------------------------
Allowed audio access in the Manifest

"permissions": [
        "desktopCapture",
        "audioCapture",
        "audio"
    ], 

On screen sharing selection, the browser is giving an option for audio share check box and also on the stream subscribe end screen/audio is enable, but can't hear anything. The stream is passing with only the screen but no audio.

Am I missing anything in the erizo controller or agent?

**Comment by lan143** [comment]
I solved this problem by making a separate stream for audio. Example: http://paste2.org/OGHHC4p9
