### ISSUE TITLE
make Erize error In CentOS 7.0

### ISSUE THREAD

**Issue by ytjjyy** [ging/licode#436]
Can you help me?

[root@10 pkg]# ./licode/scripts/installErizo.sh
Installing erizo...
-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE) 
-- checking for module 'glib-2.0'
--   package 'glib-2.0' not found
CMake Error at /extra_disk/pkg/licode/erizo/cmake/FindGlib.cmake:36 (message):
  pkg-config is needed
Call Stack (most recent call first):
  erizo/CMakeLists.txt:29 (find_package)

-- Configuring incomplete, errors occurred!
Done
make: *** No targets specified and no makefile found.  Stop.
Installing erizoAPI...
building with node-gyp
gyp info it worked if it ends with ok
gyp info using node-gyp@0.10.6
gyp info using node@0.10.42 | linux | x64
gyp info spawn python
gyp info spawn args [ '/usr/bin/gyp',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/extra_disk/pkg/licode/erizoAPI/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/lib/node_modules/node-gyp/addon-rpm.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/share/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/usr/share/node',
gyp info spawn args   '-Dmodule_root_dir=/extra_disk/pkg/licode/erizoAPI',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
make: Entering directory `/extra_disk/pkg/licode/erizoAPI/build'
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/addon/addon.o
  CXX(target) Release/obj.target/addon/WebRtcConnection.o
  CXX(target) Release/obj.target/addon/OneToManyProcessor.o
  CXX(target) Release/obj.target/addon/ExternalInput.o
  CXX(target) Release/obj.target/addon/ExternalOutput.o
  CXX(target) Release/obj.target/addon/OneToManyTranscoder.o
  SOLINK_MODULE(target) Release/obj.target/addon.node
/usr/bin/ld: cannot find -lerizo
collect2: error: ld returned 1 exit status
make: *** [Release/obj.target/addon.node] Error 1
make: Leaving directory `/extra_disk/pkg/licode/erizoAPI/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 3.10.0-327.13.1.el7.x86_64
gyp ERR! command "node" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /extra_disk/pkg/licode/erizoAPI
gyp ERR! node -v v0.10.42
gyp ERR! node-gyp -v v0.10.6
gyp ERR! not ok 
Installing erizoController...
[erizo_controller] Installing node_modules for erizo_controller

**Comment by lodoyun** [comment]
Looks like the dependencies were not installed properly.
We don't officially support CentOS. I would advise using [docker](https://hub.docker.com/r/lynckia/licode/) if that's an option for you

**Comment by ytjjyy** [comment]
@lodoyun 
Thanks for your help,i have solved the problem.

Please attention:
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
-- checking for module 'glib-2.0'
-- package 'glib-2.0' not found

Exec command : yum install libgnomeui-devel

Then ./licode/scripts/installErizo.sh,it works fine.
