### ISSUE TITLE
The Sample Page Has an Error

### ISSUE THREAD

**Issue by yuanxing008** [ging/licode#439]
FIREBUG:
17:42:04.562 ERROR:  Not Connected! Error: Cannot connect to ErizoController (socket.io error)1 erizo.js:169:1
17:42:04.563 DEBUG:  Event: room-error1 erizo.js:169:1

and it just has one camera view in the page.Could you Help me?
Thanks!

**Comment by nachoaguadoc** [comment]
Hi @yuanxing008, we had a problem with our servers, but it's solved by now. Thanks!
