### ISSUE TITLE
Sound not working with new Chrome version and some OS

### ISSUE THREAD

**Issue by Vidmeet1** [ging/licode#440]
With the latest update of Chrome to Version 50.0.2661.87 m (64-bit) some of the Erizo audioplayer seem to fail. I tried Audio Room 2 example. Worked fine with Chrome 48.x
Now I tried several OS. Window 10 to Windows 7 or Ubuntu Linux 15.10 have the same result.
The sound transmitted from Win10 to the other system is played. The oposite way not. The streams seem to be transmitted correctly and also the Url is put into the audioplayer. But no sound is played on the Win10 system. 
Also a test between two ubuntu clients fails. No sound on either side. It does make no sence, since the sound from the Win10 system is transmitted and played the sound a the ubuntu system or Win 7 system is transmitted, but not played. Very strange! Any Idea? Can you reconstruct the problem?

**Comment by cracker0dks** [comment]
nop can not reconstruct. 

I tested on Win10
Chrome50 <--> chrome50
Firefox46 <--> chrome50
Firefox46 <--> Firefox46

Working for me. More tests inc on friday

**Comment by cracker0dks** [comment]
Ok more tests:

Tested on Ubuntu15

chromium49 <--> chromium49 --> Working
Firefox46 <--> chromium49 --> Not Working
Firefox46 <--> Firefox46 --> Not Working

But I think this is a firefox bug -> https://github.com/ging/licode/issues/426

**Comment by Vidmeet1** [comment]
I use Chrome on both systems. Ubuntu and Windows.  I will test again on Monday and give further feedback. 


Von meinem Samsung Gerät gesendet.

-------- Ursprüngliche Nachricht --------
Von: Cracker <notifications@github.com> 
Datum: 29.04.2016  18:33  (GMT+01:00) 
An: ging/licode <licode@noreply.github.com> 
Cc: Vidmeet1 <Matthias.Baumgart@onlinehome.de>, Author <author@noreply.github.com> 
Betreff: Re: [ging/licode] Sound not working with new Chrome version and some
  OS (#440) 

Ok more tests:

Tested on Ubuntu15

chromium49 <--> chromium49 --> Working

Firefox46 <--> chromium49 --> Not Working

Firefox46 <--> Firefox46 --> Not Working

But I think this is a firefox bug -> #426

**Comment by Vidmeet1** [comment]
Hi i found out the problem. It is not related to Erizo. The point is that if you have multiple audio output devices it happens that the output device changes, when a mediastream is assigned as source to an audio tag. I could not find out why or to which device (it was not the standard device nor the standard communication device).
In my case I had not attached speakers to the device that was why I could not hear anything.
After reassigning the correct audio device after the mediastream assignment everything worked fine.
Issue can be closed. Thank you for your time investment.

Best regards!

**Comment by cracker0dks** [comment]
I had the same Problem on one of my users yesterday. 
You can set the audio output device on the clientsite with javascript to default: https://webrtc.github.io/samples/src/content/devices/multi/
