### ISSUE TITLE
The iphone client access does not support ??

### ISSUE THREAD

**Issue by domininia** [ging/licode#441]
I have installed Licode on My ubuntu 12.04 according to the Installation of Licode,I have problems when I try to open the url with my iphone,but what i can see is a blank page,
so I want to know does iphone support??

**Comment by menelike** [comment]
IOS has no webRTC support by default. This won't work without huge additional efforts.

**Comment by zevarito** [comment]
@domininia If you want to interop between Licode-IOS(native) you can try https://github.com/zevarito/Licode-ErizoClientIOS

**Comment by lodoyun** [comment]
@zevarito's client is your best bet for that, it's the closest to an "official"  Licode iOS client.
