### ISSUE TITLE
Stream-data event can't trigger

### ISSUE THREAD

**Issue by ytjjyy** [ging/licode#448]
......
     room = Erizo.Room({token: token});
    localStream.addEventListener("stream-data", function(evt){
    	console.log(evt.msg.text);// can't work;
    });

    localStream.addEventListener("access-accepted", function ()
    {....});

I have received DEBUG:  Event: stream-data info from Chrome.
![1111](https://cloud.githubusercontent.com/assets/12911640/15119678/a2688064-1644-11e6-8ae7-cda1911e79da.png)

But can't trigger stream-data.

Can you help me

**Comment by lodoyun** [comment]
You won't receive streamEvents if you have not subscribed to the stream (and you probably will not want subscribe to a localStream).
Follow the licode [API](http://lynckia.com/licode/client-api.html) to subscribe to a remote data stream and then you can add the "stream-data" event listener there

**Comment by ytjjyy** [comment]
@lodoyun  Thanks for you advice:)

**Comment by YashonNice** [comment]
@ytjjyy  Hello, I have this problem, can you help me
