### ISSUE TITLE
Core dumped on stream-removed

### ISSUE THREAD

**Issue by softforge** [ging/licode#450]
I have Licode running and recording streams on OSX 10.11.4 with NodeJS v0.10.44. I suddenly ran out of disk space and discovered that I had 225G of core dumps in /cores/core.*

It turns out that when running basicServer.js, every time I refresh the page it produces a 1.3G core dump file in /cores/ and an associated crash report like this:

[node_2016-05-10-151818_Joes-MacBook-Pro.crash](https://github.com/ging/licode/files/257398/node_2016-05-10-151818_Joes-MacBook-Pro.crash.txt)

These crash reports appear in `~/Library/Logs/DiagnosticReports/` and you can watch the core dumps being produced like this:

    cd /cores; watch -n 0.1 ls -lh

Any idea how to stop this happening?

Many thanks

**Comment by lodoyun** [comment]
I've found the root of this issue but I cannot merge it into master right now.
It should only happen when erizoJS closes when it has no more publishers, removing streams while there are more publishers should be fine. 
Will keep you posted, in the meantime, you can always disable core files.

**Comment by softforge** [comment]
Thanks for looking into this. You are right, I can confirm that it only crashes when the last publisher exists the room.

I will disable core files for now.

**Comment by lodoyun** [comment]
Should be fixed in 745027793cfd5bcb88f917655c28db2629e9e347 
Please try it and reopen if that didn't solve the problem for you
