### ISSUE TITLE
update openSSL url for ubuntu unattended install

### ISSUE THREAD

**Issue by menelike** [ging/licode#453]
Docker builds stopped working because of an old openSSL url, this has been fixed for casual ubuntu installs, but https://github.com/ging/licode/commit/faad44399ddca7aaaecc544ea57be6dbba10ccbf missed [this part](https://github.com/ging/licode/blob/745027793cfd5bcb88f917655c28db2629e9e347/scripts/installUbuntuDepsUnattended.sh#l61)

**Comment by cracker0dks** [comment]
Dont know why, but you can also fix this by: `apt-get update && apt-get upgrade -y` at the start of the docker file (before "apt-get install git"). :)
like this: https://hub.docker.com/r/rofl256/licodebasic/~/dockerfile/

**Comment by menelike** [comment]
@cracker0dks I'm afraid that this doesn't solve the general problem.

This is confusing anyway, reading https://github.com/ging/licode/commit/faad44399ddca7aaaecc544ea57be6dbba10ccbf I taught that the URL has been updated and the old one is invalid. I just checked both URLs and both work.

As the sources should be kept consistent I advise to stick with one URL.

**Comment by cracker0dks** [comment]
I think the problem is not the link. Its the (a new?) Ubuntu image on docker hub. If you dont "apt-get update" the "apt-get install git" crashes because git is not known at the package list.

**Comment by lodoyun** [comment]
Fixed it. Sorry for the delay, I feel like I've updated this 20 times
