### ISSUE TITLE
he Basic Example can't execute！

### ISSUE THREAD

**Issue by liushengkai** [ging/licode#454]
Now you can connect to "localhost:3001" and test your basic videoconference example!
![image](https://cloud.githubusercontent.com/assets/853500/15279442/012e15fc-1b57-11e6-8ce9-982de4151e1e.png)

**Comment by mkhahani** [comment]
It's Google Chrome warning that prevents accessing user's media (mic/webcam) on none secure (HTTP) origins except for localhost. But you can test on Firefox.

**Comment by cracker0dks** [comment]
if you want to use chrome, you have to enable https in the licode_config.js, restart licode and connect to https://localhost:3004

**Comment by nachoaguadoc** [comment]
As @mkhahani said, this is a Chrome related problem, due to their change of policy regarding getUserMedia(). The solution is the one @cracker0dks suggests. Can you make it work that way?

**Comment by liushengkai** [comment]
thank you very much！

**Comment by liushengkai** [comment]
thank you very much！
