### ISSUE TITLE
Loop: "Launched new ErizoJS" on CentOS release 6.7 (Final)

### ISSUE THREAD

**Issue by nionis** [ging/licode#455]
Hi guys, I have used licode on ubuntu and it worked fine however when I build it in cent os 6 and run initLicode.sh I get in a loop:

`
2016-05-16 15:21:23.584  - INFO: ErizoAgent - Launched new ErizoJS  4bc8e470-9a58-5ba8-2bd9-b03ea96a95dc
`
`
2016-05-16 15:21:23.678  - INFO: ErizoAgent - ErizoJS 4bc8e470-9a58-5ba8-2bd9-b03ea96a95dc has closed
`
`
2016-05-16 15:21:23.678  - INFO: ErizoAgent - Launching a new ErizoJS process
`
`
2016-05-16 15:21:23.681  - INFO: ErizoAgent - Launched new ErizoJS  343a0ff1-6120-e2d0-b483-445bf84d582c
`

One package that is missing is log4cxx-devel but I don't know where its cause of the issue.

--

(update)
Seems like the issue happens when I build Erizo

`-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE)
-- checking for module 'glib-2.0'
--   package 'glib-2.0' not found
CMake Error at /home/gamingforgood/licode/erizo/cmake/FindGlib.cmake:36 (message):
  pkg-config is needed
Call Stack (most recent call first):
  erizo/CMakeLists.txt:29 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/gamingforgood/licode/erizo/build/CMakeFiles/CMakeOutput.log".
Done
make: *** No targets specified and no makefile found.  Stop.`

--

(update)
Managed to install glib-2.0 but the issue remains, log:
`
CXX(target) Release/obj.target/addon/addon.o
In file included from /home/gamingforgood/licode/scripts/./../erizo/src/erizo/WebRtcConnection.h:9,
                 from ../WebRtcConnection.h:5,
                 from ../addon.cc:5:
/home/gamingforgood/licode/scripts/./../erizo/src/erizo/logger.h:25:28: warning: log4cxx/logger.h: No such file or directory
/home/gamingforgood/licode/scripts/./../erizo/src/erizo/logger.h:26:39: warning: log4cxx/helpers/exception.h: No such file or directory
In file included from /home/gamingforgood/licode/scripts/./../erizo/src/erizo/WebRtcConnection.h:10,
                 from ../WebRtcConnection.h:5,
                 from ../addon.cc:5:
`

Apparently log4cxx is the issue, but it seems impossible to find it and install it

**Comment by mkhahani** [comment]
Recently I did installed Licode on my CentOS 7 without any problem. But installation on CentOS 6 failed. I don't remember the error but it happened when compiling libvpx.

**Comment by nionis** [comment]
Seems some dependencies are not available on yum, and you I needed to build them manually, I switched to ubuntu.
