### ISSUE TITLE
how to disable the packet loss feedback mechanism

### ISSUE THREAD

**Issue by xiliu** [ging/licode#456]
hi all 
    i want to disable the  packet loss feedback mechanism because i found worst subscriber connection causes the publisher lower his send video bandwidth. in other words, one of subscribers have worst connection causes all subscribers get worst video stream quality from publisher.

 i had try three way as follows ,However, it seems not work.

1.add removeREMB function as [Sergio](https://groups.google.com/forum/#!topic/lynckia/vZdirnQ3kdQ) say ,and remove other rtcp-fb in sdp.
2. commented `wrtc.setFeedbackReports()` in the file erizoJSController.js at server.
3.commented  `sdp << "a=rtcp-fb:" << payloadType << " " << rtp.feedbackTypes[itFb] << "\n";` in the file Sdpinfo.cpp at server.

Any idea how to disable feedback mechanism?

Many thanks

**Comment by lodoyun** [comment]
Take a look at the "Managing Quality Adaptation" of the licode [client API](http://lynckia.com/licode/client-api.html)
