### ISSUE TITLE
Can I forcibly set Remote stream bandwidth?

### ISSUE THREAD

**Issue by mosfet1kg** [ging/licode#461]
Even if I forcibly set a bitrate for a stream from the side of a publisher, all bitrate of subscribers who receive its stream can decrease when a client joins with bad network such as 3G, narrow band and etc.

Because of QoE guarantee for all subscribers,  the publisher's bitrate automatically adapts to the lowest subscriber bandwidth among the clients. Therefore, It is possible for many subscribers to suffer from performance degradation because of a subscriber who has bad network.

so Is there anyway to give a low bit rate stream to a user who has bad network without performance degradation which can be occurred to the others?

**Comment by lodoyun** [comment]
We've updated the [client API page](http://lynckia.com/licode/client-api.html) with some tips on how to do this.
The simplest option you have is that you can set a minimum BW per publisher and subscribers will get events when they are reporting less.
