### ISSUE TITLE
Black screen on video playback

### ISSUE THREAD

**Issue by ytjjyy** [ging/licode#466]
Hi,

After the normal video recording(.mkv), when it was tried to play, only the black screen and loader.
The mkv file works fine with vlc. 

Chrome Version 51.0.2704.63 (64-bit)

<img width="323" alt="68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f313633333831382f313632303133392f33663866303266652d353636642d313165332d396364632d3039373563313063366435622e706e67 2" src="https://cloud.githubusercontent.com/assets/12911640/15718080/4310bc9c-285c-11e6-8dfa-bb15abdc4ae3.png">

Can you give some advice.
Thank very much.

**Comment by ytjjyy** [comment]
@cracker0dks  
Hi friend,I miss you terribly!
have you had any progress for the problem?

**Comment by cracker0dks** [comment]
Hey, had no time so far to check this. But maybe its the same scale problem as you mention at: https://github.com/ging/licode/issues/464 ?

**Comment by lodoyun** [comment]
Check chrome://webrtc-internals and see if you are actually receiving any data.
Try reencoding the video. That looks like no keyframes reach the subscriber and it's not able to decode it.
