### ISSUE TITLE
Restart Licode

### ISSUE THREAD

**Issue by nionis** [ging/licode#467]
I couldn't find any documentation on how to restart licode as a whole, I know there are multiple services running, if there is not a method implemented what services will I need to terminate and relaunch to effectively have a restart ?

**Comment by lodoyun** [comment]
With initLicode you are running: nuve, erizoController, erizoAgent (+ ErizoJS instances) plus MongoDB and rabbitMQ.
All of them are node applications. In dev environments it's usually safe to do ``killall node`` and just initLicode again, just make sure you don't have any other node apps running

**Comment by nionis** [comment]
thanks
