### ISSUE TITLE
"./licode/scripts/initLicode.sh" keep on running

### ISSUE THREAD

**Issue by nasr18** [ging/licode#483]
after executing the above command in terminal, its not keep on running. how do i restart "basicExample" app.

![screenshot from 2016-06-21 14 46 51](https://cloud.githubusercontent.com/assets/7514936/16224295/0b223b7c-37bf-11e6-8075-a7a9ffeece98.png)

**Comment by michaelluk** [comment]
Check out:
#467 - how to restart licode
and
#449 - how to solve this error

**Comment by nasr18** [comment]
how do i uninstall this `installErizo.sh", i mean uninstall and reinstall. @michaelluk

**Comment by michaelluk** [comment]
I don't think you need to "uninstall" `installErizo.sh`. Just simply run the script again to compile the project. If you really want to clean it, I think you can just delete `erizo/build`

**Comment by nasr18** [comment]
ok wait. let me do it.

**Comment by nasr18** [comment]
actually i'm using Linux Mint 17.3. but i tried "installLinuxDependencies.sh" instead of "installUbuntuDeps.sh". will this cause any damage???

**Comment by nasr18** [comment]
while reinstalling `installErizo.sh` i'm getting this error...

![screenshot from 2016-06-21 15 23 22](https://cloud.githubusercontent.com/assets/7514936/16225472/51c43454-37c4-11e6-8cb8-e3e51c8f6468.png)

**Comment by michaelluk** [comment]
@nasr18 Seems like your log4cxx is missing. You better confirm that there is no error with your dependencies installation. Run `installLinuxDependencies.sh` again.

**Comment by nasr18** [comment]
go with `installUbuntuDeps.sh` or `installLinuxDependencies.sh`??

**Comment by nasr18** [comment]
again same result. keep on running.

**Comment by lodoyun** [comment]
What OS are you running this in? Ubuntu?
You should try installUbuntuDeps.sh and make sure there are no errors. Then at least run installErizo.sh, if there are any errors you can post them here. In your last screenshot, log4cxx was missing so I would make sure that it is being installed. If you install it successfully, you'll have to run installErizo.sh again for erizo to be compiled successfully.
