### ISSUE TITLE
BasicExample not working. Can't able to get subcriber video.

### ISSUE THREAD

**Issue by nasr18** [ging/licode#485]
while running basicExample only local video is displaying. Remote video not displaying. getting following error in console.

![screenshot from 2016-06-22 13 38 29](https://cloud.githubusercontent.com/assets/7514936/16259155/edb55950-387e-11e6-87ff-673c584ab000.png)

**Comment by lodoyun** [comment]
Did you get pass #483 ? If erizoJS is not running there is no point in trying the basicExample. You should solve that first and then this will work :)

**Comment by amanuel2** [comment]
Hello @nasr18

**Comment by nasr18** [comment]
i did whatever i have to do. but no success.
