### ISSUE TITLE
No Audio play in ExternalInput Video file(with Audio)

### ISSUE THREAD

**Issue by fanchuanster** [ging/licode#487]
Hi ,
Based on basic sample, I added an ExternalInput video - file:///workarea/myvideo.mov(H264&AAC)
The video plays well in FireFox, but no audio.
I checked into the licode source, found audio not implemented, because the video [needs transcoding](https://github.com/ging/licode/blob/e4058594ea84f65b3d13570ce576c684c290073d/erizo/src/erizo/media/ExternalInput.cpp#L181)
so I changed the code to make audio work:
1. transcoded AAC to PCM U8 (transcoded successfully, because saved in .wav file audio plays well)
2. send the PCM U8 data to browser video
No luck. (send AAC directly to browser video, does not work neither.)

Here is the PCM U8 RTP packet received:
Frame 400: 632 bytes on wire (5056 bits), 632 bytes captured (5056 bits) on interface 0
Ethernet II, Src: CadmusCo_15:77:96 (08:00:27:15:77:96), Dst: IntelCor_cb:c6:7c (24:77:03:cb:c6:7c)
Internet Protocol Version 4, Src: 192.168.1.107, Dst: 192.168.1.102
User Datagram Protocol, Src Port: 40972 (40972), Dst Port: 52944 (52944)
Real-Time Transport Protocol
    10.. .... = Version: RFC 1889 Version (2)
    ..0. .... = Padding: False
    ...0 .... = Extension: False
    .... 0000 = Contributing source identifiers count: 0
    0... .... = Marker: False
    Payload type: ITU-T G.711 PCMU (0)
    Sequence number: 140
    Timestamp: 6768
    Synchronization Source identifier: 0x0000ad9c (44444)
    Payload: 01f16cecb33ec1bfde82891fd1594c5ae57f7ce65494d39d...

Appreciate it if any suggestion!!!

**Comment by fanchuanster** [comment]
@cracker0dks
can you share any suggestion?

**Comment by cracker0dks** [comment]
I can't try this at the moment. (next week I think I have time) 
Have you checked VP8+OPUS oder VP8+PCMU8 because this is what should work for files.
H.264 is for a RTSP scource accordingly to the [doc](http://lynckia.com/licode/client-api.html#stream) and I dont know if H.264 works for files as well.

**Comment by fanchuanster** [comment]
Thanks @cracker0dks for your prompt reply!
since the [needTranscoding_](https://github.com/ging/licode/blob/e4058594ea84f65b3d13570ce576c684c290073d/erizo/src/erizo/media/ExternalInput.cpp#L181) is true, currently in licode ExternalInput audio actually not implemented.
So I transcoded the audio in the Video file, from AAC to PCMU8, not work. The Video transcoded to VP8 which works well. 
When will be implemented the audio in an ExternalInput Video?

**Comment by fanchuanster** [comment]
" currently in licode ExternalInput audio", I mean audio in  ExternalInput Video.

**Comment by fanchuanster** [comment]
Audio played, after:
split the audio packet into small pices, like 20ms, for in SDP constraints is payload in a UDP should not exceed 60ms.
Note, the timestap is of audio time base(for audio), not wallclock timebase. since read from a audio file, then no need to rescale because it is already audio time base.
Interesting, 20ms should be of size 160bytes( (8000 bytes per second / 1000 ) * 20ms), but actual received payload is 160 + 10 bytes, where is the extra 10 bytes from?
