### ISSUE TITLE
 ICE Connection Failed on publishing stream

### ISSUE THREAD

**Issue by ytjjyy** [ging/licode#488]
Hi all
```
ERROR:  ICE Connection Failed on publishing stream 570608127862215040
INFO:  Gathered all candidates.
WARNING:  Stream 570608127862215040 has failed after succesfuly ICE checks
DEBUG:  Event: stream-failed
Stream Failed, act accordingly
WARNING:  Received a removeStream for 570608127862215040 and it has not been registered here, ignoring.
INFO:  Stream unpublished
```
How can i solve this problem, can you help me?

**Comment by mkhahani** [comment]
It's just like the issue #482 and not fixed yet.

**Comment by ytjjyy** [comment]
Oh...No!!!

**Comment by ytjjyy** [comment]
@cracker0dks Come here ,i need you help.

**Comment by lodoyun** [comment]
@mkhahani  not all ICE fails are related to #482 
Particularly, this is probably different because the connection is established and at some point, Chrome marks it as a failed connection.
@ytjjyy can you elaborate on the specifics of the problem? What's the network scenario of the connection?

**Comment by cracker0dks** [comment]
got no problems with the last commit.
Tested Audio/Video: 
Chrome <-> Chrome
Chrome <-> Firefox
Firefox <-> Firefox
Tested local, lan and online
can you test your connection with the basic example?

**Comment by ytjjyy** [comment]
I'm so sorry. I was careless.
I closed firewall,it works well.
Thanks for everyone!

**Comment by mkhahani** [comment]
@ytjjyy Did you stopped the firewall permanently? If no then what rules did you add to resolve the issue?

**Comment by hedgerh** [comment]
Hey all, just got licode up and running on OSX 10.11.6, and I'm having this issue when opening the basic example in Chrome 53, but no problems at all in Firefox 49.  Running the server locally.  Firewall is turned off.  Any idea what may be causing an issue in Chrome?
