### ISSUE TITLE
install script for centos and others

### ISSUE THREAD

**Issue by xxxman2008** [ging/licode#489]
Hi, all

    after 3 days working,  i give up  install Licode on Centos6.x  . Now ,i just try to install a new Ubuntu Server for testing.

    some country FW  forbbiden  google.com , i.e ..china fw .  Plz kindly replace libvpx download url  by  git addres (https://github.com/webmproject/libvpx.git) .

    i wish ,in the future .a  wonderful  ,handsome man ,will write a 100% working script  for  centos.  please be informed ,  node.js 4.x require gcc4.8+  and ld.gold,   mongodb install from yum require  additional information.

**Comment by ytjjyy** [comment]
Hi,boy

I have success install licode in Centos 7,I can share you my experience

**Comment by cracker0dks** [comment]
vor allem gegen Ende glaubt sie sich doch selber nicht :D


Am 27.06.2016 um 16:51 schrieb ytjjyy:

**Comment by socay1** [comment]
@ytjjyy I need you, can you share your solution to me? I'm working on Centos 7.
Regards

**Comment by buzaki2** [comment]
@ytjjyy  me too please

**Comment by kalero** [comment]
Hi,

I'm also using CentOS 7. Could you post that script? Many thanks.
