### ISSUE TITLE
compile ErizoApi failed on Ubuntu 14.04.4 Server  x64

### ISSUE THREAD

**Issue by xxxman2008** [ging/licode#490]
Hi, all 

     Excute  installErizo.sh scripts failed .  error log.is :

     raymond@ubuntu:~$ sudo ./licode/scripts/installErizo.sh
Installing erizo...
-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE)
-- Found glib-2.0: /usr/include/glib-2.0, /usr/lib/x86_64-linux-gnu/libglib-2.0.so;/usr/lib/x86_64-linux-gnu/libgobject-2.0.so;/usr/lib/x86_64-linux-gnu/libgthread-2.0.so
-- Boost version: 1.54.0
-- Found the following Boost libraries:
--   thread
--   regex
--   system
-- Configuring done
-- Generating done
-- Build files have been written to: /home/raymond/licode/erizo/build
Done
[100%] Built target erizo

---------------  so, it seems  erizo  is compiled with no error  ---------------------------------------

Installing erizoAPI...
licode@0.1.0 /home/raymond/licode
└── nan@2.3.2

building with node-gyp
gyp info it worked if it ends with ok
gyp info using node-gyp@3.3.1
gyp info using node@4.4.6 | linux | x64
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/usr/local/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/raymond/licode/erizoAPI/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/raymond/.node-gyp/4.4.6/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/raymond/.node-gyp/4.4.6',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/raymond/licode/erizoAPI',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make:entering directory '/home/raymond/licode/erizoAPI/build'
  CXX(target) Release/obj.target/addon/addon.o
In file included from ../addon.cc:7:0:
../OneToManyTranscoder.h:29:42: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> New(const v8::Arguments& args);
                                          ^
../OneToManyTranscoder.h:29:57: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
   static v8::Handle<v8::Value> New(const v8::Arguments& args);
                                                         ^
../OneToManyTranscoder.h:34:44: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> close(const v8::Arguments& args);
                                            ^
../OneToManyTranscoder.h:34:59: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
   static v8::Handle<v8::Value> close(const v8::Arguments& args);
                                                           ^
../OneToManyTranscoder.h:39:51: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> setPublisher(const v8::Arguments& args);
                                                   ^
../OneToManyTranscoder.h:39:66: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
   static v8::Handle<v8::Value> setPublisher(const v8::Arguments& args);
                                                                  ^
../OneToManyTranscoder.h:43:51: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> hasPublisher(const v8::Arguments& args);
                                                   ^
../OneToManyTranscoder.h:43:66: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
   static v8::Handle<v8::Value> hasPublisher(const v8::Arguments& args);
                                                                  ^
../OneToManyTranscoder.h:49:52: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> addSubscriber(const v8::Arguments& args);
                                                    ^
../OneToManyTranscoder.h:49:67: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
   static v8::Handle<v8::Value> addSubscriber(const v8::Arguments& args);
                                                                   ^
../OneToManyTranscoder.h:54:55: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> removeSubscriber(const v8::Arguments& args);
                                                       ^
../OneToManyTranscoder.h:54:70: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
   static v8::Handle<v8::Value> removeSubscriber(const v8::Arguments& args);
                                                                      ^
make: *** [Release/obj.target/addon/addon.o] error 1
make:leaving directory “/home/raymond/licode/erizoAPI/build”
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.2.0-27-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/raymond/licode/erizoAPI
gyp ERR! node -v v4.4.6
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok

**Comment by lodoyun** [comment]
You are using node 4.4.6
Currently only node ~0.10.
