### ISSUE TITLE
ErizoController instances in distributed deploy

### ISSUE THREAD

**Issue by zevarito** [ging/licode#492]
Hi,

What are pros/cons about having 1 Erizo Controller & n Erizo Agents vs n Erizo Controllers and n Erizo Agents? Basically both apps living together in the same server.

Please correct me if I am wrong, since Erizo Controller is responsible for recording, in the 1 EC n EA, how that exactly works?

**Comment by kekkokk** [comment]
Erizo controller is not for recording purpose. 
Erizo controller is all about signaling. If you have only 1 controller, every single user in your platform will open a websocket on your controller. The controller also communicate thru amqper with your "core" library, which is written in C++ and handle everything concern the video stream.

For example, when you click 'record', from you client the request is sent to erizo controller thru websocket. The controller do some checks (ex. you have permissions) then he send a remote procedure call to your erizo Agent, which tells you associated erizoJs to start the recording process. 

the "erizo core" is inside every erizoJs, which are spawned by your erizoAgents.

**Comment by zevarito** [comment]
@kekkokk this confused me:

https://github.com/ging/licode/blob/master/scripts/licode_default.js#L103

**Comment by kekkokk** [comment]
yeah, this is used by the controller when telling the agent (in an remote procedure call) where to store the files.
