### ISSUE TITLE
why externalinput .webm( vp8&vorbis) not play audio

### ISSUE THREAD

**Issue by fanchuanster** [ging/licode#494]
[this is standard webm demo file](http://video.webmfiles.org/elephants-dream.webm).
Video plays well, but Audio not play, just noise.

Any suggestion, experts!!

**Comment by lodoyun** [comment]
That won't work. WebRTC does not support vorbis and Licode won't transcode it for you.
You should process the file to have vp8+opus for instance. Webm does not support that as a container, we use mkv.
