### ISSUE TITLE
what is the purpose of VP8 Fragment first byte

### ISSUE THREAD

**Issue by fanchuanster** [ging/licode#495]
Hi experts,

why the first byte buffer[0] is added for VP8?
unsigned [int RtpVP8Fragmenter::writeFragment](https://github.com/ging/licode/blob/88f6ca2379e54391e8471b3447deee7dd722ad37/erizo/src/erizo/rtp/RtpVP8Fragmenter.cpp#L54)(const Fragment& fragment,
		unsigned char* buffer, unsigned int* length) {

	if (VP8) {
		buffer[0] = 0x0;
		if (fragment.first)
			buffer[0] |= 0x10; // S bit 1 // era 01
		memcpy(&buffer[1], &totalData_[fragment.position], fragment.size);
		return (fragment.size + 1);
	} else {
		memcpy(&buffer[0], &totalData_[fragment.position], fragment.size);
		return fragment.size;
	}
}

https://github.com/ging/licode/blob/88f6ca2379e54391e8471b3447deee7dd722ad37/erizo/src/erizo/rtp/RtpVP8Fragmenter.cpp#L54

**Comment by lodoyun** [comment]
We're setting the S bit (S: Start of VP8 partition) more details in [RFC 7741](https://tools.ietf.org/html/rfc7741).
