### ISSUE TITLE
urgent: fix for mongojs installed which not compatible with node 0.10.x

### ISSUE THREAD

**Issue by nionis** [ging/licode#512]
The mongojs lib was updated from 2.3.0 -> 2.4.0 which uses some features like object.assign which are not supported by 0.10.x.

I would suggest making a proper package.json file for all the needed libs. Its actually quite brittle the way it is now.

**Comment by nionis** [comment]
here is the [pull request](https://github.com/ging/licode/pull/513)

**Comment by lodoyun** [comment]
Merged.
Thanks!
