### ISSUE TITLE
is licode an MCU or an SFU

### ISSUE THREAD

**Issue by nikhilrayaprolu** [ging/licode#518]
I have seen that SFU is more scalable than an MCU. even many other MCU based projects have implemented their system as an SFU( intel webrtc) . is licode an MCU or an SFU. if not an SFU ,do we have plans to make it do the functionality of an SFU

**Comment by lodoyun** [comment]
Erizo, the WebRTC core of Licode is an SFU. It does have minimal transcoding capabilities that we may expand on at some point but we avoid transcoding whenever we can. 

Fun fact: when I last checked, the Intel WebRTC thing included a modified version of Licode

**Comment by nikhilrayaprolu** [comment]
@lodoyun if intel MCU are able to add transcode capabilities for our code,why aren't we not adding it for original licode. What is the reason we are avoiding it right now?

**Comment by jnoring** [comment]
@nikhilrayaprolu an SFU is not "more scalable" than an MCU, depending on what you mean by "more scalable."  The reasons for avoiding it is that it's not a clear win, but a huge tradeoff.

**Comment by sebastianfelipe** [comment]
Well, but it works as MCU if the conversation is not a P2P, in that case, when the room is P2P set to true, then the connection is a Mesh?

**Comment by kekkokk** [comment]
MCU = have transcoding capabilities.
SFU = only "clone" packets and delivers to every participant.

when a licode room is set to p2p, it uses a mesh config. like you said.
when it's not set in p2p it acts like an sfu

**Comment by sebastianfelipe** [comment]
Perfect! Thanks, but why is not possible to use the mute audio/video with P2P communication? I think that is a client decision/characteristic and not a server feature.

**Comment by sebastianfelipe** [comment]
Due this, I'd like to know one thing more, using SFU or MCU connections, then the RTCPeerConnection API is not available anymore? or is used but considering the server as a peer? And about the security channel, does the connection still use the DTLS protocol in the session protected layer? Thanks.
