### ISSUE TITLE
How audio mixing can be useful

### ISSUE THREAD

**Issue by mkhahani** [ging/licode#533]
Hi everybody!
Sorry, I know it's a long post but I think it is worse to read.

Regarding to the media mixing, I know there is no plan for it at the moment in Licode project but I have three reasons that it can be useful, particularly the audio mixing:

**1. Bandwidth:** The bandwidth usage for an event (e.g. a web meeting) on the server side is calculated by multiplying the number of publishers(speakers) and the number of participants(1 send stream for the publisher & n-1 receive streams for listeners). By audio mixing the amount of bandwidth will decrease to just one publisher (this does not apply for video). For a small event it has not a noticeable impact but in a large scale event, a webinar with hundreds of participants for instance, every single publisher matters and audio mixing is strongly helpful. Let me explain this with an example. Consider a web meeting with 10 participants and 3 publishers (audio only) and a webinar with 100 participants and the same 3 publishers. Let's assume each audio stream creates 50 kbps bandwidth on the MCU. The result of audio mixing for these two scenarios is interesting:

```
10  users * 3 publishers * 50 kbps = 1,500  kbps => audio mixing saves 1,000 kbps (not much)
100 users * 3 publishers * 50 kbps = 15,000 kbps => audio mixing saves 10,000 kbps (10 mbps!)
```

It is while the costs of audio mixing (e.g. CPU, RAM) for a particular number of publishers (3 in this example) is always the same for any number of participants! And for audio mixing it would be not much.

You may say in a webinar there always would be only one publisher at a time. Oaky, then you would have to ask the speakers to turn on/off their mic when they start/stop speaking. By audio mixing you don't worry about the bandwidth any more even if all speakers are publishing.

**2. Latency:** This is even more important than the bandwidth. As you may know there is a latency when subscribing and unsubscribing to/from a publisher because the MCU does a lot of things for every user subscription. I've experienced that the number of participants affects this latency. For a large number of users the latency can grow up to several seconds depending on the server resources. Such a latency is really annoying in a big webinar. By having audio mixing there would be only one stream that every user subscribes to, so no more subscription/unsubscription when we are switching between publishers as far as there is at least one publisher at a time. Even I have a technique in mind that the MCU sends an empty stream when there is no publisher, so no unsubscription at all. This feature is very useful for webinars with float speakers which start and stop publishing frequently.

**3. Recording:** It is obviously easier to record, sync and replay only one stream rather than several steams. It needs less resources including CPU, RAM and disk space.

**Comment by mkhahani** [comment]
Any thought? Any one has experiences on audio mixing? Please let me know if I'm wrong, and if I'm not then I would like to help this feature to be added to Licode.

**Comment by jjahifi** [comment]
Proper audio mixing would be a nice feature. I would like it to be included in Licode and have been looking at technical possibilities. There are, however, a couple of issues that should be considered:

1. Would we like to have other audio processing features than just mixing? Compression, equalization etc. Compression (reduction of the dynamic range) is a quite useful tool when mixing sound from very diverse sources. If go for mixing, then there is no reason to leave those processing features out (or at least allow hooking already existing tools to the mixing system).

2. Would we like use "smart mixing" or not? Smart mixing would handle sound in the way that the person speaking would not get his/her own voice back. That would be nice, but makes mixing more complex and creates more than one mixed audio streams. The smart mixing would not be too difficult in itself, just use suitable trigger levels and time delays (may require some experimenting), but handling the streams might not be straightforward.

I would be happy to have mixing even without the smart features.

**Comment by jcague** [comment]
Audio mixing is not in the roadmap. We plan to continue developing a SFU without any kind of real-time mixing. Audio mixing has its advantages. There are other alternatives that could be interesting such as audio stream selection.

**Comment by mkhahani** [comment]
@jcague Thanks for the reply.
Would you please explain more about audio stream selection?

**Comment by jcague** [comment]
You can select and forward only those streams that you consider more important, and mute the rest. But again, you're right, SFU and MCU have their own pros and cons anyway.

**Comment by mars00772** [comment]
@mkhahani any audio/video mixer solution opensource code alternative, rtmp or webrtc was fine for me? cause my android platform‘s CPU is pool.
