### ISSUE TITLE
Video is not shown on client side using nodejs app 

### ISSUE THREAD

**Issue by codebazz** [ging/licode#563]
Failed to load '' as a plugin, because the frame into which the plugin is loading is sandboxed.

**Comment by codebazz** [comment]
`<div id="localVideo_container" class=" grid_element_border"><div id="localVideo" class=" grid_element"></div></div>`

**Comment by codebazz** [comment]
INFO: Requested access to local media
erizo.js (line 175)
DEBUG: Object { video=true,  audio=true,  fake=undefined,  more...}
erizo.js (line 175)
ERROR: Failed to get access to local media. Error code was undefined.
erizo.js (line 175)
DEBUG: Event: access-denied

**Comment by codebazz** [comment]
SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data
	

...("Room already connected");a.state=1;c(JSON.parse(e),function(c){var e=0,d=[],f,...

**Comment by jcague** [comment]
Can you give more info please? Browser, version, etc.

**Comment by vjaindev** [comment]
Hi,
I am also getting the same issue on firefox 50.1.0 and chrome Version 55.0.2883.87 (64-bit)

Browser logs:------------------------------------------
INFO:  Requested access to local media  erizo.js:177:478
DEBUG:  Object { video: Object, audio: true, fake: undefined, screen: "", extensionId: undefined }  erizo.js:177:478
No Erizo Controller found  connection_test.js:32:5
INFO:  Requested access to local media  erizo.js:177:478
DEBUG:  Object { video: Object, audio: true, fake: undefined, screen: undefined, extensionId: undefined }  erizo.js:177:478
INFO:  User has granted access to local media.  erizo.js:177:478
DEBUG:  Event: access-accepted  erizo.js:177:478
ERROR:  Failed to get access to local media. Error code was undefined.  erizo.js:177:478
DEBUG:  Event: access-denied

Erijo Logs in terminal:------------------------------------------------------------
{ username: 'user', role: 'presenter', room: 'basicExampleRoom' }
POST /createToken/ - - ms - -
GET /connection_test.html 304 1.128 ms - -
GET /erizo.js 304 0.389 ms - -
GET /connection_test.js 304 1.053 ms - -
{ username: 'user', role: 'presenter' }
404 ErrorNo Erizo Controller found
404 ErrorNo Erizo Controller found
POST /createToken/ 401 11015.960 ms - 25

Licode logs:---------------------------------------------------------------------------
2017-01-06 11:49:25.882  - ERROR: CloudHandler - No erizoController is available.
2017-01-06 11:49:35.212  - ERROR: CloudHandler - No erizoController is available.
2017-01-06 11:49:36.891  - ERROR: TokensResource - message: createToken error, errorMgs: No Erizo Controller available
2017-01-06 11:49:46.223  - ERROR: TokensResource - message: createToken error, errorMgs: No Erizo Controller available

It looks like create token request is not responding and I just executed all the scripts successfully and launched http://localhost:3001

Is there any more configuration needed to test the videoconference demo in local env using licode ?
ty

**Comment by codebazz** [comment]
I have solved the problem but enabling proper CORS from my application. It was not working in nodejs application where I used `JADE `as a template engine for view page. Using plain html and providing sandbox permission I have solved the problem

**Comment by ershubhamgupta1** [comment]
Hi @codebazz  i m also facing the same error i.e  Failed to get access to local media ,access denied
can u help me to get of this.

**Comment by neumerance** [comment]
@codebazz i'm having the same issue.
https://discourse.lynckia.com/t/failed-to-get-access-to-local-media-error-code-was-undefined/769

can you define how you fixed it?
