### ISSUE TITLE
disable  srtp encryption on licode?

### ISSUE THREAD

**Issue by notedit** [ging/licode#596]
srtp's  encryption   and decryption  will cost lots of cpu,  webrtc native code has a  disable_encryption  option.

does erizo  support this?

**Comment by notedit** [comment]
@lodoyun  can you give me some advise?

**Comment by lodoyun** [comment]
I'm afraid currently it's not possible but we're making changes in the implementation that could lead to changes like this to be easier.
If you're interested, you can propose the new feature following the [contributor guide](http://lynckia.com/licode/contribute.html) so we can discuss it.
