### ISSUE TITLE
which TURN server is being used?

### ISSUE THREAD

**Issue by siddo420** [ging/licode#620]
Is Licode still using the old turn server implementation or the more advanced ones like coTurn etc?

**Comment by lodoyun** [comment]
Licode does not use any turn server per-se. It should be compatible with any rfc compliant turn server.
If it doesn't, please feel free to open a new issue and we'll look into it

**Comment by siddo420** [comment]
Thanks for a quick response.

I am new to WebRTC but I fail to understand what Licode exactly is. If it works with any server then is it a client library like Adapter.js or something else? What does the server component do when its not a TURN/STUN server. Where in the WebRTC stack does Licode sit?

I've looked into client API and server API docs but not sure where Licode is used. 

What I understood from your reply is that Licode can be configured to use any TURN server or multiple TURN servers (for load balancing etc). I was referring to http://lynckia.com/licode/turn.html.

Please clarify.

**Comment by notedit** [comment]
licode support p2p and  server relay.  if you use the server relay, it does not need turn.

**Comment by siddo420** [comment]
Thanks notedit.

Is there a reason why its no supported  on FF? Is it not the same as WebRTC?
