### ISSUE TITLE
Audio only rooms doesn't seem to work

### ISSUE THREAD

**Issue by timmhuang** [ging/licode#626]
I was trying out the basic example and I wanted to create a room with only audio communication, so I changed the config's 'video' field from 'true' to 'false' inside script.js. After changing it, I couldn't hear anything like I used to when video is enabled. Is there anything in the documentation that talks about how to do this?

**Comment by timmhuang** [comment]
seems like I did not set it parameters correctly when subscribing to the stream. I got it to work after looking at the demo https://chotis2.dit.upm.es/ again.

**Comment by sureshkumar9887** [comment]
I can't get this answer clearly. Please explain me clearly. I am also facing this issue.
