### ISSUE TITLE
Closing stream does not remove it from "chrome://webrtc-internals"

### ISSUE THREAD

**Issue by mkhahani** [ging/licode#627]
Calling the `stream.close()` I still can see the stream in **chrome://webrtc-internals** but after leaving the room it disappears. I think we are missing some thing when closing the stream.

**Comment by kekkokk** [comment]
chrome doesn't remove the peerconnection tab until the page is closed. this is a wanted behaviour (i think for debug purpose).
What you want to check is the "stop" in the peerconnection log. 
ex.
![screen shot 2016-11-29 at 15 45 55](https://cloud.githubusercontent.com/assets/15072723/20714033/f65dccb4-b64a-11e6-839f-ff1a6fc1f975.png)

**Comment by mkhahani** [comment]
Good point! Makes sense.
Thank you.
