### ISSUE TITLE
Recording resolutions and aspect ratios

### ISSUE THREAD

**Issue by zevarito** [ging/licode#637]
How this[0] affect recording where the source video is different of that resolution and aspect ratio?
Should be this class updated to handle different sizes?

[0] https://github.com/ging/licode/blob/1961e22a57c2406de5bf3f638cc26dc9a434a7d9/erizo/src/erizo/media/ExternalOutput.cpp#L350

**Comment by kekkokk** [comment]
for my experience it doesn't affect the recording.
apparently ffmpeg can decode the resolution for every frame and change it dynamically.

**Comment by zevarito** [comment]
@kekkokk you right, I'll close this issue. Thanks!
