### ISSUE TITLE
canary 57 vp8 payloads != chrome 55

### ISSUE THREAD

**Issue by kekkokk** [ging/licode#641]
Hi guys,
Tried canary 57 yesterday and didn't worked as expected. 
signaling works just fine, the subscriber has an "stream added" and a "stream subscirbed". 
but the video is showing the loading icon forever and nothig flows in the peerconnection.

on the receiver side (chrome, chrome://webrtc-internals) the peerconnection identify correctly the audio channel, but the video seems broken: "codecImplementationName	unknown"
I receive the packets but seems unable to decode them.

digging in the offer/answer I noticed a payload number mismatch. here's a diff of the offer in both chrome and canary.
[https://www.diffchecker.com/Qmu68jdc](https://www.diffchecker.com/Qmu68jdc)
is it normal that chrome has vp8 = 100 and in canary vp8 = 96 or is a bug?

Thanks,
Francesco

**Comment by HemanthAnakapalle** [comment]
Hi Francesco,

How this is fixed for you?

Thanks,
Hemanth

**Comment by kekkokk** [comment]
I dont' know. everythng's fine. note that my version of licode is like a month old 'cause i heavily modded and I am waiting the simulcast feature to merge.
btw I'm successfully making calls from chrome 56/57/58.
Have you configured your TURN? maybe this is the issue.
It happened for a day than (I don't know how) everything's fine.

**Comment by HemanthAnakapalle** [comment]
Thanks for the information Francesco.
I will try to update my turn server version and see. It may help.

Thanks,
Hemanth
