### ISSUE TITLE
problem with record

### ISSUE THREAD

**Issue by lipku** [ging/licode#651]
I have recorded  mkv file in licode, the client is chrome.
when i play the mkv file in vlc, there is no sound.  The message is 
"opus error: cannot read Opus header
opus error: initial Opus header is corrupted"

How to resolve the problem. Thank you.

**Comment by kekkokk** [comment]
try to play it with ffplay. if you want to play it with any player you'll probably need to transcode it with ffmpeg. ex. ffmpeg -i filename -vsync 0 -c:a libopus out.mp4

**Comment by lipku** [comment]
thanks.. ffplay can play the mkv file.

**Comment by zombiecong** [comment]
@kekkokk Hi, does ffplay still work for you now? I try to play recorded mvk file with ffplay , it seems no sound. And I try the ffmpeg command you provided, it also does not work for me.Can you help me? :)
