### ISSUE TITLE
I run ./licode/scripts/installUbuntuDeps.sh ,And I get no .nvmrc file found Error

### ISSUE THREAD

**Issue by supernow** [ging/licode#660]
The Last error show:
```
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm
No .nvmrc file found
```

I can find .nvmrc is in the ./licode directory. Is this file the ".nvmrc" referred before？

**Comment by kekkokk** [comment]
try:
cd ./licode/scripts
then
./installUbuntuDeps.sh

**Comment by mccob** [comment]
usefull thank you
