### ISSUE TITLE
Bandwidth Estimation Handler stop working

### ISSUE THREAD

**Issue by kekkokk** [ging/licode#683]
Hi guys,
I'm doing some research on how to solve some multiparty problems when a user has a bad connection as described here [DISCOURSE](http://discourse.lynckia.com/t/adapt-schemes-not-working-as-expected/352/1)
Doing some tests I noticed that when you connect to server ALONE and start publishing, the bwe algorythm is working perfectly, in fact I can get my max bw very fast.

but, if another user join the call and subscribes to the video, and then leave the call, the bwe mechanism stop working. 

![grafico](https://cloud.githubusercontent.com/assets/15072723/21682831/f334b966-d356-11e6-8f45-c5f0535047db.jpg)

As you can see, i connect, wait until my bwe has ramped up, then join a subscriber. the subscriber has plenty of bandwidth and in fact it doesn't affect the publisher. suddently, the subscribed is forced to 1mbit download bw by the router, so the publisher adapt his throughput to approx @ 1mbit. everything ok until now.
but then the subscriber disconnect. what i will expect is a ramp up of the publisher since its alone and the bwe handler is sending to him large rembs. but it stuck @ 1mbit.

![grafico2](https://cloud.githubusercontent.com/assets/15072723/21682951/84087554-d357-11e6-8d81-6bef6015f980.jpg)

**Comment by jcague** [comment]
Thanks for the details! could you be limiting bw to 1mb also for the publisher in the router?

**Comment by kekkokk** [comment]
Honestly I was using Apple's link conditioner on the subscriber's pc. The publisher was on another pc, so no. It had a full 100/100 Mbit/s network at disposal

**Comment by jcague** [comment]
@kekkokk are you still seeing this issue?

**Comment by kekkokk** [comment]
@jcague yeah, I am waiting https://github.com/ging/licode/pull/705 to be merged to close the issue

**Comment by jcague** [comment]
great then! thanks!

**Comment by kekkokk** [comment]
solved with https://github.com/ging/licode/pull/705
thanks guys!

**Comment by menelike** [comment]
I'm getting the same exact same error/behavior on the current master (https://github.com/lynckia/licode/commit/33c7f5a148fcd0b5ff139f7e685e5d3b1e2803e6) on `Google Chrome Version 58.0.3029.110 (64-bit) osX`. It only happens in 1/50? times without any chance to reproduce the positive test.

Currently I need to comment/disable `goog-remb` in `rtp_meda_config` to make it work again.
To my surprise this only happens on our servers (Azure hosted) and never on localhost. Tested with enough bandwidth and low latency (100mbit fiber to home, tested on other networks). 

I assume that this is a latency issue. Unfortunetly I'm no expert in this stack and wasn't able to get gather appropiate debug messages.
