### ISSUE TITLE
Bandwidth Estimation Handler FPS

### ISSUE THREAD

**Issue by kekkokk** [ging/licode#689]
Hi guys,
I'm here again with some strange considerations:

Long story short:
In some cases where the fps output reach 30, the bwe fails and take the bandwidth down causing poor quality.
happens to me every time I use my Logitech c920 with my MacbookPro

TLDR:
Talking about the bwe handler.

never had an issue until now, tested with about 5 different macs and 3 different windows machines.
usually, I used the internal webcam of each laptop; they are different but what have they in common:
they are 720p
they never reach 30fps <- that's the tricky part I think

so, implemented the RR mechanism to avoid some issues as I described in my previous PR and wanted to test with much hardware I can.

I have 2 external webcam:
Logitech c920  1080p 30fps
Logitech c270   720p  30fps

My basicexample is set to 720p for each test.

What I noticed is that my c920 + my macbookPro NEVER reachs the upper bound of the bwe in chrome.
The internal camera always ramp up to 2Mbit which is my limit and is just OK.
Strange, so I hooked the c920 to another macbookPro, same results:

![screen shot 2017-01-11 at 17 37 01](https://cloud.githubusercontent.com/assets/15072723/21887526/93637062-d8c0-11e6-9cf8-33c15c0caa7b.png)

so I started some combinations:
windows + c920 = works great
older macbook (same os) + c920 = works great (so it's not an osx issue)
another windows machine + c920 = works great.
another macbookPro (newest one) + c920 = works great.
my 2 macbook pro (2011,2012) + macbook pro of my friend (2011) = NOT work as expected

the other c270 works in every laptop.
The only conclusion is that windows NEVER does this unwanted behaviour and that it only affects the c920 camera + osx. 

So, what makes this camera different from others? it's newer and obviously more powerful.
I did check the FP (chrome://webrtc-insternals): 
- the integrated cameras on these laptops and the c270 never reach 30fps. 
- the c920 stay about 30fps in and 30fps out. sometimes the IN fps goes up to 31.
   noticed that if the sentFps drop from 30 to something < 30 cause a bwe drop.

So, the last test was to limit the fps in the constraints of getusermedia.
Max fps set to 29 -> everything works just fine.

Recap:
on majority of mac, the c920 @ 30fps cause a wrong bwe estimation.
on all windows, the c920 @ 30fps works fine
on mac, if capped @ 29 fps works fine BUT the input fps are around 22-24 (shouldn't be 29????) 
on windows, if capped @ 29 (just to try, it worked great also without a cap) it works and the input framerate is actually 29.

I think that the last consideration is caused by different drivers used by windows vs osx. it seems that on windows the constraints cap are more precise than the osx ones.

What I found then, is that the algorythm used by bwe in some cases fail, resulting in a very bad quality and MAYBE it has something to do with FPS.

@jcague do you have any clue about that?

**Comment by jcague** [comment]
@kekkokk thanks for the report! it's quite useful! 

I think I haven't got any problem with 30fps but according to your statement my camera has never reached that value probably, so I'd need to try again.

Anyway, we've seen situations where bwe is not behaving as expected (sending extremely low values) so we're currently investigating and will try to figure out the reasons. Meanwhile we'll add a mechanism to enable/disable it by configuration just to let people disable it when needed.

**Comment by kekkokk** [comment]
Yeah, as I said I'm not totally sure about the FPS, tried with manyCam set to 60 fps and sometimes behaved good, sometimes not, but i was not at 720p so the test was not very useful. 

But for sure there's something that sometimes broke the mechanism. 
Let's keep in touch!

**Comment by kekkokk** [comment]
@jcague 
So, it seems that setting
`config.erizoAgent.useIndividualLogFiles = true;`
in licode_config, and examinating the log produced, every incoming packet generate an:

`(rtp_utility.cc:342): Failed to find extension id: 5`

This is not printed in stdoutput when 
`config.erizoAgent.useIndividualLogFiles = false;`

From my studies, rtp_utility.cc which is native webrtc code is used in the bwe handler.
Maybe this has something to do with this problem?

**Comment by jcague** [comment]
@kekkok can you try with PR #712? it should solve an issue we found with Chrome 55. The PR changes the default rtp_media_config.js file, so be sure to update it too.

**Comment by kekkokk** [comment]
sure, give me a couple of hours

**Comment by kekkokk** [comment]
@jcague 
I can confirm it's working flawlessly. I'm so happy guys. 
I've only tested it in localhost, in these days I'll check everything is working on the servers too. 
I have tried it also with the rr_generation_handler and noticed that the RTT calculations results more accurate.
I'll keep you updated. thanks guys
