### ISSUE TITLE
The documentation can't be worse than this

### ISSUE THREAD

**Issue by aghasoroush** [ging/licode#690]
Docker is completely useless :)
And every single time there is a different error in build :)
How can it be that bad ?

**Comment by aalonsog** [comment]
We always try to make it compatible with the last changes in the code. Could you share the specific error you are getting?

And... of course you can also try to contribute a fix

**Comment by aghasoroush** [comment]
Okay, ty. I will fix the docker asap.

**Comment by jcague** [comment]
closing it until we have more data.
