### ISSUE TITLE
db.erizoControllers does not exists

### ISSUE THREAD

**Issue by garcianavalon** [ging/licode#708]
Hi,

after updating to the latest commit we are having the following error when starting licode
```
/usr/share/licode/nuve/nuveAPI/mdb/erizoControllerRegistry.js:11
    db.erizoControllers.find({}).toArray(function (err, erizoControllers) {
                        ^
TypeError: Cannot call method 'find' of undefined
    at Object.exports.getErizoControllers (/usr/share/licode/nuve/nuveAPI/mdb/erizoControllerRegistry.js:11:25)
    at checkKA (/usr/share/licode/nuve/nuveAPI/cloudHandler.js:90:29)
    at wrapper [as _onTimeout] (timers.js:261:14)
    at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)
```

[The error line](https://github.com/ging/licode/blob/master/nuve/nuveAPI/mdb/erizoControllerRegistry.js#L11) whats to use the `erizoControllers` property of the `db` object. But looking at the [database code](https://github.com/ging/licode/blob/master/nuve/nuveAPI/mdb/dataBase.js) the erizoControllers property is not created anywhere.

It seems like a bug in the code. Can you help us with this issue?

Thanks!

**Comment by kekkokk** [comment]
i don't remember where exactly they're created but probably an ./installErizo && ./installNuve will fix your probl.

**Comment by garcianavalon** [comment]
thanks @kekkokk I'll try your fix

**Comment by wolmi** [comment]
I've already executed both scripts and still have the issue

**Comment by aalonsog** [comment]
It should be fixed in https://github.com/ging/licode/pull/710

Thanks!

**Comment by garcianavalon** [comment]
Thanks @aalonsog for the quick fix! :)
