### ISSUE TITLE
REMB bitrate is stuck

### ISSUE THREAD

**Issue by kekkokk** [ging/licode#718]
Hi guys, 
I just noticed that with the PR https://github.com/ging/licode/pull/712 a huge bug was introduced.
the bwe handler actually is stuck with a value.

the googavailablereceivebandwidth never grows, it can only decrease (on bandwidth fluctuation):
![screen shot 2017-01-27 at 17 00 00](https://cloud.githubusercontent.com/assets/15072723/22377393/fce2e584-e4b1-11e6-9e17-251629c301a7.png)

so obviously the publisher will send at that max rate:

![223021705_14931336985890982653](https://cloud.githubusercontent.com/assets/15072723/22377415/130092d0-e4b2-11e6-8612-24d44a93d401.jpg)

As you can see the REMB value never changes (the values are inconsistent with the previous pictures, this screenshot was taken in a different time):
![screen shot 2017-01-27 at 17 03 22](https://cloud.githubusercontent.com/assets/15072723/22377510/8943ab12-e4b2-11e6-99c9-67802ea2f85f.png)

[UPDATE]
It also seems that the probe fails after the X try: 
![screen shot 2017-01-30 at 11 32 05](https://cloud.githubusercontent.com/assets/15072723/22419871/b109071c-e6df-11e6-8909-65e52c36c109.png)

**Comment by kekkokk** [comment]
apparently, leaving transport-cc commented in rtp_mappings, will break the recvAvailableBW and the remb mechanism.
uncommenting the line, everything came back to works as before, so, for example the "30fps" problem (I know that is probably not related to fps, but I'll call it like this for practice) PERSIST.
`mediaConfig.extMappings = [
  "urn:ietf:params:rtp-hdrext:ssrc-audio-level",
  "http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time",
  "urn:ietf:params:rtp-hdrext:toffset",
  "urn:3gpp:video-orientation",
  // "http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01",
  "http://www.webrtc.org/experiments/rtp-hdrext/playout-delay"
];`

Interestingly, also enabling transport-cc in the feedbackTypes, 
`mediaConfig.rtpMappings.vp8 = {
    payloadType: 100,
    encodingName: 'VP8',
    clockRate: 90000,
    channels: 1,
    mediaType: 'video',
    feedbackTypes: [
        'ccm fir',
        'nack',
        'nack pli',
        'goog-remb',
       'transport-cc',
    ],
};`

seems to fix everything. 
Chrome will read googAvailableReceiveBandwidth as 0, but the "30fps" problem seems gone and everything seems working fine, adjusting the bandwidth correctly.

I never asked why transport-cc is disabled, and what it effectively is. 
The only thing I saw with transport-cc enabled is that REMBS are not sent anymore and a lot of NACKS are forwarded.

Can you please give me more infos about that?
I also made you aware that the current master branch version of licode will not work as expected, as the minimum bandwidth drop will degradate permanently the quality and will never ramp up again.

**Comment by jcague** [comment]
I just did a test to limit the bandwidth and it seems to work if I decrease and increase the available bandwidth between the publisher and Erizo, so I'm not able to reproduce your issue yet.

Regarding transport-cc, it should work as you said, between Chrome browsers, but then REMBs will not work anymore and they are an important part of Erizo. Firefox won't work neither because it doesn't support transport-cc, AFAIK.

**Comment by kekkokk** [comment]
did you tried with publisher only and subscriber only? if you try to reduce the incoming bandwidth of the subscriber, do you see googAvailableReceiveBandwidth decrease?
![223024786_6722215696911708879](https://cloud.githubusercontent.com/assets/15072723/22429222/2c3ed1a8-e70a-11e6-89c8-0413c01bfc10.jpg)

This is a pic of a subscriber capped @ 200kbit. it is stuck @ 1mbit on the subscriber and never changes, never goes up/down.

I am now deploying a new aws instance to try the master branch on a fresh install but I am facing this issue in localhost (osx) and my develop instance (ubuntu 14.04), tried also with chrome 55 to chrome 55, chrome 56 to chrome 56 and chrome 55 to chrome 56.

**Comment by jcague** [comment]
where does that stats come from?

**Comment by kekkokk** [comment]
I have 2 macbook. one publish only and one subscriber only.
these stats are from the subscriber only laptop. 
chrome calculates its availableReceivebw as 1mbit at the start of the call and never updates. this cause the subscriber to send REMBS to the publisher with 1mbit value.

before the PR#712 that value was constantly updated with meaningful data

**Comment by kekkokk** [comment]
Ok so, tried with an aws fresh install: same issue; 
to reproduce:
launched aws Ubuntu 14.04 instance.
logged in
install git via apt
cloned licode
./installUbuntuDeps
./installErizo
./installNuve
./installBasicExample

add "amazon" in licode config cloud provider.
enabled both ssl and set maxVideoBW to 3000.

./initLicode && ./initBasicexample

on one pc go to https://aws-instance-ip:3004 (publisher)
check webrtc://internals => everything's fine, bw ramp_up 

join with a subscriber on another pc ho to https://aws-instance-ip:3004?onlySubscribe=true (subscriber)
check webrtc://internals. googAvailableBw has a value, and this value NEVER adjust.

in my tests for example, the first time I joined was 3mbit (awesome!!)
just reload the page and was 300kbit ( :( )  -> this cause the subscriber to constantly send 300kbit remb to publisher.
if I reload another time I'll get another "random" value (in my case 800kbit)

to go further, I'll tried to cap my bw on the subscriber but these values never changes. this will break all our rembs mechanism.

sorry for my english, if some parts aren't so clear I can make a video

**Comment by jcague** [comment]
We found the issue, @lodoyun is working on a fix right now. Thanks for the info @kekkokk!

**Comment by kekkokk** [comment]
thank you guys, it's a pleasure working with you!
